In [20]:
import pandas as pd
import numpy as np

# Merge Panel Data

In [21]:
# 1. Load the data
df1 = pd.read_csv("data/panel_data.csv")
df2 = pd.read_csv("data/esg_panel_data.csv")

# 2. DROP THE EXTRA HEADER ROWS
df1 = df1[df1["Year"] != "Year"]
df2 = df2[df2["Year"] != "Year"]

# 3. NOW it is safe to convert them to integers
df1["Year"] = df1["Year"].astype(int)

# (df2's columns were renamed in your cell 12, so make sure to do that first)
df2.columns = ['company', 'isin', 'country', 'Year', 'emissions_intensity',
       'environmental_investment', 'internal_carbon_pricing']
df2["Year"] = df2["Year"].astype(int)

In [22]:
df1.head()

,company,ticker,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,net_cash_flow_operating_actv,net_sales_or_revenues,operating_income,return_on_assets,return_on_equity_total,total_assets,total_capital,total_debt,total_liabilities,tri
0,3-2 INVESTMENT,C32.HM,Vietnam,2009,NaN,NaN,17626663.0,16475504.0,137674980.0,85237198.0,...,73326604.0,261484630.0,46452397.0,NaN,NaN,232460719.0,147223522.0,11194597.0,85833310.0,NaN
1,3-2 INVESTMENT,C32.HM,Vietnam,2010,NaN,NaN,17265301.0,11054438.0,152181932.0,81189068.0,...,18436157.0,304652527.0,57069600.0,18.06,27.46,242453063.0,161184637.0,13054186.0,81844514.0,NaN
2,3-2 INVESTMENT,C32.HM,Vietnam,2011,NaN,4090.91,28431946.0,8742910.0,163477837.0,72876736.0,...,49037391.0,373219753.0,69917952.0,21.96,32.29,272271065.0,199337595.0,28538479.0,101471949.0,100.05
3,3-2 INVESTMENT,C32.HM,Vietnam,2012,NaN,1022.73,3610136.0,54588281.0,193610957.0,81334774.0,...,49698352.0,333154185.0,57707764.0,16.24,24.34,292602989.0,211268215.0,28000000.0,109334774.0,40.8
4,3-2 INVESTMENT,C32.HM,Vietnam,2013,4924.24,4734.84,9709328.0,38118699.0,237449813.0,110128828.0,...,115143396.0,427534725.0,95149861.0,22.14,33.04,330118228.0,219989400.0,28000000.0,110128828.0,311.03

In [23]:
df2.head()

,company,isin,country,Year,emissions_intensity,environmental_investment,internal_carbon_pricing
0,3-2 INVESTMENT AND,VN000000C325,Vietnam,2015,2546.06881537,NaN,NaN
1,3-2 INVESTMENT AND,VN000000C325,Vietnam,2016,2819.72533457,NaN,NaN
2,3-2 INVESTMENT AND,VN000000C325,Vietnam,2017,4362.53269686,NaN,NaN
3,3-2 INVESTMENT AND,VN000000C325,Vietnam,2018,3615.6048792,NaN,NaN
4,3-2 INVESTMENT AND,VN000000C325,Vietnam,2019,1825.21286898,NaN,NaN

In [24]:
# load market data
vn = pd.read_csv("data/vn-market.csv")
tl = pd.read_csv("data/tl-market.csv")
ml = pd.read_csv("data/ml-market.csv")
sing = pd.read_csv("data/sing-market.csv")
pp = pd.read_csv("data/pp-market.csv")
other = pd.read_csv("data/other-market.csv")

In [25]:
market_data = pd.concat([vn, tl, ml, sing, pp], ignore_index=True)
market_data.drop("currency", axis=1, inplace=True)

other = other.reindex(columns=["name", "ric", "org_permid", "isin"])
market_data = pd.concat([market_data, other], ignore_index=True)

In [26]:
tmp1 = pd.merge(df2, market_data, on="isin", how="inner")
tmp1.drop(["name", "org_permid", "company", "country"], axis=1, inplace=True)

In [27]:
df1.columns = ['company', 'ric', 'country', 'Year', 'ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities',
       'tri']

In [28]:
df1["Year"] = df1["Year"].astype(int)
tmp1["Year"] = tmp1["Year"].astype(int)

merge_data = pd.merge(df1, tmp1, on=["ric", "Year"], how="left")
merge_data

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,return_on_equity_total,total_assets,total_capital,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,internal_carbon_pricing
0,3-2 INVESTMENT,C32.HM,Vietnam,2009,NaN,NaN,17626663.0,16475504.0,137674980.0,85237198.0,...,NaN,232460719.0,147223522.0,11194597.0,85833310.0,NaN,NaN,NaN,NaN,NaN
1,3-2 INVESTMENT,C32.HM,Vietnam,2010,NaN,NaN,17265301.0,11054438.0,152181932.0,81189068.0,...,27.46,242453063.0,161184637.0,13054186.0,81844514.0,NaN,NaN,NaN,NaN,NaN
2,3-2 INVESTMENT,C32.HM,Vietnam,2011,NaN,4090.91,28431946.0,8742910.0,163477837.0,72876736.0,...,32.29,272271065.0,199337595.0,28538479.0,101471949.0,100.05,NaN,NaN,NaN,NaN
3,3-2 INVESTMENT,C32.HM,Vietnam,2012,NaN,1022.73,3610136.0,54588281.0,193610957.0,81334774.0,...,24.34,292602989.0,211268215.0,28000000.0,109334774.0,40.8,NaN,NaN,NaN,NaN
4,3-2 INVESTMENT,C32.HM,Vietnam,2013,4924.24,4734.84,9709328.0,38118699.0,237449813.0,110128828.0,...,33.04,330118228.0,219989400.0,28000000.0,110128828.0,311.03,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84080,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.78,135794.0,349551.0,1377820.0,239360.0,...,28.04,4246645.0,3998756.0,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.61331027,NaN,N
84081,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.78,135794.0,349551.0,1377820.0,239360.0,...,28.04,4246645.0,3998756.0,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.61331027,NaN,N
84082,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.78,135794.0,349551.0,1377820.0,239360.0,...,28.04,4246645.0,3998756.0,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.61331027,NaN,N
84083,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.78,135794.0,349551.0,1377820.0,239360.0,...,28.04,4246645.0,3998756.0,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.61331027,NaN,N
84084,ZETRIX AI BHD,ZETR.KL,Malaysia,2025,0.98,0.975,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,12208.83,NaN,NaN,NaN,NaN

In [29]:
# Reset the index so it starts from 0 cleanly
merge_data = merge_data.reset_index(drop=True)

# Drop redundant duplicate rows if the market data caused any
merge_data = merge_data.drop_duplicates(subset=["ric", "Year"])

# Verify the final count 
print("Final Cleaned Panel Rows:", len(merge_data))
merge_data.head()

Final Cleaned Panel Rows: 69806

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,return_on_equity_total,total_assets,total_capital,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,internal_carbon_pricing
0,3-2 INVESTMENT,C32.HM,Vietnam,2009,NaN,NaN,17626663.0,16475504.0,137674980.0,85237198.0,...,NaN,232460719.0,147223522.0,11194597.0,85833310.0,NaN,NaN,NaN,NaN,NaN
1,3-2 INVESTMENT,C32.HM,Vietnam,2010,NaN,NaN,17265301.0,11054438.0,152181932.0,81189068.0,...,27.46,242453063.0,161184637.0,13054186.0,81844514.0,NaN,NaN,NaN,NaN,NaN
2,3-2 INVESTMENT,C32.HM,Vietnam,2011,NaN,4090.91,28431946.0,8742910.0,163477837.0,72876736.0,...,32.29,272271065.0,199337595.0,28538479.0,101471949.0,100.05,NaN,NaN,NaN,NaN
3,3-2 INVESTMENT,C32.HM,Vietnam,2012,NaN,1022.73,3610136.0,54588281.0,193610957.0,81334774.0,...,24.34,292602989.0,211268215.0,28000000.0,109334774.0,40.8,NaN,NaN,NaN,NaN
4,3-2 INVESTMENT,C32.HM,Vietnam,2013,4924.24,4734.84,9709328.0,38118699.0,237449813.0,110128828.0,...,33.04,330118228.0,219989400.0,28000000.0,110128828.0,311.03,NaN,NaN,NaN,NaN

In [30]:
gb = pd.read_csv("data/greenbonds.csv")

In [31]:
gb.head()

,Exceeded the limit for the Number of Deals,Package Identifier,Master Deal Type Code,All New Issues Manager Roles Code,Manager's Role Code,Dates: Issue Date,Issuer/Borrower Name Full,Issuer/Borrower PermID,Issue Type,Transaction Status,...,Issuer/Borrower TRBC Business Sector,Issuer/Borrower TRBC Economic Sector,Lead Left Bookrunner,Managers Tier 1 & Tier 2,ECM Flag,Primary Use Of Proceeds,Issuer/Borrower Nation Region,Master Deal Type,All New Issues Manager Roles,Manager's Role
0,154084480389,3480516,D,JB|JB|JB|CM|CM|CM|CM,JB|JB|JB|CM|CM|CM|CM,8/1/2017,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
1,154084486562,3480516,D,JB|JB|JB|CM|CM|CM|CM,JB|JB|JB|CM|CM|CM|CM,8/1/2017,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
2,154084490384,9983331,D,JB|JB|JB,JB|JB|JB,3/12/2015,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Morgan Stanley &...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
3,154084593248,3319100,D,JB|JB|JB,JB|JB|JB,8/9/2016,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
4,154084594902,3319989,ED,JB|JB|JB|JB|JB,JB|JB|JB|JB|JB,8/10/2016,Greenko Investment Co,5.051761e+09,High Yield Corporate,Live,...,Banking & Investment Services,Financials,Deutsche Bank,Deutsche Bank|Investec Bank Ltd|JP Morgan & Co...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,Euro & Foreign Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...

In [32]:
gb["Year"] = pd.to_datetime(gb["Dates: Issue Date"]).dt.year
# Keep only necessary columns
gb = gb[["Issuer/Borrower PermID", "Year", "Proceeds Amount This Market"]].rename(columns={"Issuer/Borrower PermID": "org_permid"})
# Standardize org_permid to string to match market_data
gb["org_permid"] = gb["org_permid"].apply(lambda x: str(int(x)) if pd.notna(x) else np.nan)
gb.head()

   org_permid  Year  Proceeds Amount This Market
0  8589934162  2017                     495.8600
1  8589934162  2017                     746.4825
2  8589934162  2015                     496.4700
3  8589934162  2016                     798.2320
4  5051761072  2016                     500.0000

In [33]:
market_data["org_permid_str"] = pd.to_numeric(market_data["org_permid"], errors='coerce')
market_data["org_permid_str"] = market_data["org_permid_str"].apply(lambda x: str(int(x)) if pd.notna(x) else np.nan)
# Map PermID to RIC
gb_mapped = pd.merge(gb, market_data[["org_permid_str", "ric"]].dropna(), left_on="org_permid", right_on="org_permid_str", how="inner")
gb_mapped.head()

   org_permid  Year  Proceeds Amount This Market org_permid_str       ric
0  4295888106  2017                        500.0     4295888106   DBSM.SI
1  4295888106  2017                        500.0     4295888106    DBSM.F
2  4295888106  2017                        500.0     4295888106  DBSDF.PK
3  4295888106  2017                        500.0     4295888106  DBSDY.PK
4  4295888106  2017                        500.0     4295888106   DEVGy.F

In [34]:
gb_agg = gb_mapped.groupby(["ric", "Year"], as_index=False).agg(
    green_bond_proceeds=("Proceeds Amount This Market", "sum")
)
gb_agg["green_bond_issue"] = 1
gb_agg.head()

         ric  Year  green_bond_proceeds  green_bond_issue
0  009830.KS  2021           152.832755                 1
1   ACDSF.PK  2020           511.413086                 1
2    ALCO.PS  2020           118.319858                 1
3   ALCPD.PS  2020            59.159929                 1
4   ALCPF.PS  2020            59.159929                 1

In [35]:
final_panel = pd.merge(merge_data, gb_agg, on=["ric", "Year"], how="left")
# Fill missing values from the merge with 0 (since no issuance = 0)
final_panel["green_bond_issue"] = final_panel["green_bond_issue"].fillna(0)
final_panel["green_bond_proceeds"] = final_panel["green_bond_proceeds"].fillna(0)
# Create the cumulative Green Bond dummy (1 for the year of issue and all years after)
final_panel = final_panel.sort_values(by=["ric", "Year"])
final_panel["green_bond_active"] = final_panel.groupby("ric")["green_bond_issue"].cumsum().clip(upper=1)
print(final_panel.shape)
final_panel.head()

(69806, 33)

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,internal_carbon_pricing,green_bond_proceeds,green_bond_issue,green_bond_active
21181,9F INC,0,Malaysia,2020,163.86,1093.28,79.47,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
21182,9F INC,0,Malaysia,2021,34.6,263.34,17.24,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
21183,9F INC,0,Malaysia,2022,19.5,171.86,9.41,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
21184,9F INC,0,Malaysia,2023,2.07,19.26,1.03,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
21185,9F INC,0,Malaysia,2024,2.46,23.88,1.28,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [36]:
final_panel = final_panel.sort_index()

In [37]:
final_panel

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,internal_carbon_pricing,green_bond_proceeds,green_bond_issue,green_bond_active
0,3-2 INVESTMENT,C32.HM,Vietnam,2009,NaN,NaN,17626663.0,16475504.0,137674980.0,85237198.0,...,11194597.0,85833310.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1,3-2 INVESTMENT,C32.HM,Vietnam,2010,NaN,NaN,17265301.0,11054438.0,152181932.0,81189068.0,...,13054186.0,81844514.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,3-2 INVESTMENT,C32.HM,Vietnam,2011,NaN,4090.91,28431946.0,8742910.0,163477837.0,72876736.0,...,28538479.0,101471949.0,100.05,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,3-2 INVESTMENT,C32.HM,Vietnam,2012,NaN,1022.73,3610136.0,54588281.0,193610957.0,81334774.0,...,28000000.0,109334774.0,40.8,NaN,NaN,NaN,NaN,0.0,0.0,0.0
4,3-2 INVESTMENT,C32.HM,Vietnam,2013,4924.24,4734.84,9709328.0,38118699.0,237449813.0,110128828.0,...,28000000.0,110128828.0,311.03,NaN,NaN,NaN,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69801,SOLARVEST HOLD,SOLA.KL,Malaysia,2017,NaN,NaN,1592.0,NaN,14578.0,7928.0,...,10380.0,16249.0,NaN,MYQ0215OO002,5819.55947217,NaN,NaN,0.0,0.0,0.0
69802,SOLARVEST HOLD,SOLA.KL,Malaysia,2018,NaN,NaN,2517.0,NaN,21385.0,8385.0,...,10805.0,16717.0,NaN,MYQ0215OO002,6250.15559179,NaN,NaN,0.0,0.0,0.0
69803,SOLARVEST HOLD,SOLA.KL,Malaysia,2019,NaN,NaN,1594.0,NaN,69155.0,44251.0,...,19753.0,56364.0,NaN,MYQ0215OO002,6901.32257892,NaN,NaN,0.0,0.0,0.0
69804,ZETRIX AI BHD,ZETR.KL,Malaysia,2005,NaN,NaN,471,987,4297,1953,...,133,1991,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
69805,ZETRIX AI BHD,ZETR.KL,Malaysia,2006,NaN,NaN,221.0,2277.0,7930.0,1852.0,...,33.0,1865.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [38]:
# 1. Load the Series Data
series_df = pd.read_csv("data/series_data.csv")

# 2. We only need the 'ticker' (which is the ric) and 'gic' columns
# (You already have the 'country' column in your final_panel)
series_df = series_df[['ticker', 'gic']]

# 3. Rename 'ticker' to 'ric' so it perfectly matches the final_panel column name
series_df = series_df.rename(columns={'ticker': 'ric'})

# 4. Merge the GIC codes back into the master panel!
final_panel = pd.merge(final_panel, series_df, on="ric", how="left")

# Print to check the output
print(final_panel.shape)

# (Optional: If you appended multiple times, the series data might have duplicates too)
# Run this just to be perfectly safe, then save:
final_panel = final_panel.drop_duplicates(subset=["ric", "Year"])

(70540, 34)

In [39]:
final_panel.to_csv("processed_data/final_data.csv")

# Data Processing

In [40]:
final_panel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69806 entries, 0 to 70538
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   company                       69795 non-null  object
 1   ric                           69806 non-null  object
 2   country                       69806 non-null  object
 3   Year                          69806 non-null  int64
 4   ask_price                     55746 non-null  object
 5   bid_price                     33977 non-null  object
 6   capital_expenditures          46916 non-null  object
 7   cash                          31585 non-null  object
 8   current_assets_total          19542 non-null  object
 9   current_liabilities_total     19559 non-null  object
 10  earnings_bef_interest_tax     22018 non-null  object
 11  employees                     12560 non-null  object
 12  interest_expense_total        2602 non-null   object
 13  long_term_debt                22295 non-null  object
 14  market_capitalization         20739 non-null  object
 15  market_value                  20990 non-null  object
 16  net_cash_flow_operating_actv  22737 non-null  object
 17  net_sales_or_revenues         22711 non-null  object
 18  operating_income              22482 non-null  object
 19  return_on_assets              21825 non-null  object
 20  return_on_equity_total        21590 non-null  object
 21  total_assets                  22952 non-null  object
 22  total_capital                 22803 non-null  object
 23  total_debt                    22737 non-null  object
 24  total_liabilities             22948 non-null  object
 25  tri                           21043 non-null  object
 26  isin                          31753 non-null  object
 27  emissions_intensity           29854 non-null  object
 28  environmental_investment      6107 non-null   object
 29  internal_carbon_pricing       8674 non-null   object
 30  green_bond_proceeds           69806 non-null  float64
 31  green_bond_issue              69806 non-null  float64
 32  green_bond_active             69806 non-null  float64
 33  gic                           67598 non-null  object
dtypes: float64(3), int64(1), object(30)
memory usage: 18.6+ MB

In [50]:
tmp1 = final_panel[final_panel["environmental_investment"].notna()]
tmp1

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_liabilities,tri,isin,emissions_intensity,environmental_investment,internal_carbon_pricing,green_bond_proceeds,green_bond_issue,green_bond_active,gic
295,BAMBOO CAPITAL,BCG.HM,Vietnam,2020,3809.53,3803.25,2128566266.0,903386455.0,11338108288.0,10609458385.0,...,21129013950.0,36.62,VN000000BCG5,511.81584085,N,N,0.000000,0.0,0.0,1.0
296,BAMBOO CAPITAL,BCG.HM,Vietnam,2021,9852.27,9783.86,2153024873.0,1044039648.0,16238689244.0,10197137593.0,...,29269706359.0,105.94,VN000000BCG5,727.22184486,N,N,0.000000,0.0,0.0,1.0
297,BAMBOO CAPITAL,BCG.HM,Vietnam,2022,20519.48,20389.61,3452957149.0,629496376.0,17761709187.0,11380169032.0,...,29880498716.0,232.38,VN000000BCG5,522.08967477,N,N,0.000000,0.0,0.0,1.0
298,BAMBOO CAPITAL,BCG.HM,Vietnam,2023,5836.36,5827.27,132426498.0,756859465.0,19478597670.0,12090231560.0,...,24391498715.0,68.36,VN000000BCG5,497.57761896,N,N,0.000000,0.0,0.0,1.0
299,BAMBOO CAPITAL,BCG.HM,Vietnam,2024,7645.45,7636.36,287264578.0,722226655.0,22192281556.0,13228418571.0,...,24981189520.0,89.59,VN000000BCG5,572.12359601,N,NaN,0.000000,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70498,HANWHA SOLUTIONS,009830.KS,Other,2020,20480.87,20426.54,883786181.0,1199836791.0,4958364766.0,5251125587.0,...,9090711887.0,1547.81,KR7009830001,5643.6770326,Y,N,0.000000,0.0,0.0,1.0
70499,HANWHA SOLUTIONS,009830.KS,Other,2021,52523.2,52467.56,812670936.0,1651530298.0,6159819811.0,5789061165.0,...,11676167795.0,3975.71,KR7009830001,4885.61560282,Y,N,152.832755,1.0,1.0,1.0
70500,HANWHA SOLUTIONS,009830.KS,Other,2022,37111.2,37055.56,902923088.0,2616168297.0,8642576225.0,6810183012.0,...,13726017132.0,2812.09,KR7009830001,2601.2523099,Y,N,0.000000,0.0,1.0,1.0
70501,HANWHA SOLUTIONS,009830.KS,Other,2023,46291.63,46235.99,2390483416.0,1958054672.0,8708394577.0,7689704560.0,...,15275876648.0,3507.73,KR7009830001,2587.19032097,Y,N,0.000000,0.0,1.0,1.0
70502,HANWHA SOLUTIONS,009830.KS,Other,2024,26950.0,26900.0,3397574334.0,2184380593.0,10882665025.0,11707552341.0,...,19837828963.0,2054.18,KR7009830001,1634.18196089,Y,NaN,0.000000,0.0,1.0,1.0

In [51]:
final_panel.columns

Index(['company', 'ric', 'country', 'Year', 'ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities',
       'tri', 'isin', 'emissions_intensity', 'environmental_investment',
       'internal_carbon_pricing', 'green_bond_proceeds', 'green_bond_issue',
       'green_bond_active', 'gic'],
      dtype='object')

float: ask_price, bid_price, capital_expenditures, cash, current_assets_total, current_liabilities_total, earnings_bef_interest_tax, interest_expense_total, long_term_debt, market_capitalization, market_value, net_cash_flow_operating_actv, net_sales_or_revenues, operating_income, return_on_assets, return_on_equity_total, total_assets, total_capital, total_debt, total_liabilities, tri, emissions_intensity, green_bond_proceeds, green_bond_issue, green_bond_active, gic

need_encode: environmental_investment, internal_carbon_pricing

In [57]:
numeric_attributes = ['ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities', "tri", "emissions_intensity", "green_bond_proceeds", "green_bond_issue", "green_bond_active", "gic"]

encoded_attributes = ["environmental_investment", "internal_carbon_pricing"]

In [55]:
final_panel[numeric_attributes] = final_panel[numeric_attributes].astype(float)

In [56]:
final_panel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69806 entries, 0 to 70538
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   company                       69795 non-null  object
 1   ric                           69806 non-null  object
 2   country                       69806 non-null  object
 3   Year                          69806 non-null  int64
 4   ask_price                     55746 non-null  float64
 5   bid_price                     33977 non-null  float64
 6   capital_expenditures          46916 non-null  float64
 7   cash                          31585 non-null  float64
 8   current_assets_total          19542 non-null  float64
 9   current_liabilities_total     19559 non-null  float64
 10  earnings_bef_interest_tax     22018 non-null  float64
 11  employees                     12560 non-null  float64
 12  interest_expense_total        2602 non-null   float64
 13  long_term_debt                22295 non-null  float64
 14  market_capitalization         20739 non-null  float64
 15  market_value                  20990 non-null  float64
 16  net_cash_flow_operating_actv  22737 non-null  float64
 17  net_sales_or_revenues         22711 non-null  float64
 18  operating_income              22482 non-null  float64
 19  return_on_assets              21825 non-null  float64
 20  return_on_equity_total        21590 non-null  float64
 21  total_assets                  22952 non-null  float64
 22  total_capital                 22803 non-null  float64
 23  total_debt                    22737 non-null  float64
 24  total_liabilities             22948 non-null  float64
 25  tri                           21043 non-null  float64
 26  isin                          31753 non-null  object
 27  emissions_intensity           29854 non-null  float64
 28  environmental_investment      6107 non-null   object
 29  internal_carbon_pricing       8674 non-null   object
 30  green_bond_proceeds           69806 non-null  float64
 31  green_bond_issue              69806 non-null  float64
 32  green_bond_active             69806 non-null  float64
 33  gic                           67598 non-null  float64
dtypes: float64(27), int64(1), object(6)
memory usage: 18.6+ MB

In [58]:
?pd.get_dummies

Signature:
pd.get_dummies(
    data,
    prefix=None,
    prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_',
    dummy_na: 'bool' = False,
    columns=None,
    sparse: 'bool' = False,
    drop_first: 'bool' = False,
    dtype: 'NpDtype | None' = None,
) -> 'DataFrame'
Docstring:
Convert categorical variable into dummy/indicator variables.

Each variable is converted in as many 0/1 variables as there are different
values. Columns in the output are each named after a value; if the input is
a DataFrame, the name of the original variable is prepended to the value.

Parameters
----------
data : array-like, Series, or DataFrame
    Data of which to get dummy indicators.
prefix : str, list of str, or dict of str, default None
    String to append DataFrame column names.
    Pass a list with length equal to the number of columns
    when calling get_dummies on a DataFrame. Alternatively, `prefix`
    can be a dictionary mapping column names to prefixes.
prefix_sep : str, default '_'
    If appending prefix, separator/delimiter to use. Or pass a
    list or dictionary as with `prefix`.
dummy_na : bool, default False
    Add a column to indicate NaNs, if False NaNs are ignored.
columns : list-like, default None
    Column names in the DataFrame to be encoded.
    If `columns` is None then all the columns with
    `object`, `string`, or `category` dtype will be converted.
sparse : bool, default False
    Whether the dummy-encoded columns should be backed by
    a :class:`SparseArray` (True) or a regular NumPy array (False).
drop_first : bool, default False
    Whether to get k-1 dummies out of k categorical levels by removing the
    first level.
dtype : dtype, default bool
    Data type for new columns. Only a single dtype is allowed.

Returns
-------
DataFrame
    Dummy-coded data. If `data` contains other columns than the
    dummy-coded one(s), these will be prepended, unaltered, to the result.

See Also
--------
Series.str.get_dummies : Convert Series of strings to dummy codes.
:func:`~pandas.from_dummies` : Convert dummy codes to categorical ``DataFrame``.

Notes
-----
Reference :ref:`the user guide <reshaping.dummies>` for more examples.

Examples
--------
>>> s = pd.Series(list('abca'))

>>> pd.get_dummies(s)
       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False

>>> s1 = ['a', 'b', np.nan]

>>> pd.get_dummies(s1)
       a      b
0   True  False
1  False   True
2  False  False

>>> pd.get_dummies(s1, dummy_na=True)
       a      b    NaN
0   True  False  False
1  False   True  False
2  False  False   True

>>> df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
...                    'C': [1, 2, 3]})

>>> pd.get_dummies(df, prefix=['col1', 'col2'])
   C  col1_a  col1_b  col2_a  col2_b  col2_c
0  1    True   False   False    True   False
1  2   False    True    True   False   False
2  3    True   False   False   False    True

>>> pd.get_dummies(pd.Series(list('abcaa')))
       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False
4   True  False  False

>>> pd.get_dummies(pd.Series(list('abcaa')), drop_first=True)
       b      c
0  False  False
1   True  False
2  False   True
3  False  False
4  False  False

>>> pd.get_dummies(pd.Series(list('abc')), dtype=float)
     a    b    c
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
File:      ~/miniconda3/lib/python3.13/site-packages/pandas/core/reshape/encoding.py
Type:      function

In [60]:
final_panel = pd.get_dummies(final_panel, columns=encoded_attributes, drop_first=True)

In [61]:
final_panel

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_liabilities,tri,isin,emissions_intensity,green_bond_proceeds,green_bond_issue,green_bond_active,gic,environmental_investment_Y,internal_carbon_pricing_Y
0,3-2 INVESTMENT,C32.HM,Vietnam,2009,NaN,NaN,17626663.0,16475504.0,137674980.0,85237198.0,...,85833310.0,NaN,NaN,NaN,0.0,0.0,0.0,1.0,False,False
1,3-2 INVESTMENT,C32.HM,Vietnam,2010,NaN,NaN,17265301.0,11054438.0,152181932.0,81189068.0,...,81844514.0,NaN,NaN,NaN,0.0,0.0,0.0,1.0,False,False
2,3-2 INVESTMENT,C32.HM,Vietnam,2011,NaN,4090.91,28431946.0,8742910.0,163477837.0,72876736.0,...,101471949.0,100.05,NaN,NaN,0.0,0.0,0.0,1.0,False,False
3,3-2 INVESTMENT,C32.HM,Vietnam,2012,NaN,1022.73,3610136.0,54588281.0,193610957.0,81334774.0,...,109334774.0,40.80,NaN,NaN,0.0,0.0,0.0,1.0,False,False
4,3-2 INVESTMENT,C32.HM,Vietnam,2013,4924.24,4734.84,9709328.0,38118699.0,237449813.0,110128828.0,...,110128828.0,311.03,NaN,NaN,0.0,0.0,0.0,1.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70530,SOLARVEST HOLD,SOLA.KL,Malaysia,2017,NaN,NaN,1592.0,NaN,14578.0,7928.0,...,16249.0,NaN,MYQ0215OO002,5819.559472,0.0,0.0,0.0,1.0,False,False
70532,SOLARVEST HOLD,SOLA.KL,Malaysia,2018,NaN,NaN,2517.0,NaN,21385.0,8385.0,...,16717.0,NaN,MYQ0215OO002,6250.155592,0.0,0.0,0.0,1.0,False,False
70534,SOLARVEST HOLD,SOLA.KL,Malaysia,2019,NaN,NaN,1594.0,NaN,69155.0,44251.0,...,56364.0,NaN,MYQ0215OO002,6901.322579,0.0,0.0,0.0,1.0,False,False
70536,ZETRIX AI BHD,ZETR.KL,Malaysia,2005,NaN,NaN,471.0,987.0,4297.0,1953.0,...,1991.0,NaN,NaN,NaN,0.0,0.0,0.0,1.0,False,False
70538,ZETRIX AI BHD,ZETR.KL,Malaysia,2006,NaN,NaN,221.0,2277.0,7930.0,1852.0,...,1865.0,NaN,NaN,NaN,0.0,0.0,0.0,1.0,False,False