In [1]:
import pandas as pd
import numpy as np

# Merge Panel Data

In [2]:
# 1. Load the data
df1 = pd.read_csv("../data/panel_data.csv")
df2 = pd.read_csv("../data/esg_panel_data.csv")

# 2. DROP THE EXTRA HEADER ROWS
df1 = df1[df1["Year"] != "Year"]
df2 = df2[df2["Year"] != "Year"]

# 3. NOW it is safe to convert them to integers
df1["Year"] = df1["Year"].astype(int)

# (df2's columns were renamed in your cell 12, so make sure to do that first)
df2 = df2.rename(columns={"ticker": "isin"}) 
df2["Year"] = df2["Year"].astype(int)

In [3]:
df1.head()

,company,ticker,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,net_cash_flow_operating_actv,net_sales_or_revenues,operating_income,return_on_assets,return_on_equity_total,total_assets,total_capital,total_debt,total_liabilities,tri
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,139551920.0,557407302.0,120073608.0,23.12,32.37,443321800.0,325687074.0,12154497.0,117634726.0,915.21
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.90,81063081.0,26696986.0,373711509.0,159031144.0,...,159226609.0,520269497.0,104861803.0,19.17,26.44,550731097.0,393873772.0,62680107.0,170454686.0,1292.29
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,116226295.0,559746010.0,108434020.0,14.24,21.23,745486949.0,479984306.0,186715604.0,305496890.0,1662.77
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,164716711.0,722333338.0,110365095.0,12.95,19.85,780505063.0,533398478.0,164144027.0,288917413.0,1605.27
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,77719241.0,802112862.0,74237342.0,9.90,14.14,894945037.0,558134707.0,256450459.0,383110921.0,1421.17

In [4]:
df2.head()

,company,isin,country,Year,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne
0,3-2 INVESTMENT AND,VN000000C325,Vietnam,2015,2546.068815,NaN,NaN,64828.867445,NaN,NaN
1,3-2 INVESTMENT AND,VN000000C325,Vietnam,2016,2819.725335,NaN,NaN,65675.451046,NaN,NaN
2,3-2 INVESTMENT AND,VN000000C325,Vietnam,2017,4362.532697,NaN,NaN,107555.911603,NaN,NaN
3,3-2 INVESTMENT AND,VN000000C325,Vietnam,2018,3615.604879,NaN,NaN,113458.609522,NaN,NaN
4,3-2 INVESTMENT AND,VN000000C325,Vietnam,2019,1825.212869,NaN,NaN,63036.406400,NaN,NaN

In [5]:
# load market data
vn = pd.read_csv("../data/vn-market.csv")
tl = pd.read_csv("../data/tl-market.csv")
ml = pd.read_csv("../data/ml-market.csv")
sing = pd.read_csv("../data/sing-market.csv")
pp = pd.read_csv("../data/pp-market.csv")
other = pd.read_csv("../data/other-market.csv")

In [6]:
market_data = pd.concat([vn, tl, ml, sing, pp], ignore_index=True)
market_data.drop("currency", axis=1, inplace=True)

other = other.reindex(columns=["name", "ric", "org_permid", "isin"])
market_data = pd.concat([market_data, other], ignore_index=True)

In [7]:
tmp1 = pd.merge(df2, market_data, on="isin", how="inner")
tmp1.drop(["name", "org_permid", "company", "country"], axis=1, inplace=True)

In [8]:
df1.columns = ['company', 'ric', 'country', 'Year', 'ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities',
       'tri']

In [9]:
df1["Year"] = df1["Year"].astype(int)
tmp1["Year"] = tmp1["Year"].astype(int)

merge_data = pd.merge(df1, tmp1, on=["ric", "Year"], how="left")
merge_data

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.660,11553.020,14506949.0,21859220.0,346329349.0,119808545.0,...,12154497.0,117634726.0,915.21,VN000000C325,2546.068815,NaN,NaN,64828.867445,NaN,NaN
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.780,15340.900,81063081.0,26696986.0,373711509.0,159031144.0,...,62680107.0,170454686.0,1292.29,VN000000C325,2819.725335,NaN,NaN,65675.451046,NaN,NaN
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.540,18939.380,65713763.0,51147987.0,393966308.0,267676461.0,...,186715604.0,305496890.0,1662.77,VN000000C325,4362.532697,NaN,NaN,107555.911603,NaN,NaN
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.260,17181.810,29890001.0,38972280.0,407136318.0,249280403.0,...,164144027.0,288917413.0,1605.27,VN000000C325,3615.604879,NaN,NaN,113458.609522,NaN,NaN
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.990,14074.990,50628247.0,67504284.0,430996731.0,337421263.0,...,256450459.0,383110921.0,1421.17,VN000000C325,1825.212869,NaN,NaN,63036.406400,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54030,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.780,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.613310,NaN,50.4,22416.960700,NaN,N
54031,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.780,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.613310,NaN,50.4,22416.960700,NaN,N
54032,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.780,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.613310,NaN,50.4,22416.960700,NaN,N
54033,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.780,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.613310,NaN,50.4,22416.960700,NaN,N
54034,ZETRIX AI BHD,ZETR.KL,Malaysia,2025,0.980,0.975,NaN,NaN,NaN,NaN,...,NaN,NaN,12208.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Reset the index so it starts from 0 cleanly
merge_data = merge_data.reset_index(drop=True)

# Drop redundant duplicate rows if the market data caused any
merge_data = merge_data.drop_duplicates(subset=["ric", "Year"])

# Verify the final count 
print("Final Cleaned Panel Rows:", len(merge_data))
merge_data.head()

Final Cleaned Panel Rows: 44422

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,12154497.0,117634726.0,915.21,VN000000C325,2546.068815,NaN,NaN,64828.867445,NaN,NaN
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.90,81063081.0,26696986.0,373711509.0,159031144.0,...,62680107.0,170454686.0,1292.29,VN000000C325,2819.725335,NaN,NaN,65675.451046,NaN,NaN
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,186715604.0,305496890.0,1662.77,VN000000C325,4362.532697,NaN,NaN,107555.911603,NaN,NaN
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,164144027.0,288917413.0,1605.27,VN000000C325,3615.604879,NaN,NaN,113458.609522,NaN,NaN
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,256450459.0,383110921.0,1421.17,VN000000C325,1825.212869,NaN,NaN,63036.406400,NaN,NaN

In [11]:
gb = pd.read_csv("../data/greenbonds.csv")

In [12]:
gb.head()

,Exceeded the limit for the Number of Deals,Package Identifier,Master Deal Type Code,All New Issues Manager Roles Code,Manager's Role Code,Dates: Issue Date,Issuer/Borrower Name Full,Issuer/Borrower PermID,Issue Type,Transaction Status,...,Issuer/Borrower TRBC Business Sector,Issuer/Borrower TRBC Economic Sector,Lead Left Bookrunner,Managers Tier 1 & Tier 2,ECM Flag,Primary Use Of Proceeds,Issuer/Borrower Nation Region,Master Deal Type,All New Issues Manager Roles,Manager's Role
0,154084480389,3480516,D,JB|JB|JB|CM|CM|CM|CM,JB|JB|JB|CM|CM|CM|CM,8/1/2017,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
1,154084486562,3480516,D,JB|JB|JB|CM|CM|CM|CM,JB|JB|JB|CM|CM|CM|CM,8/1/2017,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
2,154084490384,9983331,D,JB|JB|JB,JB|JB|JB,3/12/2015,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Morgan Stanley &...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
3,154084593248,3319100,D,JB|JB|JB,JB|JB|JB,8/9/2016,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
4,154084594902,3319989,ED,JB|JB|JB|JB|JB,JB|JB|JB|JB|JB,8/10/2016,Greenko Investment Co,5.051761e+09,High Yield Corporate,Live,...,Banking & Investment Services,Financials,Deutsche Bank,Deutsche Bank|Investec Bank Ltd|JP Morgan & Co...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,Euro & Foreign Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...

In [13]:
gb["Year"] = pd.to_datetime(gb["Dates: Issue Date"]).dt.year
# Keep only necessary columns
gb = gb[["Issuer/Borrower PermID", "Year", "Proceeds Amount This Market"]].rename(columns={"Issuer/Borrower PermID": "org_permid"})
# Standardize org_permid to string to match market_data
gb["org_permid"] = gb["org_permid"].apply(lambda x: str(int(x)) if pd.notna(x) else np.nan)
gb.head()

   org_permid  Year  Proceeds Amount This Market
0  8589934162  2017                     495.8600
1  8589934162  2017                     746.4825
2  8589934162  2015                     496.4700
3  8589934162  2016                     798.2320
4  5051761072  2016                     500.0000

In [14]:
market_data["org_permid_str"] = pd.to_numeric(market_data["org_permid"], errors='coerce')
market_data["org_permid_str"] = market_data["org_permid_str"].apply(lambda x: str(int(x)) if pd.notna(x) else np.nan)
# Map PermID to RIC
gb_mapped = pd.merge(gb, market_data[["org_permid_str", "ric"]].dropna(), left_on="org_permid", right_on="org_permid_str", how="inner")
gb_mapped.head()

   org_permid  Year  Proceeds Amount This Market org_permid_str       ric
0  4295888106  2017                        500.0     4295888106   DBSM.SI
1  4295888106  2017                        500.0     4295888106    DBSM.F
2  4295888106  2017                        500.0     4295888106  DBSDF.PK
3  4295888106  2017                        500.0     4295888106  DBSDY.PK
4  4295888106  2017                        500.0     4295888106   DEVGy.F

In [15]:
gb_agg = gb_mapped.groupby(["ric", "Year"], as_index=False).agg(
    green_bond_proceeds=("Proceeds Amount This Market", "sum")
)
gb_agg["green_bond_issue"] = 1
gb_agg.head()

         ric  Year  green_bond_proceeds  green_bond_issue
0  009830.KS  2021           152.832755                 1
1   ACDSF.PK  2020           511.413086                 1
2    ALCO.PS  2020           118.319858                 1
3   ALCPD.PS  2020            59.159929                 1
4   ALCPF.PS  2020            59.159929                 1

In [16]:
final_panel = pd.merge(merge_data, gb_agg, on=["ric", "Year"], how="left")
# Fill missing values from the merge with 0 (since no issuance = 0)
final_panel["green_bond_issue"] = final_panel["green_bond_issue"].fillna(0)
final_panel["green_bond_proceeds"] = final_panel["green_bond_proceeds"].fillna(0)
# Create the cumulative Green Bond dummy (1 for the year of issue and all years after)
final_panel = final_panel.sort_values(by=["ric", "Year"])
final_panel["green_bond_active"] = final_panel.groupby("ric")["green_bond_issue"].cumsum().clip(upper=1)
print(final_panel.shape)
final_panel.head()

(44422, 36)

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active
13820,9F INC,0,Malaysia,2020,163.86,1093.28,79.47,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13821,9F INC,0,Malaysia,2021,34.60,263.34,17.24,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13822,9F INC,0,Malaysia,2022,19.50,171.86,9.41,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13823,9F INC,0,Malaysia,2023,2.07,19.26,1.03,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13824,9F INC,0,Malaysia,2024,2.46,23.88,1.28,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [17]:
final_panel = final_panel.sort_index()

In [18]:
final_panel

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,VN000000C325,2546.068815,NaN,NaN,64828.867445,NaN,NaN,0.0,0.0,0.0
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.90,81063081.0,26696986.0,373711509.0,159031144.0,...,VN000000C325,2819.725335,NaN,NaN,65675.451046,NaN,NaN,0.0,0.0,0.0
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,VN000000C325,4362.532697,NaN,NaN,107555.911603,NaN,NaN,0.0,0.0,0.0
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,VN000000C325,3615.604879,NaN,NaN,113458.609522,NaN,NaN,0.0,0.0,0.0
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,VN000000C325,1825.212869,NaN,NaN,63036.406400,NaN,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44417,SIME DARBY,SIPR.KL,Malaysia,2017,NaN,NaN,26298.0,1075260.0,8755777.0,3741719.0,...,MYL5288OO005,346.921939,NaN,47.02,211726.281824,NaN,N,0.0,0.0,0.0
44418,SOLARVEST HOLD,SOLA.KL,Malaysia,2016,NaN,NaN,2394.0,NaN,12149.0,8831.0,...,MYQ0215OO002,3506.650169,NaN,NaN,30743.954777,NaN,NaN,0.0,0.0,0.0
44419,SOLARVEST HOLD,SOLA.KL,Malaysia,2017,NaN,NaN,1592.0,NaN,14578.0,7928.0,...,MYQ0215OO002,5819.559472,NaN,NaN,54128.443528,NaN,NaN,0.0,0.0,0.0
44420,SOLARVEST HOLD,SOLA.KL,Malaysia,2018,NaN,NaN,2517.0,NaN,21385.0,8385.0,...,MYQ0215OO002,6250.155592,NaN,NaN,67680.695763,NaN,NaN,0.0,0.0,0.0
44421,SOLARVEST HOLD,SOLA.KL,Malaysia,2019,NaN,NaN,1594.0,NaN,69155.0,44251.0,...,MYQ0215OO002,6901.322579,NaN,NaN,190110.930472,NaN,NaN,0.0,0.0,0.0

In [19]:
# 1. Load the Series Data
series_df = pd.read_csv("../data/series_data.csv")

# 2. We only need the 'ticker' (which is the ric) and 'gic' columns
# (You already have the 'country' column in your final_panel)
series_df = series_df[['ticker', 'gic']]

# 3. Rename 'ticker' to 'ric' so it perfectly matches the final_panel column name
series_df = series_df.rename(columns={'ticker': 'ric'})

# 4. Merge the GIC codes back into the master panel!
final_panel = pd.merge(final_panel, series_df, on="ric", how="left")

# Print to check the output
print(final_panel.shape)

# (Optional: If you appended multiple times, the series data might have duplicates too)
# Run this just to be perfectly safe, then save:
final_panel = final_panel.drop_duplicates(subset=["ric", "Year"])

(44868, 37)

In [20]:
# final_panel.to_csv("../processed_data/final_data.csv")

# Data Processing

In [21]:
final_panel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44422 entries, 0 to 44866
Data columns (total 37 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   company                           44412 non-null  object
 1   ric                               44422 non-null  object
 2   country                           44422 non-null  object
 3   Year                              44422 non-null  int64
 4   ask_price                         35660 non-null  float64
 5   bid_price                         21100 non-null  float64
 6   capital_expenditures              28906 non-null  float64
 7   cash                              20940 non-null  float64
 8   current_assets_total              12129 non-null  float64
 9   current_liabilities_total         12143 non-null  float64
 10  earnings_bef_interest_tax         13518 non-null  float64
 11  employees                         6643 non-null   float64
 12  interest_expense_total            1540 non-null   float64
 13  long_term_debt                    13670 non-null  float64
 14  market_capitalization             13460 non-null  float64
 15  market_value                      13850 non-null  float64
 16  net_cash_flow_operating_actv      14174 non-null  float64
 17  net_sales_or_revenues             14043 non-null  float64
 18  operating_income                  13949 non-null  float64
 19  return_on_assets                  13794 non-null  float64
 20  return_on_equity_total            13729 non-null  float64
 21  total_assets                      14279 non-null  float64
 22  total_capital                     14044 non-null  float64
 23  total_debt                        14074 non-null  float64
 24  total_liabilities                 14273 non-null  float64
 25  tri                               13995 non-null  float64
 26  isin                              30307 non-null  object
 27  emissions_intensity               29854 non-null  float64
 28  environmental_investment          4859 non-null   object
 29  esg_score                         6185 non-null   float64
 30  estimated_total_carbon_footprint  29854 non-null  float64
 31  internal_carbon_pricing           728 non-null    object
 32  internal_carbon_price_per_tonne   6662 non-null   object
 33  green_bond_proceeds               44422 non-null  float64
 34  green_bond_issue                  44422 non-null  float64
 35  green_bond_active                 44422 non-null  float64
 36  gic                               42528 non-null  float64
dtypes: float64(29), int64(1), object(7)
memory usage: 12.9+ MB

In [22]:
tmp1 = final_panel[final_panel["environmental_investment"].notna()]
tmp1

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active,gic
208,BAMBOO CAPITAL,BCG.HM,Vietnam,2020,3809.53,3803.25,2.128566e+09,9.033865e+08,1.133811e+10,1.060946e+10,...,511.815841,N,30.73,4.086246e+04,N,NaN,0.000000,0.0,0.0,1.0
209,BAMBOO CAPITAL,BCG.HM,Vietnam,2021,9852.27,9783.86,2.153025e+09,1.044040e+09,1.623869e+10,1.019714e+10,...,727.221845,N,29.97,8.211414e+04,N,NaN,0.000000,0.0,0.0,1.0
210,BAMBOO CAPITAL,BCG.HM,Vietnam,2022,20519.48,20389.61,3.452957e+09,6.294964e+08,1.776171e+10,1.138017e+10,...,522.089675,N,33.84,1.011759e+05,N,NaN,0.000000,0.0,0.0,1.0
211,BAMBOO CAPITAL,BCG.HM,Vietnam,2023,5836.36,5827.27,1.324265e+08,7.568595e+08,1.947860e+10,1.209023e+10,...,497.577619,N,34.54,8.380882e+04,N,NaN,0.000000,0.0,0.0,1.0
212,BAMBOO CAPITAL,BCG.HM,Vietnam,2024,7645.45,7636.36,2.872646e+08,7.222267e+08,2.219228e+10,1.322842e+10,...,572.123596,N,31.34,9.988903e+04,NaN,NaN,0.000000,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44830,HANWHA SOLUTIONS,009830.KS,Other,2020,20480.87,20426.54,8.837862e+08,1.199837e+09,4.958365e+09,5.251126e+09,...,5643.677033,Y,73.05,4.406877e+07,NaN,N,0.000000,0.0,0.0,1.0
44831,HANWHA SOLUTIONS,009830.KS,Other,2021,52523.20,52467.56,8.126709e+08,1.651530e+09,6.159820e+09,5.789061e+09,...,4885.615603,Y,64.46,4.582102e+07,NaN,N,152.832755,1.0,1.0,1.0
44832,HANWHA SOLUTIONS,009830.KS,Other,2022,37111.20,37055.56,9.029231e+08,2.616168e+09,8.642576e+09,6.810183e+09,...,2601.252310,Y,61.56,2.653609e+07,NaN,N,0.000000,0.0,1.0,1.0
44833,HANWHA SOLUTIONS,009830.KS,Other,2023,46291.63,46235.99,2.390483e+09,1.958055e+09,8.708395e+09,7.689705e+09,...,2587.190321,Y,68.58,2.593030e+07,NaN,N,0.000000,0.0,1.0,1.0
44834,HANWHA SOLUTIONS,009830.KS,Other,2024,26950.00,26900.00,3.397574e+09,2.184381e+09,1.088267e+10,1.170755e+10,...,1634.181961,Y,73.43,1.486943e+07,NaN,NaN,0.000000,0.0,1.0,1.0

In [23]:
final_panel.columns

Index(['company', 'ric', 'country', 'Year', 'ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities',
       'tri', 'isin', 'emissions_intensity', 'environmental_investment',
       'esg_score', 'estimated_total_carbon_footprint',
       'internal_carbon_pricing', 'internal_carbon_price_per_tonne',
       'green_bond_proceeds', 'green_bond_issue', 'green_bond_active', 'gic'],
      dtype='object')

float: ask_price, bid_price, capital_expenditures, cash, current_assets_total, current_liabilities_total, earnings_bef_interest_tax, interest_expense_total, long_term_debt, market_capitalization, market_value, net_cash_flow_operating_actv, net_sales_or_revenues, operating_income, return_on_assets, return_on_equity_total, total_assets, total_capital, total_debt, total_liabilities, tri, emissions_intensity, green_bond_proceeds, green_bond_issue, green_bond_active, gic

need_encode: environmental_investment, internal_carbon_pricing

In [24]:
numeric_attributes = ['ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities', "tri", "emissions_intensity", "green_bond_proceeds", "green_bond_issue", "green_bond_active", "gic"]

encoded_attributes = ["environmental_investment"]

In [25]:
final_panel[numeric_attributes] = final_panel[numeric_attributes].astype(float)
final_panel["internal_carbon_pricing"] = pd.to_numeric(final_panel["internal_carbon_pricing"], errors='coerce')
final_panel["internal_carbon_price_per_tonne"] = pd.to_numeric(final_panel["internal_carbon_pricing"], errors='coerce')

In [26]:
final_panel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44422 entries, 0 to 44866
Data columns (total 37 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   company                           44412 non-null  object
 1   ric                               44422 non-null  object
 2   country                           44422 non-null  object
 3   Year                              44422 non-null  int64
 4   ask_price                         35660 non-null  float64
 5   bid_price                         21100 non-null  float64
 6   capital_expenditures              28906 non-null  float64
 7   cash                              20940 non-null  float64
 8   current_assets_total              12129 non-null  float64
 9   current_liabilities_total         12143 non-null  float64
 10  earnings_bef_interest_tax         13518 non-null  float64
 11  employees                         6643 non-null   float64
 12  interest_expense_total            1540 non-null   float64
 13  long_term_debt                    13670 non-null  float64
 14  market_capitalization             13460 non-null  float64
 15  market_value                      13850 non-null  float64
 16  net_cash_flow_operating_actv      14174 non-null  float64
 17  net_sales_or_revenues             14043 non-null  float64
 18  operating_income                  13949 non-null  float64
 19  return_on_assets                  13794 non-null  float64
 20  return_on_equity_total            13729 non-null  float64
 21  total_assets                      14279 non-null  float64
 22  total_capital                     14044 non-null  float64
 23  total_debt                        14074 non-null  float64
 24  total_liabilities                 14273 non-null  float64
 25  tri                               13995 non-null  float64
 26  isin                              30307 non-null  object
 27  emissions_intensity               29854 non-null  float64
 28  environmental_investment          4859 non-null   object
 29  esg_score                         6185 non-null   float64
 30  estimated_total_carbon_footprint  29854 non-null  float64
 31  internal_carbon_pricing           175 non-null    float64
 32  internal_carbon_price_per_tonne   175 non-null    float64
 33  green_bond_proceeds               44422 non-null  float64
 34  green_bond_issue                  44422 non-null  float64
 35  green_bond_active                 44422 non-null  float64
 36  gic                               42528 non-null  float64
dtypes: float64(31), int64(1), object(5)
memory usage: 12.9+ MB

In [27]:
?pd.get_dummies

Signature:
pd.get_dummies(
    data,
    prefix=None,
    prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_',
    dummy_na: 'bool' = False,
    columns=None,
    sparse: 'bool' = False,
    drop_first: 'bool' = False,
    dtype: 'NpDtype | None' = None,
) -> 'DataFrame'
Docstring:
Convert categorical variable into dummy/indicator variables.

Each variable is converted in as many 0/1 variables as there are different
values. Columns in the output are each named after a value; if the input is
a DataFrame, the name of the original variable is prepended to the value.

Parameters
----------
data : array-like, Series, or DataFrame
    Data of which to get dummy indicators.
prefix : str, list of str, or dict of str, default None
    String to append DataFrame column names.
    Pass a list with length equal to the number of columns
    when calling get_dummies on a DataFrame. Alternatively, `prefix`
    can be a dictionary mapping column names to prefixes.
prefix_sep : str, default '_'
    If appending prefix, separator/delimiter to use. Or pass a
    list or dictionary as with `prefix`.
dummy_na : bool, default False
    Add a column to indicate NaNs, if False NaNs are ignored.
columns : list-like, default None
    Column names in the DataFrame to be encoded.
    If `columns` is None then all the columns with
    `object`, `string`, or `category` dtype will be converted.
sparse : bool, default False
    Whether the dummy-encoded columns should be backed by
    a :class:`SparseArray` (True) or a regular NumPy array (False).
drop_first : bool, default False
    Whether to get k-1 dummies out of k categorical levels by removing the
    first level.
dtype : dtype, default bool
    Data type for new columns. Only a single dtype is allowed.

Returns
-------
DataFrame
    Dummy-coded data. If `data` contains other columns than the
    dummy-coded one(s), these will be prepended, unaltered, to the result.

See Also
--------
Series.str.get_dummies : Convert Series of strings to dummy codes.
:func:`~pandas.from_dummies` : Convert dummy codes to categorical ``DataFrame``.

Notes
-----
Reference :ref:`the user guide <reshaping.dummies>` for more examples.

Examples
--------
>>> s = pd.Series(list('abca'))

>>> pd.get_dummies(s)
       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False

>>> s1 = ['a', 'b', np.nan]

>>> pd.get_dummies(s1)
       a      b
0   True  False
1  False   True
2  False  False

>>> pd.get_dummies(s1, dummy_na=True)
       a      b    NaN
0   True  False  False
1  False   True  False
2  False  False   True

>>> df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
...                    'C': [1, 2, 3]})

>>> pd.get_dummies(df, prefix=['col1', 'col2'])
   C  col1_a  col1_b  col2_a  col2_b  col2_c
0  1    True   False   False    True   False
1  2   False    True    True   False   False
2  3    True   False   False   False    True

>>> pd.get_dummies(pd.Series(list('abcaa')))
       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False
4   True  False  False

>>> pd.get_dummies(pd.Series(list('abcaa')), drop_first=True)
       b      c
0  False  False
1   True  False
2  False   True
3  False  False
4  False  False

>>> pd.get_dummies(pd.Series(list('abc')), dtype=float)
     a    b    c
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
File:      ~/miniconda3/lib/python3.13/site-packages/pandas/core/reshape/encoding.py
Type:      function

In [28]:
final_panel = pd.get_dummies(final_panel, columns=encoded_attributes, drop_first=True)

In [29]:
final_panel.columns = final_panel.columns.str.strip()

final_panel = final_panel.rename(columns={
    "environmental_investment_Y": "environmental_investment"
    })
final_panel

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,emissions_intensity,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active,gic,environmental_investment
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,2546.068815,NaN,64828.867445,NaN,NaN,0.0,0.0,0.0,1.0,False
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.90,81063081.0,26696986.0,373711509.0,159031144.0,...,2819.725335,NaN,65675.451046,NaN,NaN,0.0,0.0,0.0,1.0,False
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,4362.532697,NaN,107555.911603,NaN,NaN,0.0,0.0,0.0,1.0,False
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,3615.604879,NaN,113458.609522,NaN,NaN,0.0,0.0,0.0,1.0,False
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,1825.212869,NaN,63036.406400,NaN,NaN,0.0,0.0,0.0,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44858,SIME DARBY,SIPR.KL,Malaysia,2017,NaN,NaN,26298.0,1075260.0,8755777.0,3741719.0,...,346.921939,47.02,211726.281824,NaN,NaN,0.0,0.0,0.0,1.0,False
44860,SOLARVEST HOLD,SOLA.KL,Malaysia,2016,NaN,NaN,2394.0,NaN,12149.0,8831.0,...,3506.650169,NaN,30743.954777,NaN,NaN,0.0,0.0,0.0,1.0,False
44862,SOLARVEST HOLD,SOLA.KL,Malaysia,2017,NaN,NaN,1592.0,NaN,14578.0,7928.0,...,5819.559472,NaN,54128.443528,NaN,NaN,0.0,0.0,0.0,1.0,False
44864,SOLARVEST HOLD,SOLA.KL,Malaysia,2018,NaN,NaN,2517.0,NaN,21385.0,8385.0,...,6250.155592,NaN,67680.695763,NaN,NaN,0.0,0.0,0.0,1.0,False
44866,SOLARVEST HOLD,SOLA.KL,Malaysia,2019,NaN,NaN,1594.0,NaN,69155.0,44251.0,...,6901.322579,NaN,190110.930472,NaN,NaN,0.0,0.0,0.0,1.0,False

## Econometric Data Cleaning
Applying data cleaning techniques based on the Econometric Data Cleaning skill and the Evaluation Report fixes.

**Pipeline order (corrected):**
1. Load data & filter non-ASEAN firms / Year 2025
2. Handle missing values via forward fill (grouped by `ric`), then drop firms with <3 years of `total_assets`
3. Data type conversion (ensure numeric columns are numeric early)
4. Currency conversion to USD using `yfinance` (excludes ratios: ROA, ROE, emissions_intensity)
5. Winsorization at 1st/99th percentiles (AFTER currency conversion, in common currency)
6. Normalize ROA/ROE from percentage to decimal (divide by 100)
7. Log transform `total_assets`
8. Encode `environmental_investment` as binary (Y=1, N=0, NaN=NaN)
9. Data type verification & duplicate resolution

In [30]:
import pandas as pd
import yfinance as yf
from scipy.stats.mstats import winsorize
import numpy as np

# Load data

# ============================================================
# 0. Filter non-ASEAN firms and Year 2025
# (Issue #7, #8, #18: "Other" country includes Korean firms
#  in non-ASEAN exchanges; Year 2025 has almost all NaN financials)
# ============================================================
final_panel = final_panel[final_panel['country'] != 'Other'].copy()
print(f"Shape after removing non-ASEAN ('Other') firms: {final_panel.shape}")

final_panel['Year'] = pd.to_numeric(final_panel['Year'], errors='coerce')
final_panel = final_panel[final_panel['Year'] != 2025].copy()
print(f"Shape after removing Year 2025: {final_panel.shape}")

# ============================================================
# 1. Handle Missing Values
# Forward fill slowly-changing variables, grouped by 'ric'.
# NOTE: environmental_investment is NOT forward-filled (Issue #19)
#   — it is a Y/N indicator, ffill would artificially inflate 'Y'.
# ============================================================
vars_to_ffill = [
    'total_assets', 'return_on_equity_total', 'return_on_assets',
    'emissions_intensity', 'esg_score', 'estimated_total_carbon_footprint',
    'internal_carbon_pricing', 'internal_carbon_price_per_tonne'
]
for col in vars_to_ffill:
    if col in final_panel.columns:
        final_panel[col] = final_panel.groupby('ric')[col].transform(lambda x: x.ffill())

# Reduce data loss (Issue #15): keep firms with at least 3 years of
# non-null total_assets, then drop individual rows still missing it.
ta_notna_count = final_panel.groupby('ric')['total_assets'].transform(
    lambda x: x.notna().sum()
)
final_panel = final_panel[ta_notna_count >= 3].copy()
final_panel = final_panel.dropna(subset=['total_assets']).copy()
print(f"Shape after ffill and filtering firms with <3 years of total_assets: {final_panel.shape}")

# ============================================================
# 2. Early Data Type Conversion (Issue #9)
# Convert numeric columns from object to float BEFORE any math.
# ============================================================
numeric_cols = [
    'ask_price', 'bid_price', 'capital_expenditures', 'cash',
    'current_assets_total', 'current_liabilities_total',
    'earnings_bef_interest_tax', 'interest_expense_total',
    'long_term_debt', 'market_capitalization', 'market_value',
    'net_cash_flow_operating_actv', 'net_sales_or_revenues',
    'operating_income', 'total_assets', 'total_capital',
    'total_debt', 'total_liabilities',
    'return_on_assets', 'return_on_equity_total',
    'emissions_intensity', 'esg_score', 'estimated_total_carbon_footprint',
    'internal_carbon_pricing', 'internal_carbon_price_per_tonne',
    'employees', 'tri'
]
for col in numeric_cols:
    if col in final_panel.columns:
        final_panel[col] = pd.to_numeric(final_panel[col], errors='coerce')

# ============================================================
# 3. Currency Conversion to USD (BEFORE winsorization)
# (Issue #16: winsorize AFTER conversion to common currency)
# (Issue #17: EXCLUDE ratios from FX conversion — ROA, ROE,
#  emissions_intensity are percentages/ratios, not currency values)
# ============================================================
currency_map = {
    'Vietnam': 'VND=X',
    'Thailand': 'THB=X',
    'Malaysia': 'MYR=X',
    'Singapore': 'SGD=X',
    'Indonesia': 'IDR=X',
    'Philippines': 'PHP=X'
}

fx_rates = {}
for country, ticker in currency_map.items():
    tk = yf.Ticker(ticker)
    hist = tk.history(period="max")
    if not hist.empty:
        hist['Year'] = hist.index.year
        yearly_avg = hist.groupby('Year')['Close'].mean()
        fx_rates[country] = yearly_avg.to_dict()

# Only MONETARY columns — explicitly exclude ratios/percentages
financial_cols_for_fx = [
    'ask_price', 'bid_price', 'capital_expenditures', 'cash',
    'current_assets_total', 'current_liabilities_total',
    'earnings_bef_interest_tax', 'interest_expense_total',
    'long_term_debt', 'market_capitalization', 'market_value',
    'net_cash_flow_operating_actv', 'net_sales_or_revenues',
    'operating_income', 'total_assets', 'total_capital',
    'total_debt', 'total_liabilities'
]
# NOTE: return_on_assets, return_on_equity_total, emissions_intensity,
#        esg_score, internal_carbon_pricing are NOT converted.

def get_fx_rate(row):
    country = row['country']
    year = row['Year']
    if country in fx_rates and year in fx_rates[country]:
        return fx_rates[country][year]
    return 1.0  # fallback (should not happen after filtering 'Other')

final_panel['fx_rate'] = final_panel.apply(get_fx_rate, axis=1)

for col in financial_cols_for_fx:
    if col in final_panel.columns:
        final_panel[col] = final_panel[col] / final_panel['fx_rate']

final_panel.drop(columns=['fx_rate'], inplace=True)
print("Currency conversion to USD complete (ratios excluded).")

# ============================================================
# 4. Winsorization (AFTER currency conversion — Issue #16)
# Now all monetary values are in USD, so percentile trimming
# is statistically meaningful across countries.
# Also winsorize emissions_intensity (Issue #25).
# ============================================================
winsorize_vars = [
    'ask_price', 'bid_price', 'total_assets', 'net_sales_or_revenues',
    'cash', 'capital_expenditures', 'long_term_debt', 'total_debt',
    'market_capitalization', 'market_value', 'operating_income',
    'earnings_bef_interest_tax', 'current_assets_total',
    'current_liabilities_total', 'total_liabilities', 'total_capital',
    'emissions_intensity', 'estimated_total_carbon_footprint'
]
# Also winsorize ratios separately
ratio_winsorize_vars = ['return_on_assets', 'return_on_equity_total']

for col in winsorize_vars + ratio_winsorize_vars:
    if col in final_panel.columns:
        mask = final_panel[col].notna()
        if mask.sum() > 0:
            final_panel.loc[mask, col] = winsorize(final_panel.loc[mask, col], limits=[0.01, 0.01])

print("Winsorization complete (post-FX conversion).")

# ============================================================
# 5. Normalize ROA and ROE from percentage to decimal
# (User feedback: these are stored as percentages, divide by 100)
# ============================================================
for col in ['return_on_assets', 'return_on_equity_total']:
    if col in final_panel.columns:
        final_panel[col] = final_panel[col] / 100.0

# ============================================================
# 6. Data Transformation & Normalization
# Log transform total_assets (standard in corporate finance)
# ============================================================
final_panel['ln_total_assets'] = np.log(final_panel['total_assets'].replace(0, np.nan))

# ============================================================
# 7. Encode environmental_investment properly (Issue #11)
# Map Y→1, N→0, keep NaN as NaN (not falsely coded as 0)
# ============================================================
if 'environmental_investment' in final_panel.columns:
    final_panel['environmental_investment'] = final_panel['environmental_investment'].map({'Y': 1, 'N': 0})
    print(f"environmental_investment encoded: "
          f"1={int((final_panel['environmental_investment']==1).sum())}, "
          f"0={int((final_panel['environmental_investment']==0).sum())}, "
          f"NaN={int(final_panel['environmental_investment'].isna().sum())}")

# ============================================================
# 8. Data Type Verification
# ============================================================
final_panel['isin'] = final_panel['isin'].astype(str)
final_panel['ric'] = final_panel['ric'].astype(str)
final_panel['country'] = final_panel['country'].astype(str)
final_panel['company'] = final_panel['company'].astype(str)
final_panel['Year'] = final_panel['Year'].astype(int)

# Treat GIC as categorical, not numeric (Issue #14)
if 'gic' in final_panel.columns:
    final_panel['gic'] = final_panel['gic'].astype(str).astype('category')

# ============================================================
# 9. Duplicates Resolution
# ============================================================
final_panel = final_panel.sort_values(by=final_panel.columns.tolist()).drop_duplicates(subset=['ric', 'Year'], keep='last')

print(f"\nData Cleaning Complete. Final Shape: {final_panel.shape}")
print(f"Countries: {final_panel['country'].unique()}")
print(f"Year range: {final_panel['Year'].min()} - {final_panel['Year'].max()}")
print(f"Unique firms (RICs): {final_panel['ric'].nunique()}")

# Save the cleaned dataset for the next step
final_panel.to_csv('../processed_data/cleaned_panel_data.csv', index=False)

Shape after removing non-ASEAN ('Other') firms: (44400, 37)
Shape after removing Year 2025: (39827, 37)
Shape after ffill and filtering firms with <3 years of total_assets: (13688, 37)
Currency conversion to USD complete (ratios excluded).
Winsorization complete (post-FX conversion).
environmental_investment encoded: 1=0, 0=0, NaN=13688

Data Cleaning Complete. Final Shape: (13688, 38)
Countries: ['Thailand' 'Vietnam' 'Indonesia' 'Malaysia']
Year range: 2015 - 2024
Unique firms (RICs): 1463

## Variable Engineering
Calculations of intermediate financial and environmental variables for regression models.

Tasks include:
- Calculating Control Variables: Firm Size, Leverage, Profitability, Capital Intensity.
- Green Bond & ESG Processing: Log-transforming severely skewed `emissions_intensity`.
- Lagged Variables: Computing 1-year lagged values for independent variables grouped by firm.
- Creating Country and Year dummy variables for fixed effects.

**Evaluation Report fixes applied:**
- `Firm_Size` is a proper `.copy()` (Issue #26)
- `Leverage` and `Capital_Intensity` clipped to [0, 1] (Issues #24, #27)
- `gic` treated as categorical (Issue #14)
- `pd.get_dummies` no longer applied on `environmental_investment` (already binary from cleaning)

In [31]:
import pandas as pd
import numpy as np

# Load cleaned data (environmental_investment already encoded as 1/0/NaN)
# final_panel = pd.read_csv('../processed_data/cleaned_panel_data.csv')
# print(f"Loaded cleaned data: {final_panel.shape}")

# ============================================================
# 1. Calculate Control Variables
# ============================================================
# Firm_Size: proper copy, not a reference (Issue #26)
final_panel['Firm_Size'] = final_panel['ln_total_assets'].copy()

# Leverage: clip to [0, 1] — values > 1 indicate total_debt > total_assets,
# which is possible for distressed firms but likely data error at extreme values (Issue #24)
final_panel['Leverage'] = (final_panel['total_debt'] / final_panel['total_assets']).clip(lower=0, upper=1)

# Capital_Intensity: cap at [0, 1] — CapEx/Assets > 1 is almost certainly
# a data error (Issue #27)
final_panel['Capital_Intensity'] = (final_panel['capital_expenditures'].abs() / final_panel['total_assets']).clip(lower=0, upper=1)

print("Control variables calculated:")
print(final_panel[['Firm_Size', 'Leverage', 'Capital_Intensity']].describe())

# ============================================================
# 2. Green Bond & ESG Processing
# ============================================================
# Log-transform emissions_intensity (extreme skewness = 33.5, Issue #25)
# Already winsorized in cleaning step; log calms remaining skewness
if 'emissions_intensity' in final_panel.columns:
    final_panel['ln_emissions_intensity'] = np.log(final_panel['emissions_intensity'].replace(0, np.nan))

# Log-transform estimated_total_carbon_footprint if present
if 'estimated_total_carbon_footprint' in final_panel.columns:
    final_panel['ln_carbon_footprint'] = np.log(
        final_panel['estimated_total_carbon_footprint'].replace(0, np.nan)
    )

# ============================================================
# 3. Lagged Variables (1-year lag grouped by firm)
# ============================================================
independent_vars = [
    'Firm_Size', 'Leverage', 'Capital_Intensity',
    'return_on_assets', 'return_on_equity_total',
    'ln_emissions_intensity', 'environmental_investment',
    'esg_score'
]

for col in independent_vars:
    if col in final_panel.columns:
        final_panel[f'L1_{col}'] = final_panel.groupby('ric')[col].shift(1)

print(f"\nLagged variables created for: {[c for c in independent_vars if c in final_panel.columns]}")

# ============================================================
# 4. GIC as categorical (Issue #14)
# ============================================================
if 'gic' in final_panel.columns:
    final_panel['gic'] = final_panel['gic'].astype(str).astype('category')
    print(f"GIC categories: {final_panel['gic'].nunique()} unique industry codes")

# ============================================================
# 5. Country and Year Dummies (Fixed Effects Preparation)
# Note: 'Other' country already filtered in cleaning. Year 2025 removed.
# environmental_investment is already 1/0/NaN — no get_dummies needed for it.
# ============================================================
final_panel = pd.get_dummies(final_panel, columns=['country', 'Year'], drop_first=True, dtype=int)

# ============================================================
# Final Dataset Cleanup and Saving
# ============================================================
final_panel.to_csv('../processed_data/final_engineered_panel_data.csv', index=False)
print(f"\nVariable Engineering Complete. Final shape: {final_panel.shape}")
print("\nSummary of key engineered variables:")
summary_cols = ['Firm_Size', 'Leverage', 'Capital_Intensity', 'ln_emissions_intensity']
summary_cols = [c for c in summary_cols if c in final_panel.columns]
print(final_panel[summary_cols].describe())

Control variables calculated:
          Firm_Size      Leverage  Capital_Intensity
count  13688.000000  13450.000000       12969.000000
mean      10.726509      0.236774           0.039592
std        2.746210      0.205643           0.064806
min        2.168593      0.000000           0.000000
25%        9.805304      0.041450           0.003930
50%       11.004245      0.204886           0.017995
75%       12.283024      0.387229           0.048775
max       16.789092      1.000000           1.000000

Lagged variables created for: ['Firm_Size', 'Leverage', 'Capital_Intensity', 'return_on_assets', 'return_on_equity_total', 'ln_emissions_intensity', 'environmental_investment', 'esg_score']
GIC categories: 6 unique industry codes

Variable Engineering Complete. Final shape: (13688, 61)

Summary of key engineered variables:
          Firm_Size      Leverage  Capital_Intensity  ln_emissions_intensity
count  13688.000000  13450.000000       12969.000000            13308.000000
mean      10.726509      0.236774           0.039592                6.437695
std        2.746210      0.205643           0.064806                1.175411
min        2.168593      0.000000           0.000000                4.269326
25%        9.805304      0.041450           0.003930                5.605799
50%       11.004245      0.204886           0.017995                6.279637
75%       12.283024      0.387229           0.048775                7.160239
max       16.789092      1.000000           1.000000                9.618776

## Panel Data Validation
Structurally validating the firm-year panel dataset.

Tasks include:
- Setting the multi-index (`['ric', 'Year']`).
- Checking if the panel is severely unbalanced.
- Generating descriptive statistics (Table 1) including engineered variables.
- Producing a correlation matrix.
- Before/after diagnostics for key variables.

In [32]:
final_panel

,company,ric,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,earnings_bef_interest_tax,employees,...,country_Vietnam,Year_2016,Year_2017,Year_2018,Year_2019,Year_2020,Year_2021,Year_2022,Year_2023,Year_2024
4365,2S METAL,2S.BK,0.068098,0.066929,851.314989,1804.601894,21421.116952,12176.569181,1821.378013,NaN,...,0,0,0,0,0,0,0,0,0,0
4366,2S METAL,2S.BK,0.039466,0.039183,2255.608504,2445.246343,34872.578575,19026.078459,12494.859293,NaN,...,0,1,0,0,0,0,0,0,0,0
4367,2S METAL,2S.BK,0.141764,0.140880,1642.132440,2140.663772,40800.199142,18141.530118,10895.746354,NaN,...,0,0,1,0,0,0,0,0,0,0
4368,2S METAL,2S.BK,0.107713,0.107094,2659.438610,2006.534221,39228.089136,15796.051973,4492.238483,NaN,...,0,0,0,1,0,0,0,0,0,0
4369,2S METAL,2S.BK,0.062827,0.062183,1567.367837,4248.102644,38261.759988,11288.966283,5473.882432,NaN,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14042,ZIGA INNOVATION PCL,ZIGAm.BK,0.023665,0.023026,4030.698880,6304.752816,21922.291849,13030.206249,5197.627412,NaN,...,0,0,0,0,0,1,0,0,0,0
14043,ZIGA INNOVATION PCL,ZIGAm.BK,0.151069,0.150131,2983.812792,46.258966,30662.594691,18889.234265,8125.626690,94.0,...,0,0,0,0,0,0,1,0,0,0
14044,ZIGA INNOVATION PCL,ZIGAm.BK,0.251193,0.249766,2715.079679,15.185744,14944.941250,7743.815889,-10475.166007,NaN,...,0,0,0,0,0,0,0,1,0,0
14045,ZIGA INNOVATION PCL,ZIGAm.BK,0.097771,0.097195,228.294144,5301.692254,14050.513939,12175.102993,2402.624052,NaN,...,0,0,0,0,0,0,0,0,1,0
14046,ZIGA INNOVATION PCL,ZIGAm.BK,0.083379,0.082811,69.085131,1389.927044,11296.127948,7749.332480,1262.505248,NaN,...,0,0,0,0,0,0,0,0,0,1

In [35]:
import pandas as pd
import numpy as np

# ============================================================
# 1. Set Multi-Index
# ============================================================
df = pd.read_csv("../processed_data/cleaned_panel_data.csv")
panel = df.set_index(['ric', 'Year']).sort_index()

# ============================================================
# 2. Panel Structure Check
# ============================================================
obs_per_firm = panel.groupby(level='ric').size()
print("=" * 60)
print("PANEL STRUCTURE CHECK")
print("=" * 60)
print(f"Total Firms (RICs): {panel.index.get_level_values('ric').nunique()}")
print(f"Total Firm-Year Observations: {len(panel)}")
print(f"Average Years per Firm: {obs_per_firm.mean():.2f}")
print(f"Temporal Range: {panel.index.get_level_values('Year').min()} to {panel.index.get_level_values('Year').max()}")
print(f"Min Years for a single firm: {obs_per_firm.min()}")
print(f"Max Years for a single firm: {obs_per_firm.max()}")

# Verify no non-ASEAN countries
if 'country' in final_panel.columns:
    print(f"\nCountries in dataset: {sorted(final_panel['country'].unique())}")

# ============================================================
# 3. Descriptive Statistics (Table 1)
# ============================================================

primary_vars = panel.select_dtypes(include=['number']).columns.tolist()


# Ensure primary variables are numeric
for col in primary_vars:
    final_panel[col] = pd.to_numeric(final_panel[col], errors='coerce')

desc_stats = final_panel[primary_vars].describe().T
desc_stats['skewness'] = final_panel[primary_vars].skew()
desc_stats['kurtosis'] = final_panel[primary_vars].kurt()
desc_stats['missing_pct'] = (final_panel[primary_vars].isna().sum() / len(final_panel) * 100).round(1)

print("\n" + "=" * 60)
print("DESCRIPTIVE STATISTICS")
print("=" * 60)
display(desc_stats)

# ============================================================
# 4. Sanity Checks on Key Variables
# ============================================================
print("\n" + "=" * 60)
print("SANITY CHECKS")
print("=" * 60)

# ROA/ROE should be in decimal range (after /100)
if 'return_on_assets' in final_panel.columns:
    roa = final_panel['return_on_assets'].dropna()
    print(f"ROA range: [{roa.min():.4f}, {roa.max():.4f}] (should be decimal, e.g. 0.05 = 5%)")

if 'return_on_equity_total' in final_panel.columns:
    roe = final_panel['return_on_equity_total'].dropna()
    print(f"ROE range: [{roe.min():.4f}, {roe.max():.4f}]")

# Check environmental_investment encoding
if 'environmental_investment' in final_panel.columns:
    print(f"\nenvironmental_investment value counts (NaN should exist, not be 0):")
    print(final_panel['environmental_investment'].value_counts(dropna=False))

# Check for any remaining non-ASEAN
if 'country' in final_panel.columns:
    non_asean = final_panel[final_panel['country'] == 'Other']
    print(f"\nNon-ASEAN ('Other') rows remaining: {len(non_asean)} (should be 0)")

# ============================================================
# 5. Correlation Matrix
# ============================================================
corr_vars = [c for c in primary_vars if c in final_panel.columns and final_panel[c].notna().sum() > 100]
corr_matrix = final_panel[corr_vars].corr(method='pearson')
print("\n" + "=" * 60)
print("PEARSON CORRELATION MATRIX")
print("=" * 60)
display(corr_matrix)

# Flag high multicollinearity
print("\nHigh correlations (|r| > 0.8):")
for i in range(len(corr_matrix)):
    for j in range(i+1, len(corr_matrix)):
        r = corr_matrix.iloc[i, j]
        if abs(r) > 0.8:
            print(f"  {corr_matrix.index[i]} ↔ {corr_matrix.columns[j]}: {r:.3f}")

============================================================
PANEL STRUCTURE CHECK
============================================================
Total Firms (RICs): 1463
Total Firm-Year Observations: 13688
Average Years per Firm: 9.36
Temporal Range: 2015 to 2024
Min Years for a single firm: 3
Max Years for a single firm: 10

============================================================
DESCRIPTIVE STATISTICS
============================================================

,count,mean,std,min,25%,50%,75%,max,skewness,kurtosis,missing_pct
ask_price,10374.0,0.531770,9.018476e-01,1.798534e-05,0.055212,0.210390,0.610769,5.779963e+00,3.569149,15.134585,24.2
bid_price,9813.0,0.515194,8.744750e-01,1.838622e-05,0.053171,0.199548,0.593088,5.494841e+00,3.510671,14.487640,28.3
capital_expenditures,12969.0,13713.974281,4.636293e+04,0.000000e+00,137.329676,1028.487888,5720.509773,3.492992e+05,5.585979,33.775360,5.3
cash,11841.0,24656.359592,8.375583e+04,1.442614e-01,614.484520,2998.112030,11028.118784,6.461765e+05,5.878941,37.191576,13.5
current_assets_total,11609.0,136179.099382,3.641555e+05,1.472415e+00,7532.673693,25817.616187,81412.313699,2.443060e+06,4.599723,22.603544,15.2
current_liabilities_total,11621.0,97685.077200,2.889073e+05,5.956477e-01,3349.831775,14388.595090,57861.864425,2.113606e+06,5.263778,30.133522,15.1
earnings_bef_interest_tax,11729.0,31449.801283,1.042240e+05,-2.128192e+04,344.753759,3389.364079,13665.771106,7.763569e+05,5.391315,31.638702,14.3
employees,6570.0,3694.716591,9.314435e+03,0.000000e+00,301.000000,912.000000,2753.750000,1.471980e+05,6.640295,63.904830,52.0
interest_expense_total,1316.0,102026.671892,3.361307e+05,1.549533e-03,189.069350,1491.702526,10043.571687,4.055784e+06,5.384865,37.922959,90.4
long_term_debt,12548.0,112211.906371,4.576196e+05,0.000000e+00,14.424473,1536.962699,18590.422162,3.482424e+06,5.914230,37.068708,8.3
market_capitalization,10835.0,365445.319578,1.149975e+06,3.439168e+01,11573.164792,43242.398478,153197.060182,8.174373e+06,5.130202,28.233882,20.8
market_value,10599.0,354.375858,1.105395e+03,2.892570e-02,11.395308,43.967184,152.237652,7.764126e+03,5.072778,27.475663,22.6
net_cash_flow_operating_actv,13517.0,40868.135876,3.310404e+05,-2.087097e+06,-0.146141,2253.241799,12151.539149,1.013806e+07,16.712262,382.830284,1.2
net_sales_or_revenues,12800.0,258567.077079,8.540528e+05,0.000000e+00,8617.447535,35568.904184,116853.875130,6.155568e+06,5.427276,30.921872,6.5
operating_income,12709.0,22356.515623,7.764246e+04,-2.787691e+04,27.142875,2182.307407,10174.926264,5.805187e+05,5.508637,32.977591,7.2
return_on_assets,13284.0,0.053444,8.088747e-02,-2.673000e-01,0.017000,0.049300,0.088000,3.357000e-01,-0.126834,4.051143,3.0
return_on_equity_total,13235.0,0.078456,1.996059e-01,-1.030700e+00,0.021400,0.084300,0.155900,6.854000e-01,-1.970614,11.327167,3.3
total_assets,13688.0,677785.969048,2.533230e+06,8.745968e+00,18129.658705,60128.829396,215997.842090,1.956186e+07,5.911220,37.259858,0.0
total_capital,12168.0,315546.782198,1.039079e+06,1.093843e+00,11273.242408,38650.030707,129610.506605,7.671725e+06,5.474087,32.173495,11.1
total_debt,13450.0,212064.708780,7.992360e+05,0.000000e+00,413.460574,8861.494785,54953.781719,5.958579e+06,5.643325,33.777641,1.7
total_liabilities,13629.0,454556.893730,1.901932e+06,5.304098e-01,4762.263652,21625.947417,102888.281663,1.463831e+07,6.026460,37.987911,0.4
tri,11844.0,705.064130,2.222387e+03,1.000000e-02,63.737500,144.730000,417.887500,5.472958e+04,8.556217,104.656425,13.5
emissions_intensity,13308.0,1384.439804,2.364927e+03,7.147347e+01,271.999136,533.594690,1287.218149,1.504463e+04,3.532743,14.294533,2.8
esg_score,1437.0,50.563556,1.801624e+01,2.700000e-01,38.170000,52.290000,63.830000,9.195000e+01,-0.377212,-0.296648,89.5
estimated_total_carbon_footprint,13308.0,984917.384316,4.397868e+06,3.026443e+01,6849.737306,29317.007133,137698.069490,3.415410e+07,6.224443,40.359742,2.8
internal_carbon_pricing,62.0,454.810645,1.353607e+03,2.000000e+00,40.000000,200.000000,637.500000,1.071100e+04,7.357439,56.469059,99.5
internal_carbon_price_per_tonne,62.0,454.810645,1.353607e+03,2.000000e+00,40.000000,200.000000,637.500000,1.071100e+04,7.357439,56.469059,99.5
green_bond_proceeds,13688.0,0.588491,1.942339e+01,0.000000e+00,0.000000,0.000000,0.000000,9.715026e+02,37.902962,1518.185605,0.0
green_bond_issue,13688.0,0.001388,3.723240e-02,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00,26.787678,715.684282,0.0
green_bond_active,13688.0,0.004310,6.551396e-02,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00,15.134548,227.087710,0.0
gic,13688.0,1.820792,1.637968e+00,1.000000e+00,1.000000,1.000000,2.000000,6.000000e+00,1.839984,1.805533,0.0
environmental_investment,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
ln_total_assets,13688.0,10.726509,2.746210e+00,2.168593e+00,9.805304,11.004245,12.283024,1.678909e+01,-0.761961,1.069171,0.0

============================================================
SANITY CHECKS
============================================================
ROA range: [-0.2673, 0.3357] (should be decimal, e.g. 0.05 = 5%)
ROE range: [-1.0307, 0.6854]

environmental_investment value counts (NaN should exist, not be 0):
environmental_investment
NaN    13688
Name: count, dtype: int64

============================================================
PEARSON CORRELATION MATRIX
============================================================

,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,earnings_bef_interest_tax,employees,interest_expense_total,long_term_debt,...,total_liabilities,tri,emissions_intensity,esg_score,estimated_total_carbon_footprint,green_bond_proceeds,green_bond_issue,green_bond_active,gic,ln_total_assets
ask_price,1.000000,0.999307,0.213372,0.246933,0.236814,0.203633,0.329899,0.140532,0.400042,0.256198,...,0.203918,0.192742,0.048474,0.150268,0.176843,0.018087,0.014431,0.018581,-0.011936,0.280843
bid_price,0.999307,1.000000,0.228032,0.253353,0.249745,0.215269,0.336826,0.152412,0.402430,0.261044,...,0.210265,0.194057,0.045959,0.130559,0.186902,0.019622,0.015904,0.020755,-0.015800,0.287903
capital_expenditures,0.213372,0.228032,1.000000,0.743583,0.730392,0.792224,0.666407,0.445992,0.290573,0.715510,...,0.461925,0.226609,0.120215,0.315593,0.417044,0.132894,0.110156,0.150098,-0.013929,0.416664
cash,0.246933,0.253353,0.743583,1.000000,0.837902,0.817032,0.785955,0.440193,0.686821,0.790606,...,0.797213,0.147166,0.173110,0.319389,0.534212,0.114446,0.091788,0.175489,-0.028740,0.432025
current_assets_total,0.236814,0.249745,0.730392,0.837902,1.000000,0.904572,0.816021,0.451057,0.374996,0.742688,...,0.773130,0.182064,0.116988,0.325944,0.500522,0.084520,0.064902,0.135583,-0.013592,0.519637
current_liabilities_total,0.203633,0.215269,0.792224,0.817032,0.904572,1.000000,0.775116,0.540012,0.534258,0.818873,...,0.866411,0.222181,0.111408,0.294252,0.483879,0.083071,0.061687,0.145217,0.024279,0.495399
earnings_bef_interest_tax,0.329899,0.336826,0.666407,0.785955,0.816021,0.775116,1.000000,0.471655,0.798860,0.764062,...,0.785643,0.182165,0.265970,0.288500,0.562780,0.049679,0.036999,0.087098,0.089188,0.475980
employees,0.140532,0.152412,0.445992,0.440193,0.451057,0.540012,0.471655,1.000000,0.641239,0.459399,...,0.444805,0.292814,0.118940,0.128741,0.346139,0.016071,0.000380,0.021173,0.011500,0.290772
interest_expense_total,0.400042,0.402430,0.290573,0.686821,0.374996,0.534258,0.798860,0.641239,1.000000,0.691251,...,0.820347,0.024112,0.486710,0.308760,0.738460,-0.009993,-0.012255,-0.024666,-0.219477,0.473745
long_term_debt,0.256198,0.261044,0.715510,0.790606,0.742688,0.818873,0.764062,0.459399,0.691251,1.000000,...,0.769876,0.223531,0.239664,0.364695,0.540489,0.113689,0.092726,0.182690,0.061316,0.428080
market_capitalization,0.360888,0.368669,0.687795,0.752071,0.769191,0.742658,0.877800,0.472377,0.795083,0.736918,...,0.715190,0.218261,0.209176,0.315436,0.523000,0.075123,0.060207,0.119246,0.054757,0.466019
market_value,0.376031,0.383777,0.703390,0.740468,0.765751,0.742199,0.866913,0.472095,0.788970,0.743154,...,0.714868,0.226373,0.205634,0.328598,0.528340,0.084090,0.069935,0.137488,0.046666,0.463564
net_cash_flow_operating_actv,0.229351,0.239183,0.465389,0.492952,0.451046,0.488749,0.573839,0.260270,0.419208,0.546048,...,0.507371,0.135501,0.132574,0.255154,0.458459,0.067573,0.038234,0.140081,0.022066,0.218480
net_sales_or_revenues,0.290220,0.296158,0.729509,0.798601,0.851521,0.887501,0.797178,0.542098,0.851524,0.765946,...,0.697213,0.205852,0.207059,0.353238,0.649990,0.061662,0.041707,0.082786,-0.011120,0.445931
operating_income,0.344993,0.352534,0.618653,0.732039,0.762344,0.701703,0.930012,0.401178,0.742812,0.697357,...,0.724674,0.174366,0.252714,0.300808,0.564767,0.051383,0.038956,0.078919,0.077169,0.440000
return_on_assets,0.247866,0.246307,0.019621,0.028771,0.020330,-0.018844,0.098170,-0.060094,-0.144823,-0.038939,...,-0.062946,0.085077,-0.079320,-0.041498,-0.019890,-0.006251,-0.000417,-0.005980,-0.029817,0.103180
return_on_equity_total,0.216752,0.213431,0.051058,0.033907,0.041350,-0.002697,0.134043,0.014296,0.108460,0.005987,...,0.029382,0.093901,-0.021377,0.032820,0.026159,-0.001522,0.002620,0.001961,0.004037,0.141192
total_assets,0.232707,0.242234,0.536291,0.831522,0.816259,0.869603,0.836930,0.453426,0.829694,0.812181,...,0.983261,0.143061,0.377051,0.321908,0.582262,0.059036,0.051300,0.098988,0.143155,0.461131
total_capital,0.271780,0.278138,0.731937,0.838373,0.837220,0.854095,0.861893,0.478103,0.749181,0.938931,...,0.832958,0.193384,0.277510,0.375191,0.602331,0.093568,0.077149,0.159316,0.077031,0.489550
total_debt,0.227890,0.241869,0.609365,0.802675,0.775140,0.876272,0.810675,0.486636,0.812812,0.918316,...,0.888590,0.183635,0.326454,0.318221,0.560675,0.082026,0.065054,0.136965,0.118265,0.456689
total_liabilities,0.203918,0.210265,0.461925,0.797213,0.773130,0.866411,0.785643,0.444805,0.820347,0.769876,...,1.000000,0.126883,0.386771,0.301372,0.539220,0.055331,0.049046,0.090999,0.154316,0.433393
tri,0.192742,0.194057,0.226609,0.147166,0.182064,0.222181,0.182165,0.292814,0.024112,0.223531,...,0.126883,1.000000,-0.018685,0.239644,0.079041,0.006736,0.001443,0.020170,-0.036964,0.064614
emissions_intensity,0.048474,0.045959,0.120215,0.173110,0.116988,0.111408,0.265970,0.118940,0.486710,0.239664,...,0.386771,-0.018685,1.000000,0.111710,0.479896,0.030952,0.037449,0.065976,0.119501,0.061787
esg_score,0.150268,0.130559,0.315593,0.319389,0.325944,0.294252,0.288500,0.128741,0.308760,0.364695,...,0.301372,0.239644,0.111710,1.000000,0.249884,0.078967,0.096850,0.153807,-0.035918,0.316740
estimated_total_carbon_footprint,0.176843,0.186902,0.417044,0.534212,0.500522,0.483879,0.562780,0.346139,0.738460,0.540489,...,0.539220,0.079041,0.479896,0.249884,1.000000,0.060716,0.039280,0.104126,0.028177,0.269523
green_bond_proceeds,0.018087,0.019622,0.132894,0.114446,0.084520,0.083071,0.049679,0.016071,-0.009993,0.113689,...,0.055331,0.006736,0.030952,0.078967,0.060716,1.000000,0.812685,0.460507,0.006952,0.044176
green_bond_issue,0.014431,0.015904,0.110156,0.091788,0.064902,0.061687,0.036999,0.000380,-0.012255,0.092726,...,0.049046,0.001443,0.037449,0.096850,0.039280,0.812685,1.000000,0.566649,0.012465,0.043840
green_bond_active,0.018581,0.020755,0.150098,0.175489,0.135583,0.145217,0.087098,0.021173,-0.024666,0.182690,...,0.090999,0.020170,0.065976,0.153807,0.104126,0.460507,0.566649,1.000000,0.026944,0.076174
gic,-0.011936,-0.015800,-0.013929,-0.028740,-0.013592,0.024279,0.089188,0.011500,-0.219477,0.061316,...,0.154316,-0.036964,0.119501,-0.035918,0.028177,0.006952,0.012465,0.026944,1.000000,0.034123
ln_total_assets,0.280843,0.287903,0.416664,0.432025,0.519637,0.495399,0.475980,0.290772,0.473745,0.428080,...,0.433393,0.064614,0.061787,0.316740,0.269523,0.044176,0.043840,0.076174,0.034123,1.000000

High correlations (|r| > 0.8):
  ask_price ↔ bid_price: 0.999
  cash ↔ current_assets_total: 0.838
  cash ↔ current_liabilities_total: 0.817
  cash ↔ total_assets: 0.832
  cash ↔ total_capital: 0.838
  cash ↔ total_debt: 0.803
  current_assets_total ↔ current_liabilities_total: 0.905
  current_assets_total ↔ earnings_bef_interest_tax: 0.816
  current_assets_total ↔ net_sales_or_revenues: 0.852
  current_assets_total ↔ total_assets: 0.816
  current_assets_total ↔ total_capital: 0.837
  current_liabilities_total ↔ long_term_debt: 0.819
  current_liabilities_total ↔ net_sales_or_revenues: 0.888
  current_liabilities_total ↔ total_assets: 0.870
  current_liabilities_total ↔ total_capital: 0.854
  current_liabilities_total ↔ total_debt: 0.876
  current_liabilities_total ↔ total_liabilities: 0.866
  earnings_bef_interest_tax ↔ market_capitalization: 0.878
  earnings_bef_interest_tax ↔ market_value: 0.867
  earnings_bef_interest_tax ↔ operating_income: 0.930
  earnings_bef_interest_tax ↔ total_assets: 0.837
  earnings_bef_interest_tax ↔ total_capital: 0.862
  earnings_bef_interest_tax ↔ total_debt: 0.811
  interest_expense_total ↔ net_sales_or_revenues: 0.852
  interest_expense_total ↔ total_assets: 0.830
  interest_expense_total ↔ total_debt: 0.813
  interest_expense_total ↔ total_liabilities: 0.820
  long_term_debt ↔ total_assets: 0.812
  long_term_debt ↔ total_capital: 0.939
  long_term_debt ↔ total_debt: 0.918
  market_capitalization ↔ market_value: 0.971
  market_capitalization ↔ operating_income: 0.842
  market_capitalization ↔ total_capital: 0.847
  market_value ↔ operating_income: 0.826
  market_value ↔ total_capital: 0.854
  net_sales_or_revenues ↔ total_capital: 0.819
  operating_income ↔ total_capital: 0.806
  return_on_assets ↔ return_on_equity_total: 0.825
  total_assets ↔ total_capital: 0.897
  total_assets ↔ total_debt: 0.907
  total_assets ↔ total_liabilities: 0.983
  total_capital ↔ total_debt: 0.921
  total_capital ↔ total_liabilities: 0.833
  total_debt ↔ total_liabilities: 0.889
  green_bond_proceeds ↔ green_bond_issue: 0.813