In [20]:
import pandas as pd
import numpy as np

# Merge Panel Data

In [21]:
# 1. Load the data
df1 = pd.read_csv("../data/panel_data.csv")
df2 = pd.read_csv("../data/esg_panel_data.csv")

# 2. DROP THE EXTRA HEADER ROWS
df1 = df1[df1["Year"] != "Year"]
df2 = df2[df2["Year"] != "Year"]

# 3. NOW it is safe to convert them to integers
df1["Year"] = df1["Year"].astype(int)

# (df2's columns were renamed in your cell 12, so make sure to do that first)
df2 = df2.rename(columns={"ticker": "isin"}) 
df2["Year"] = df2["Year"].astype(int)

In [22]:
df1.head()

,company,ticker,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,net_cash_flow_operating_actv,net_sales_or_revenues,operating_income,return_on_assets,return_on_equity_total,total_assets,total_capital,total_debt,total_liabilities,tri
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,139551920.0,557407302.0,120073608.0,23.12,32.37,443321800.0,325687074.0,12154497.0,117634726.0,915.21
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.9,81063081.0,26696986.0,373711509.0,159031144.0,...,159226609.0,520269497.0,104861803.0,19.17,26.44,550731097.0,393873772.0,62680107.0,170454686.0,1292.29
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,116226295.0,559746010.0,108434020.0,14.24,21.23,745486949.0,479984306.0,186715604.0,305496890.0,1662.77
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,164716711.0,722333338.0,110365095.0,12.95,19.85,780505063.0,533398478.0,164144027.0,288917413.0,1605.27
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,77719241.0,802112862.0,74237342.0,9.9,14.14,894945037.0,558134707.0,256450459.0,383110921.0,1421.17

In [23]:
df2.head()

,company,isin,country,Year,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne
0,3-2 INVESTMENT AND,VN000000C325,Vietnam,2015,2546.06881537,NaN,NaN,64828.86744533,NaN,NaN
1,3-2 INVESTMENT AND,VN000000C325,Vietnam,2016,2819.72533457,NaN,NaN,65675.45104572,NaN,NaN
2,3-2 INVESTMENT AND,VN000000C325,Vietnam,2017,4362.53269686,NaN,NaN,107555.91160331,NaN,NaN
3,3-2 INVESTMENT AND,VN000000C325,Vietnam,2018,3615.6048792,NaN,NaN,113458.60952198,NaN,NaN
4,3-2 INVESTMENT AND,VN000000C325,Vietnam,2019,1825.21286898,NaN,NaN,63036.40639962,NaN,NaN

In [24]:
# load market data
vn = pd.read_csv("../data/vn-market.csv")
tl = pd.read_csv("../data/tl-market.csv")
ml = pd.read_csv("../data/ml-market.csv")
sing = pd.read_csv("../data/sing-market.csv")
pp = pd.read_csv("../data/pp-market.csv")
other = pd.read_csv("../data/other-market.csv")

In [25]:
market_data = pd.concat([vn, tl, ml, sing, pp], ignore_index=True)
market_data.drop("currency", axis=1, inplace=True)

other = other.reindex(columns=["name", "ric", "org_permid", "isin"])
market_data = pd.concat([market_data, other], ignore_index=True)

In [26]:
tmp1 = pd.merge(df2, market_data, on="isin", how="inner")
tmp1.drop(["name", "org_permid", "company", "country"], axis=1, inplace=True)

In [27]:
df1.columns = ['company', 'ric', 'country', 'Year', 'ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities',
       'tri']

In [28]:
df1["Year"] = df1["Year"].astype(int)
tmp1["Year"] = tmp1["Year"].astype(int)

merge_data = pd.merge(df1, tmp1, on=["ric", "Year"], how="left")
merge_data

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,12154497.0,117634726.0,915.21,VN000000C325,2546.06881537,NaN,NaN,64828.86744533,NaN,NaN
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.9,81063081.0,26696986.0,373711509.0,159031144.0,...,62680107.0,170454686.0,1292.29,VN000000C325,2819.72533457,NaN,NaN,65675.45104572,NaN,NaN
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,186715604.0,305496890.0,1662.77,VN000000C325,4362.53269686,NaN,NaN,107555.91160331,NaN,NaN
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,164144027.0,288917413.0,1605.27,VN000000C325,3615.6048792,NaN,NaN,113458.60952198,NaN,NaN
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,256450459.0,383110921.0,1421.17,VN000000C325,1825.21286898,NaN,NaN,63036.40639962,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54030,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.78,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.61331027,NaN,50.4,22416.96070021,NaN,N
54031,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.78,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.61331027,NaN,50.4,22416.96070021,NaN,N
54032,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.78,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.61331027,NaN,50.4,22416.96070021,NaN,N
54033,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.78,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.61331027,NaN,50.4,22416.96070021,NaN,N
54034,ZETRIX AI BHD,ZETR.KL,Malaysia,2025,0.98,0.975,NaN,NaN,NaN,NaN,...,NaN,NaN,12208.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# Reset the index so it starts from 0 cleanly
merge_data = merge_data.reset_index(drop=True)

# Drop redundant duplicate rows if the market data caused any
merge_data = merge_data.drop_duplicates(subset=["ric", "Year"])

# Verify the final count 
print("Final Cleaned Panel Rows:", len(merge_data))
merge_data.head()

Final Cleaned Panel Rows: 44422

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,12154497.0,117634726.0,915.21,VN000000C325,2546.06881537,NaN,NaN,64828.86744533,NaN,NaN
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.9,81063081.0,26696986.0,373711509.0,159031144.0,...,62680107.0,170454686.0,1292.29,VN000000C325,2819.72533457,NaN,NaN,65675.45104572,NaN,NaN
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,186715604.0,305496890.0,1662.77,VN000000C325,4362.53269686,NaN,NaN,107555.91160331,NaN,NaN
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,164144027.0,288917413.0,1605.27,VN000000C325,3615.6048792,NaN,NaN,113458.60952198,NaN,NaN
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,256450459.0,383110921.0,1421.17,VN000000C325,1825.21286898,NaN,NaN,63036.40639962,NaN,NaN

In [30]:
gb = pd.read_csv("../data/greenbonds.csv")

In [31]:
gb.head()

,Exceeded the limit for the Number of Deals,Package Identifier,Master Deal Type Code,All New Issues Manager Roles Code,Manager's Role Code,Dates: Issue Date,Issuer/Borrower Name Full,Issuer/Borrower PermID,Issue Type,Transaction Status,...,Issuer/Borrower TRBC Business Sector,Issuer/Borrower TRBC Economic Sector,Lead Left Bookrunner,Managers Tier 1 & Tier 2,ECM Flag,Primary Use Of Proceeds,Issuer/Borrower Nation Region,Master Deal Type,All New Issues Manager Roles,Manager's Role
0,154084480389,3480516,D,JB|JB|JB|CM|CM|CM|CM,JB|JB|JB|CM|CM|CM|CM,8/1/2017,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
1,154084486562,3480516,D,JB|JB|JB|CM|CM|CM|CM,JB|JB|JB|CM|CM|CM|CM,8/1/2017,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
2,154084490384,9983331,D,JB|JB|JB,JB|JB|JB,3/12/2015,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Morgan Stanley &...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
3,154084593248,3319100,D,JB|JB|JB,JB|JB|JB,8/9/2016,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
4,154084594902,3319989,ED,JB|JB|JB|JB|JB,JB|JB|JB|JB|JB,8/10/2016,Greenko Investment Co,5.051761e+09,High Yield Corporate,Live,...,Banking & Investment Services,Financials,Deutsche Bank,Deutsche Bank|Investec Bank Ltd|JP Morgan & Co...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,Euro & Foreign Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...

In [32]:
gb["Year"] = pd.to_datetime(gb["Dates: Issue Date"]).dt.year
# Keep only necessary columns
gb = gb[["Issuer/Borrower PermID", "Year", "Proceeds Amount This Market"]].rename(columns={"Issuer/Borrower PermID": "org_permid"})
# Standardize org_permid to string to match market_data
gb["org_permid"] = gb["org_permid"].apply(lambda x: str(int(x)) if pd.notna(x) else np.nan)
gb.head()

   org_permid  Year  Proceeds Amount This Market
0  8589934162  2017                     495.8600
1  8589934162  2017                     746.4825
2  8589934162  2015                     496.4700
3  8589934162  2016                     798.2320
4  5051761072  2016                     500.0000

In [33]:
market_data["org_permid_str"] = pd.to_numeric(market_data["org_permid"], errors='coerce')
market_data["org_permid_str"] = market_data["org_permid_str"].apply(lambda x: str(int(x)) if pd.notna(x) else np.nan)
# Map PermID to RIC
gb_mapped = pd.merge(gb, market_data[["org_permid_str", "ric"]].dropna(), left_on="org_permid", right_on="org_permid_str", how="inner")
gb_mapped.head()

   org_permid  Year  Proceeds Amount This Market org_permid_str       ric
0  4295888106  2017                        500.0     4295888106   DBSM.SI
1  4295888106  2017                        500.0     4295888106    DBSM.F
2  4295888106  2017                        500.0     4295888106  DBSDF.PK
3  4295888106  2017                        500.0     4295888106  DBSDY.PK
4  4295888106  2017                        500.0     4295888106   DEVGy.F

In [34]:
gb_agg = gb_mapped.groupby(["ric", "Year"], as_index=False).agg(
    green_bond_proceeds=("Proceeds Amount This Market", "sum")
)
gb_agg["green_bond_issue"] = 1
gb_agg.head()

         ric  Year  green_bond_proceeds  green_bond_issue
0  009830.KS  2021           152.832755                 1
1   ACDSF.PK  2020           511.413086                 1
2    ALCO.PS  2020           118.319858                 1
3   ALCPD.PS  2020            59.159929                 1
4   ALCPF.PS  2020            59.159929                 1

In [35]:
final_panel = pd.merge(merge_data, gb_agg, on=["ric", "Year"], how="left")
# Fill missing values from the merge with 0 (since no issuance = 0)
final_panel["green_bond_issue"] = final_panel["green_bond_issue"].fillna(0)
final_panel["green_bond_proceeds"] = final_panel["green_bond_proceeds"].fillna(0)
# Create the cumulative Green Bond dummy (1 for the year of issue and all years after)
final_panel = final_panel.sort_values(by=["ric", "Year"])
final_panel["green_bond_active"] = final_panel.groupby("ric")["green_bond_issue"].cumsum().clip(upper=1)
print(final_panel.shape)
final_panel.head()

(44422, 36)

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active
13820,9F INC,0,Malaysia,2020,163.86,1093.28,79.47,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13821,9F INC,0,Malaysia,2021,34.6,263.34,17.24,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13822,9F INC,0,Malaysia,2022,19.5,171.86,9.41,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13823,9F INC,0,Malaysia,2023,2.07,19.26,1.03,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13824,9F INC,0,Malaysia,2024,2.46,23.88,1.28,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [36]:
final_panel = final_panel.sort_index()

In [37]:
final_panel

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,VN000000C325,2546.06881537,NaN,NaN,64828.86744533,NaN,NaN,0.0,0.0,0.0
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.9,81063081.0,26696986.0,373711509.0,159031144.0,...,VN000000C325,2819.72533457,NaN,NaN,65675.45104572,NaN,NaN,0.0,0.0,0.0
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,VN000000C325,4362.53269686,NaN,NaN,107555.91160331,NaN,NaN,0.0,0.0,0.0
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,VN000000C325,3615.6048792,NaN,NaN,113458.60952198,NaN,NaN,0.0,0.0,0.0
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,VN000000C325,1825.21286898,NaN,NaN,63036.40639962,NaN,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44417,SIME DARBY,SIPR.KL,Malaysia,2017,NaN,NaN,26298.0,1075260.0,8755777.0,3741719.0,...,MYL5288OO005,346.92193886,NaN,47.02,211726.28182438,NaN,N,0.0,0.0,0.0
44418,SOLARVEST HOLD,SOLA.KL,Malaysia,2016,NaN,NaN,2394.0,NaN,12149.0,8831.0,...,MYQ0215OO002,3506.65016911,NaN,NaN,30743.95477746,NaN,NaN,0.0,0.0,0.0
44419,SOLARVEST HOLD,SOLA.KL,Malaysia,2017,NaN,NaN,1592.0,NaN,14578.0,7928.0,...,MYQ0215OO002,5819.55947217,NaN,NaN,54128.44352843,NaN,NaN,0.0,0.0,0.0
44420,SOLARVEST HOLD,SOLA.KL,Malaysia,2018,NaN,NaN,2517.0,NaN,21385.0,8385.0,...,MYQ0215OO002,6250.15559179,NaN,NaN,67680.69576344,NaN,NaN,0.0,0.0,0.0
44421,SOLARVEST HOLD,SOLA.KL,Malaysia,2019,NaN,NaN,1594.0,NaN,69155.0,44251.0,...,MYQ0215OO002,6901.32257892,NaN,NaN,190110.93047209,NaN,NaN,0.0,0.0,0.0

In [38]:
# 1. Load the Series Data
series_df = pd.read_csv("../data/series_data.csv")

# 2. We only need the 'ticker' (which is the ric) and 'gic' columns
# (You already have the 'country' column in your final_panel)
series_df = series_df[['ticker', 'gic']]

# 3. Rename 'ticker' to 'ric' so it perfectly matches the final_panel column name
series_df = series_df.rename(columns={'ticker': 'ric'})

# 4. Merge the GIC codes back into the master panel!
final_panel = pd.merge(final_panel, series_df, on="ric", how="left")

# Print to check the output
print(final_panel.shape)

# (Optional: If you appended multiple times, the series data might have duplicates too)
# Run this just to be perfectly safe, then save:
final_panel = final_panel.drop_duplicates(subset=["ric", "Year"])

(44868, 37)

In [39]:
# final_panel.to_csv("../processed_data/final_data.csv")

# Data Processing

In [40]:
final_panel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44422 entries, 0 to 44866
Data columns (total 37 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   company                           44412 non-null  object
 1   ric                               44422 non-null  object
 2   country                           44422 non-null  object
 3   Year                              44422 non-null  int64
 4   ask_price                         35660 non-null  object
 5   bid_price                         21100 non-null  object
 6   capital_expenditures              28906 non-null  object
 7   cash                              20940 non-null  object
 8   current_assets_total              12129 non-null  object
 9   current_liabilities_total         12143 non-null  object
 10  earnings_bef_interest_tax         13518 non-null  object
 11  employees                         6643 non-null   object
 12  interest_expense_total            1540 non-null   object
 13  long_term_debt                    13670 non-null  object
 14  market_capitalization             13460 non-null  object
 15  market_value                      13850 non-null  object
 16  net_cash_flow_operating_actv      14174 non-null  object
 17  net_sales_or_revenues             14043 non-null  object
 18  operating_income                  13949 non-null  object
 19  return_on_assets                  13794 non-null  object
 20  return_on_equity_total            13729 non-null  object
 21  total_assets                      14279 non-null  object
 22  total_capital                     14044 non-null  object
 23  total_debt                        14074 non-null  object
 24  total_liabilities                 14273 non-null  object
 25  tri                               13995 non-null  object
 26  isin                              30307 non-null  object
 27  emissions_intensity               29854 non-null  object
 28  environmental_investment          4859 non-null   object
 29  esg_score                         6185 non-null   object
 30  estimated_total_carbon_footprint  29854 non-null  object
 31  internal_carbon_pricing           728 non-null    object
 32  internal_carbon_price_per_tonne   6662 non-null   object
 33  green_bond_proceeds               44422 non-null  float64
 34  green_bond_issue                  44422 non-null  float64
 35  green_bond_active                 44422 non-null  float64
 36  gic                               42528 non-null  object
dtypes: float64(3), int64(1), object(33)
memory usage: 12.9+ MB

In [41]:
tmp1 = final_panel[final_panel["environmental_investment"].notna()]
tmp1

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active,gic
208,BAMBOO CAPITAL,BCG.HM,Vietnam,2020,3809.53,3803.25,2128566266.0,903386455.0,11338108288.0,10609458385.0,...,511.81584085,N,30.73,40862.45508157,N,NaN,0.000000,0.0,0.0,1.0
209,BAMBOO CAPITAL,BCG.HM,Vietnam,2021,9852.27,9783.86,2153024873.0,1044039648.0,16238689244.0,10197137593.0,...,727.22184486,N,29.97,82114.13821299,N,NaN,0.000000,0.0,0.0,1.0
210,BAMBOO CAPITAL,BCG.HM,Vietnam,2022,20519.48,20389.61,3452957149.0,629496376.0,17761709187.0,11380169032.0,...,522.08967477,N,33.84,101175.86547991,N,NaN,0.000000,0.0,0.0,1.0
211,BAMBOO CAPITAL,BCG.HM,Vietnam,2023,5836.36,5827.27,132426498.0,756859465.0,19478597670.0,12090231560.0,...,497.57761896,N,34.54,83808.824093,N,NaN,0.000000,0.0,0.0,1.0
212,BAMBOO CAPITAL,BCG.HM,Vietnam,2024,7645.45,7636.36,287264578.0,722226655.0,22192281556.0,13228418571.0,...,572.12359601,N,31.34,99889.030077,NaN,NaN,0.000000,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44830,HANWHA SOLUTIONS,009830.KS,Other,2020,20480.87,20426.54,883786181.0,1199836791.0,4958364766.0,5251125587.0,...,5643.6770326,Y,73.05,44068773.693947,NaN,N,0.000000,0.0,0.0,1.0
44831,HANWHA SOLUTIONS,009830.KS,Other,2021,52523.2,52467.56,812670936.0,1651530298.0,6159819811.0,5789061165.0,...,4885.61560282,Y,64.46,45821015.287888,NaN,N,152.832755,1.0,1.0,1.0
44832,HANWHA SOLUTIONS,009830.KS,Other,2022,37111.2,37055.56,902923088.0,2616168297.0,8642576225.0,6810183012.0,...,2601.2523099,Y,61.56,26536093.905194,NaN,N,0.000000,0.0,1.0,1.0
44833,HANWHA SOLUTIONS,009830.KS,Other,2023,46291.63,46235.99,2390483416.0,1958054672.0,8708394577.0,7689704560.0,...,2587.19032097,Y,68.58,25930296.81766,NaN,N,0.000000,0.0,1.0,1.0
44834,HANWHA SOLUTIONS,009830.KS,Other,2024,26950.0,26900.0,3397574334.0,2184380593.0,10882665025.0,11707552341.0,...,1634.18196089,Y,73.43,14869428.540835,NaN,NaN,0.000000,0.0,1.0,1.0

In [42]:
final_panel.columns

Index(['company', 'ric', 'country', 'Year', 'ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities',
       'tri', 'isin', 'emissions_intensity', 'environmental_investment',
       'esg_score', 'estimated_total_carbon_footprint',
       'internal_carbon_pricing', 'internal_carbon_price_per_tonne',
       'green_bond_proceeds', 'green_bond_issue', 'green_bond_active', 'gic'],
      dtype='object')

float: ask_price, bid_price, capital_expenditures, cash, current_assets_total, current_liabilities_total, earnings_bef_interest_tax, interest_expense_total, long_term_debt, market_capitalization, market_value, net_cash_flow_operating_actv, net_sales_or_revenues, operating_income, return_on_assets, return_on_equity_total, total_assets, total_capital, total_debt, total_liabilities, tri, emissions_intensity, green_bond_proceeds, green_bond_issue, green_bond_active, gic

need_encode: environmental_investment, internal_carbon_pricing

In [43]:
numeric_attributes = ['ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities', "tri", "emissions_intensity", "green_bond_proceeds", "green_bond_issue", "green_bond_active", "gic"]

encoded_attributes = ["environmental_investment", "internal_carbon_pricing"]

In [44]:
final_panel[numeric_attributes] = final_panel[numeric_attributes].astype(float)

In [45]:
final_panel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44422 entries, 0 to 44866
Data columns (total 37 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   company                           44412 non-null  object
 1   ric                               44422 non-null  object
 2   country                           44422 non-null  object
 3   Year                              44422 non-null  int64
 4   ask_price                         35660 non-null  float64
 5   bid_price                         21100 non-null  float64
 6   capital_expenditures              28906 non-null  float64
 7   cash                              20940 non-null  float64
 8   current_assets_total              12129 non-null  float64
 9   current_liabilities_total         12143 non-null  float64
 10  earnings_bef_interest_tax         13518 non-null  float64
 11  employees                         6643 non-null   float64
 12  interest_expense_total            1540 non-null   float64
 13  long_term_debt                    13670 non-null  float64
 14  market_capitalization             13460 non-null  float64
 15  market_value                      13850 non-null  float64
 16  net_cash_flow_operating_actv      14174 non-null  float64
 17  net_sales_or_revenues             14043 non-null  float64
 18  operating_income                  13949 non-null  float64
 19  return_on_assets                  13794 non-null  float64
 20  return_on_equity_total            13729 non-null  float64
 21  total_assets                      14279 non-null  float64
 22  total_capital                     14044 non-null  float64
 23  total_debt                        14074 non-null  float64
 24  total_liabilities                 14273 non-null  float64
 25  tri                               13995 non-null  float64
 26  isin                              30307 non-null  object
 27  emissions_intensity               29854 non-null  float64
 28  environmental_investment          4859 non-null   object
 29  esg_score                         6185 non-null   object
 30  estimated_total_carbon_footprint  29854 non-null  object
 31  internal_carbon_pricing           728 non-null    object
 32  internal_carbon_price_per_tonne   6662 non-null   object
 33  green_bond_proceeds               44422 non-null  float64
 34  green_bond_issue                  44422 non-null  float64
 35  green_bond_active                 44422 non-null  float64
 36  gic                               42528 non-null  float64
dtypes: float64(27), int64(1), object(9)
memory usage: 12.9+ MB

In [46]:
?pd.get_dummies

Signature:
pd.get_dummies(
    data,
    prefix=None,
    prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_',
    dummy_na: 'bool' = False,
    columns=None,
    sparse: 'bool' = False,
    drop_first: 'bool' = False,
    dtype: 'NpDtype | None' = None,
) -> 'DataFrame'
Docstring:
Convert categorical variable into dummy/indicator variables.

Each variable is converted in as many 0/1 variables as there are different
values. Columns in the output are each named after a value; if the input is
a DataFrame, the name of the original variable is prepended to the value.

Parameters
----------
data : array-like, Series, or DataFrame
    Data of which to get dummy indicators.
prefix : str, list of str, or dict of str, default None
    String to append DataFrame column names.
    Pass a list with length equal to the number of columns
    when calling get_dummies on a DataFrame. Alternatively, `prefix`
    can be a dictionary mapping column names to prefixes.
prefix_sep : str, default '_'
    If appending prefix, separator/delimiter to use. Or pass a
    list or dictionary as with `prefix`.
dummy_na : bool, default False
    Add a column to indicate NaNs, if False NaNs are ignored.
columns : list-like, default None
    Column names in the DataFrame to be encoded.
    If `columns` is None then all the columns with
    `object`, `string`, or `category` dtype will be converted.
sparse : bool, default False
    Whether the dummy-encoded columns should be backed by
    a :class:`SparseArray` (True) or a regular NumPy array (False).
drop_first : bool, default False
    Whether to get k-1 dummies out of k categorical levels by removing the
    first level.
dtype : dtype, default bool
    Data type for new columns. Only a single dtype is allowed.

Returns
-------
DataFrame
    Dummy-coded data. If `data` contains other columns than the
    dummy-coded one(s), these will be prepended, unaltered, to the result.

See Also
--------
Series.str.get_dummies : Convert Series of strings to dummy codes.
:func:`~pandas.from_dummies` : Convert dummy codes to categorical ``DataFrame``.

Notes
-----
Reference :ref:`the user guide <reshaping.dummies>` for more examples.

Examples
--------
>>> s = pd.Series(list('abca'))

>>> pd.get_dummies(s)
       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False

>>> s1 = ['a', 'b', np.nan]

>>> pd.get_dummies(s1)
       a      b
0   True  False
1  False   True
2  False  False

>>> pd.get_dummies(s1, dummy_na=True)
       a      b    NaN
0   True  False  False
1  False   True  False
2  False  False   True

>>> df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
...                    'C': [1, 2, 3]})

>>> pd.get_dummies(df, prefix=['col1', 'col2'])
   C  col1_a  col1_b  col2_a  col2_b  col2_c
0  1    True   False   False    True   False
1  2   False    True    True   False   False
2  3    True   False   False   False    True

>>> pd.get_dummies(pd.Series(list('abcaa')))
       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False
4   True  False  False

>>> pd.get_dummies(pd.Series(list('abcaa')), drop_first=True)
       b      c
0  False  False
1   True  False
2  False   True
3  False  False
4  False  False

>>> pd.get_dummies(pd.Series(list('abc')), dtype=float)
     a    b    c
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
File:      ~/miniconda3/lib/python3.13/site-packages/pandas/core/reshape/encoding.py
Type:      function

In [47]:
final_panel = pd.get_dummies(final_panel, columns=encoded_attributes, drop_first=True)

In [48]:
final_panel.columns = final_panel.columns.str.strip()

final_panel = final_panel.rename(columns={
    "environmental_investment_Y": "environmental_investment", 
    "internal_carbon_pricing_Y": "internal_carbon_pricing"
    })
final_panel

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,internal_carbon_pricing_683.69,internal_carbon_pricing_688.74,internal_carbon_pricing_690.61,internal_carbon_pricing_691,internal_carbon_pricing_70,internal_carbon_pricing_807,internal_carbon_pricing_840.64,internal_carbon_pricing_856.5,internal_carbon_pricing_858.58,internal_carbon_pricing_N
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,False,False,False,False,False,False,False,False,False,False
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.90,81063081.0,26696986.0,373711509.0,159031144.0,...,False,False,False,False,False,False,False,False,False,False
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,False,False,False,False,False,False,False,False,False,False
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,False,False,False,False,False,False,False,False,False,False
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44858,SIME DARBY,SIPR.KL,Malaysia,2017,NaN,NaN,26298.0,1075260.0,8755777.0,3741719.0,...,False,False,False,False,False,False,False,False,False,False
44860,SOLARVEST HOLD,SOLA.KL,Malaysia,2016,NaN,NaN,2394.0,NaN,12149.0,8831.0,...,False,False,False,False,False,False,False,False,False,False
44862,SOLARVEST HOLD,SOLA.KL,Malaysia,2017,NaN,NaN,1592.0,NaN,14578.0,7928.0,...,False,False,False,False,False,False,False,False,False,False
44864,SOLARVEST HOLD,SOLA.KL,Malaysia,2018,NaN,NaN,2517.0,NaN,21385.0,8385.0,...,False,False,False,False,False,False,False,False,False,False
44866,SOLARVEST HOLD,SOLA.KL,Malaysia,2019,NaN,NaN,1594.0,NaN,69155.0,44251.0,...,False,False,False,False,False,False,False,False,False,False

## Econometric Data Cleaning
Applying data cleaning techniques based on the Econometric Data Cleaning skill.
Tasks include:
- Handling missing values using forward fill by `ric`, then dropping rows still missing `total_assets`.
- Winsorizing continuous variables at the 1st and 99th percentiles.
- Currency conversion to USD using `yfinance`.
- Creating `ln_total_assets` transformation.
- Drop duplicate exact firm-year records.

*Note on Missing Data count:* `final_panel.dropna(subset=['total_assets'])` drops rows where `total_assets` is missing. This drops about 29k rows because many companies lack `total_assets` data even after forward filling on their `ric`.

In [49]:
import pandas as pd
import yfinance as yf
from scipy.stats.mstats import winsorize
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# 1. Handle Missing Values
# Forward fill dynamically logically sound variables, grouped by 'ric' (Reuters Instrument Code)
vars_to_ffill = ['total_assets', 'return_on_equity_total', 'emissions_intensity', 'environmental_investment']
for col in vars_to_ffill:
    if col in final_panel.columns:
        final_panel[col] = final_panel.groupby('ric')[col].transform(lambda x: x.ffill())

# Drop rows missing fundamental financial variables that cannot be safely imputed.
final_panel = final_panel.dropna(subset=['total_assets']).copy()
print(f"Shape after ffill and dropping NaN total_assets: {final_panel.shape}")

# 2. Winsorization
winsorize_vars = ['ask_price', 'bid_price', 'total_assets', 'return_on_assets', 'return_on_equity_total', 'net_sales_or_revenues', 'cash']
for col in winsorize_vars:
    if col in final_panel.columns:
        mask = final_panel[col].notna()
        final_panel.loc[mask, col] = winsorize(final_panel.loc[mask, col], limits=[0.01, 0.01])

# 3. Currency Conversion using yfinance to USD
years = sorted(final_panel['Year'].dropna().unique())
currency_map = {
    'Vietnam': 'VND=X',
    'Thailand': 'THB=X',
    'Malaysia': 'MYR=X',
    'Singapore': 'SGD=X',
    'Indonesia': 'IDR=X',
    'Philippines': 'PHP=X'
}

fx_rates = {}
for country, ticker in currency_map.items():
    tk = yf.Ticker(ticker)
    hist = tk.history(period="max")
    if not hist.empty:
        hist['Year'] = hist.index.year
        yearly_avg = hist.groupby('Year')['Close'].mean()
        fx_rates[country] = yearly_avg.to_dict()

financial_cols = [
    'ask_price', 'bid_price', 'capital_expenditures', 'cash', 
    'current_assets_total', 'current_liabilities_total', 'earnings_bef_interest_tax', 
    'interest_expense_total', 'long_term_debt', 'market_capitalization', 'market_value', 
    'net_cash_flow_operating_actv', 'net_sales_or_revenues', 'operating_income', 
    'total_assets', 'total_capital', 'total_debt', 'total_liabilities'
]

def get_fx_rate(row):
    country = row['country']
    year = row['Year']
    if country in fx_rates and year in fx_rates[country]:
        return fx_rates[country][year]
    return 1.0 # fallback

final_panel['fx_rate'] = final_panel.apply(get_fx_rate, axis=1)

for col in financial_cols:
    if col in final_panel.columns:
        final_panel[col] = final_panel[col] / final_panel['fx_rate']

final_panel.drop(columns=['fx_rate'], inplace=True)

# 4. Data Transformation & Normalization
# Log transform total_assets
final_panel['ln_total_assets'] = np.log(final_panel['total_assets'].replace(0, np.nan))

# 5. Data Type Verification
final_panel['isin'] = final_panel['isin'].astype(str)
final_panel['ric'] = final_panel['ric'].astype(str)
final_panel['country'] = final_panel['country'].astype(str)
final_panel['company'] = final_panel['company'].astype(str)
final_panel['Year'] = final_panel['Year'].astype(int)

# 6. Duplicates Resolution
final_panel = final_panel.sort_values(by=final_panel.columns.tolist()).drop_duplicates(subset=['ric', 'Year'], keep='last')

print("Data Cleaning Complete. Final Shape:", final_panel.shape)

# Save the cleaned dataset for the next step 
final_panel.to_csv('../processed_data/cleaned_panel_data.csv', index=False)

Shape after ffill and dropping NaN total_assets: (15211, 93)
Data Cleaning Complete. Final Shape: (15211, 94)

## Panel Data Validation
Structurally validating the firm-year panel dataset based on the Panel Data Validation skill.
Tasks include:
- Setting the multi-index (`['ric', 'Year']`).
- Checking if the panel is severely unbalanced.
- Generating descriptive statistics (Table 1).
- Producing a correlation matrix.

In [50]:
import pandas as pd
import numpy as np

# Load the cleaned dataset
final_panel = pd.read_csv('../processed_data/cleaned_panel_data.csv')

# 1. Set Multi-Index
panel = final_panel.set_index(['ric', 'Year']).sort_index()

# 2. Check Unbalanced Panel
obs_per_firm = panel.groupby(level='ric').size()
print("Panel Structure Check:")
print(f"Total Firms (RICs): {panel.index.get_level_values('ric').nunique()}")
print(f"Total Firm-Year Observations: {len(panel)}")
print(f"Average Years per Firm: {obs_per_firm.mean():.2f}")
print(f"Temporal Range: {panel.index.get_level_values('Year').min()} to {panel.index.get_level_values('Year').max()}")
print(f"Minimum Years for a single firm: {obs_per_firm.min()}")
print(f"Maximum Years for a single firm: {obs_per_firm.max()}")

# 3. Descriptive Statistics (Table 1)
primary_vars = [
    'total_assets', 'ln_total_assets', 'total_debt', 'return_on_assets', 
    'return_on_equity_total', 'emissions_intensity', 'environmental_investment'
]

# Ensure primary variables are numeric
for col in primary_vars:
    if col in final_panel.columns:
        final_panel[col] = pd.to_numeric(final_panel[col], errors='coerce')

desc_stats = final_panel[primary_vars].describe().T
desc_stats['skewness'] = final_panel[primary_vars].skew()
desc_stats['kurtosis'] = final_panel[primary_vars].kurt()
print("\nDescriptive Statistics:")
display(desc_stats)

# 4. Correlation Matrix
corr_matrix = final_panel[primary_vars].corr(method='pearson')
print("\nPearson Correlation Matrix:")
display(corr_matrix)

Panel Structure Check:
Total Firms (RICs): 1481
Total Firm-Year Observations: 15211
Average Years per Firm: 10.27
Temporal Range: 2015 to 2025
Minimum Years for a single firm: 2
Maximum Years for a single firm: 11

Descriptive Statistics:

,count,mean,std,min,25%,50%,75%,max,skewness,kurtosis
total_assets,15211.0,1.522643e+07,5.610699e+08,4.884761,18697.673403,61708.615698,224728.143789,3.312221e+10,43.291588,2031.723689
ln_total_assets,15211.0,1.076794e+01,2.781347e+00,1.586120,9.836154,11.030179,12.322647,2.422347e+01,-0.687674,1.449169
total_debt,14067.0,5.288184e+06,1.999865e+08,0.000000,464.639076,9272.705140,57948.912603,1.369925e+10,46.230994,2430.403163
return_on_assets,13793.0,5.444338e+00,7.915887e+00,-24.860000,1.780000,4.960000,8.820000,3.351000e+01,-0.003104,3.826638
return_on_equity_total,14735.0,7.459129e+00,2.046612e+01,-111.450000,2.050000,8.250000,15.330000,6.566000e+01,-2.351519,13.200249
emissions_intensity,14782.0,6.523050e+04,1.965063e+06,18.376731,277.700808,539.505177,1280.145881,7.920936e+07,33.510387,1146.086455

Pearson Correlation Matrix:

,total_assets,ln_total_assets,total_debt,return_on_assets,return_on_equity_total,emissions_intensity,environmental_investment
total_assets,1.000000,0.122439,0.991085,-0.014189,-0.011025,-0.000864,0.152356
ln_total_assets,0.122439,1.000000,0.120626,0.090907,0.140769,-0.097280,0.170668
total_debt,0.991085,0.120626,1.000000,-0.012770,-0.009843,-0.000742,0.172389
return_on_assets,-0.014189,0.090907,-0.012770,1.000000,0.812605,-0.043114,0.004546
return_on_equity_total,-0.011025,0.140769,-0.009843,0.812605,1.000000,-0.027232,0.011908
emissions_intensity,-0.000864,-0.097280,-0.000742,-0.043114,-0.027232,1.000000,-0.003886
environmental_investment,0.152356,0.170668,0.172389,0.004546,0.011908,-0.003886,1.000000

## Variable Engineering
Calculations of intermediate financial and environmental variables for regression models based on the Variable Engineering skill.
Tasks include:
- Calculating Control Variables: Firm Size, Leverage, Profitability, Capital Intensity.
- Green Bond & ESG Processing: Logging severely skewed variables like `emissions_intensity`.
- Lagged Variables: Computing 1-year lagged values for independent variables grouped by firm.
- Creating Country and Year dummy variables for fixed effects.

In [51]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# 1. Calculate Control Variables
final_panel['Firm_Size'] = final_panel['ln_total_assets']
final_panel['Leverage'] = final_panel['total_debt'] / final_panel['total_assets']
final_panel['Capital_Intensity'] = final_panel['capital_expenditures'] / final_panel['total_assets']

# 2. Green Bond & ESG Processing
# Assuming emissions_intensity is highly right-skewed and needs log transformation
# Replace 0 with NaN or a small number before log if appropriate
final_panel['ln_emissions_intensity'] = np.log(final_panel['emissions_intensity'].replace(0, np.nan))

# 3. Lagged Variables
# List of independent variables to create 1-year lags for
independent_vars = ['Firm_Size', 'Leverage', 'Capital_Intensity', 'return_on_assets', 
                    'return_on_equity_total', 'ln_emissions_intensity', 'environmental_investment']

for col in independent_vars:
    if col in final_panel.columns:
        final_panel[f'L1_{col}'] = final_panel.groupby('ric')[col].shift(1)

# 4. Country and Year Dummies (Fixed Effects Preparation)
final_panel = pd.get_dummies(final_panel, columns=['country', 'Year'], drop_first=True)

# Final Dataset Cleanup and Saving
final_panel.to_csv('../processed_data/final_engineered_panel_data.csv', index=False)
print("Variable Engineering Complete. Engineered dataset saved.")
print("Summary of newly created variables:")
print(final_panel[['Firm_Size', 'Leverage', 'Capital_Intensity', 'ln_emissions_intensity']].describe())

Variable Engineering Complete. Engineered dataset saved.
Summary of newly created variables:
          Firm_Size      Leverage  Capital_Intensity  ln_emissions_intensity
count  15211.000000  14067.000000       13547.000000            14782.000000
mean      10.767942      0.242795           0.044409                6.457859
std        2.781347      0.230283           0.525521                1.268286
min        1.586120      0.000000           0.000000                2.911085
25%        9.836154      0.041762           0.003918                5.626544
50%       11.030179      0.203557           0.018109                6.290652
75%       12.322647      0.393211           0.049505                7.154729
max       24.223470      4.921857          60.733325               18.187605

## Econometric Data Cleaning
Applying data cleaning techniques based on the Econometric Data Cleaning skill and the Evaluation Report fixes.

**Pipeline order (corrected):**
1. Load data & filter non-ASEAN firms / Year 2025
2. Handle missing values via forward fill (grouped by `ric`), then drop firms with <3 years of `total_assets`
3. Data type conversion (ensure numeric columns are numeric early)
4. Currency conversion to USD using `yfinance` (excludes ratios: ROA, ROE, emissions_intensity)
5. Winsorization at 1st/99th percentiles (AFTER currency conversion, in common currency)
6. Normalize ROA/ROE from percentage to decimal (divide by 100)
7. Log transform `total_assets`
8. Encode `environmental_investment` as binary (Y=1, N=0, NaN=NaN)
9. Data type verification & duplicate resolution

In [52]:
import pandas as pd
import yfinance as yf
from scipy.stats.mstats import winsorize
import numpy as np

# Load data
df = pd.read_csv('../processed_data/final_data.csv')
print(f"Original shape: {df.shape}")

# ============================================================
# 0. Filter non-ASEAN firms and Year 2025
# (Issue #7, #8, #18: "Other" country includes Korean firms
#  in non-ASEAN exchanges; Year 2025 has almost all NaN financials)
# ============================================================
df = df[df['country'] != 'Other'].copy()
print(f"Shape after removing non-ASEAN ('Other') firms: {df.shape}")

df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df = df[df['Year'] != 2025].copy()
print(f"Shape after removing Year 2025: {df.shape}")

# ============================================================
# 1. Handle Missing Values
# Forward fill slowly-changing variables, grouped by 'ric'.
# NOTE: environmental_investment is NOT forward-filled (Issue #19)
#   — it is a Y/N indicator, ffill would artificially inflate 'Y'.
# ============================================================
vars_to_ffill = [
    'total_assets', 'return_on_equity_total', 'return_on_assets',
    'emissions_intensity', 'esg_score', 'estimated_total_carbon_footprint',
    'internal_carbon_pricing', 'internal_carbon_price_per_tonne'
]
for col in vars_to_ffill:
    if col in df.columns:
        df[col] = df.groupby('ric')[col].transform(lambda x: x.ffill())

# Reduce data loss (Issue #15): keep firms with at least 3 years of
# non-null total_assets, then drop individual rows still missing it.
ta_notna_count = df.groupby('ric')['total_assets'].transform(
    lambda x: x.notna().sum()
)
df = df[ta_notna_count >= 3].copy()
df = df.dropna(subset=['total_assets']).copy()
print(f"Shape after ffill and filtering firms with <3 years of total_assets: {df.shape}")

# ============================================================
# 2. Early Data Type Conversion (Issue #9)
# Convert numeric columns from object to float BEFORE any math.
# ============================================================
numeric_cols = [
    'ask_price', 'bid_price', 'capital_expenditures', 'cash',
    'current_assets_total', 'current_liabilities_total',
    'earnings_bef_interest_tax', 'interest_expense_total',
    'long_term_debt', 'market_capitalization', 'market_value',
    'net_cash_flow_operating_actv', 'net_sales_or_revenues',
    'operating_income', 'total_assets', 'total_capital',
    'total_debt', 'total_liabilities',
    'return_on_assets', 'return_on_equity_total',
    'emissions_intensity', 'esg_score', 'estimated_total_carbon_footprint',
    'internal_carbon_pricing', 'internal_carbon_price_per_tonne',
    'employees', 'tri'
]
for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# ============================================================
# 3. Currency Conversion to USD (BEFORE winsorization)
# (Issue #16: winsorize AFTER conversion to common currency)
# (Issue #17: EXCLUDE ratios from FX conversion — ROA, ROE,
#  emissions_intensity are percentages/ratios, not currency values)
# ============================================================
currency_map = {
    'Vietnam': 'VND=X',
    'Thailand': 'THB=X',
    'Malaysia': 'MYR=X',
    'Singapore': 'SGD=X',
    'Indonesia': 'IDR=X',
    'Philippines': 'PHP=X'
}

fx_rates = {}
for country, ticker in currency_map.items():
    tk = yf.Ticker(ticker)
    hist = tk.history(period="max")
    if not hist.empty:
        hist['Year'] = hist.index.year
        yearly_avg = hist.groupby('Year')['Close'].mean()
        fx_rates[country] = yearly_avg.to_dict()

# Only MONETARY columns — explicitly exclude ratios/percentages
financial_cols_for_fx = [
    'ask_price', 'bid_price', 'capital_expenditures', 'cash',
    'current_assets_total', 'current_liabilities_total',
    'earnings_bef_interest_tax', 'interest_expense_total',
    'long_term_debt', 'market_capitalization', 'market_value',
    'net_cash_flow_operating_actv', 'net_sales_or_revenues',
    'operating_income', 'total_assets', 'total_capital',
    'total_debt', 'total_liabilities'
]
# NOTE: return_on_assets, return_on_equity_total, emissions_intensity,
#        esg_score, internal_carbon_pricing are NOT converted.

def get_fx_rate(row):
    country = row['country']
    year = row['Year']
    if country in fx_rates and year in fx_rates[country]:
        return fx_rates[country][year]
    return 1.0  # fallback (should not happen after filtering 'Other')

df['fx_rate'] = df.apply(get_fx_rate, axis=1)

for col in financial_cols_for_fx:
    if col in df.columns:
        df[col] = df[col] / df['fx_rate']

df.drop(columns=['fx_rate'], inplace=True)
print("Currency conversion to USD complete (ratios excluded).")

# ============================================================
# 4. Winsorization (AFTER currency conversion — Issue #16)
# Now all monetary values are in USD, so percentile trimming
# is statistically meaningful across countries.
# Also winsorize emissions_intensity (Issue #25).
# ============================================================
winsorize_vars = [
    'ask_price', 'bid_price', 'total_assets', 'net_sales_or_revenues',
    'cash', 'capital_expenditures', 'long_term_debt', 'total_debt',
    'market_capitalization', 'market_value', 'operating_income',
    'earnings_bef_interest_tax', 'current_assets_total',
    'current_liabilities_total', 'total_liabilities', 'total_capital',
    'emissions_intensity', 'estimated_total_carbon_footprint'
]
# Also winsorize ratios separately
ratio_winsorize_vars = ['return_on_assets', 'return_on_equity_total']

for col in winsorize_vars + ratio_winsorize_vars:
    if col in df.columns:
        mask = df[col].notna()
        if mask.sum() > 0:
            df.loc[mask, col] = winsorize(df.loc[mask, col], limits=[0.01, 0.01])

print("Winsorization complete (post-FX conversion).")

# ============================================================
# 5. Normalize ROA and ROE from percentage to decimal
# (User feedback: these are stored as percentages, divide by 100)
# ============================================================
for col in ['return_on_assets', 'return_on_equity_total']:
    if col in df.columns:
        df[col] = df[col] / 100.0

# ============================================================
# 6. Data Transformation & Normalization
# Log transform total_assets (standard in corporate finance)
# ============================================================
df['ln_total_assets'] = np.log(df['total_assets'].replace(0, np.nan))

# ============================================================
# 7. Encode environmental_investment properly (Issue #11)
# Map Y→1, N→0, keep NaN as NaN (not falsely coded as 0)
# ============================================================
if 'environmental_investment' in df.columns:
    df['environmental_investment'] = df['environmental_investment'].map({'Y': 1, 'N': 0})
    print(f"environmental_investment encoded: "
          f"1={int((df['environmental_investment']==1).sum())}, "
          f"0={int((df['environmental_investment']==0).sum())}, "
          f"NaN={int(df['environmental_investment'].isna().sum())}")

# ============================================================
# 8. Data Type Verification
# ============================================================
df['isin'] = df['isin'].astype(str)
df['ric'] = df['ric'].astype(str)
df['country'] = df['country'].astype(str)
df['company'] = df['company'].astype(str)
df['Year'] = df['Year'].astype(int)

# Treat GIC as categorical, not numeric (Issue #14)
if 'gic' in df.columns:
    df['gic'] = df['gic'].astype(str).astype('category')

# ============================================================
# 9. Duplicates Resolution
# ============================================================
df = df.sort_values(by=df.columns.tolist()).drop_duplicates(subset=['ric', 'Year'], keep='last')

print(f"\nData Cleaning Complete. Final Shape: {df.shape}")
print(f"Countries: {df['country'].unique()}")
print(f"Year range: {df['Year'].min()} - {df['Year'].max()}")
print(f"Unique firms (RICs): {df['ric'].nunique()}")

# Save the cleaned dataset for the next step
df.to_csv('../processed_data/cleaned_panel_data.csv', index=False)

Original shape: (44422, 35)
Shape after removing non-ASEAN ('Other') firms: (44400, 35)
Shape after removing Year 2025: (39827, 35)
Shape after ffill and filtering firms with <3 years of total_assets: (13688, 35)
Currency conversion to USD complete (ratios excluded).
Winsorization complete (post-FX conversion).
environmental_investment encoded: 1=0, 0=0, NaN=13688

Data Cleaning Complete. Final Shape: (13688, 36)
Countries: ['Vietnam' 'Thailand' 'Indonesia' 'Malaysia']
Year range: 2015 - 2024
Unique firms (RICs): 1463

## Variable Engineering
Calculations of intermediate financial and environmental variables for regression models.

Tasks include:
- Calculating Control Variables: Firm Size, Leverage, Profitability, Capital Intensity.
- Green Bond & ESG Processing: Log-transforming severely skewed `emissions_intensity`.
- Lagged Variables: Computing 1-year lagged values for independent variables grouped by firm.
- Creating Country and Year dummy variables for fixed effects.

**Evaluation Report fixes applied:**
- `Firm_Size` is a proper `.copy()` (Issue #26)
- `Leverage` and `Capital_Intensity` clipped to [0, 1] (Issues #24, #27)
- `gic` treated as categorical (Issue #14)
- `pd.get_dummies` no longer applied on `environmental_investment` (already binary from cleaning)

In [53]:
import pandas as pd
import numpy as np

# Load cleaned data (environmental_investment already encoded as 1/0/NaN)
df = pd.read_csv('../processed_data/cleaned_panel_data.csv')
print(f"Loaded cleaned data: {df.shape}")

# ============================================================
# 1. Calculate Control Variables
# ============================================================
# Firm_Size: proper copy, not a reference (Issue #26)
df['Firm_Size'] = df['ln_total_assets'].copy()

# Leverage: clip to [0, 1] — values > 1 indicate total_debt > total_assets,
# which is possible for distressed firms but likely data error at extreme values (Issue #24)
df['Leverage'] = (df['total_debt'] / df['total_assets']).clip(lower=0, upper=1)

# Capital_Intensity: cap at [0, 1] — CapEx/Assets > 1 is almost certainly
# a data error (Issue #27)
df['Capital_Intensity'] = (df['capital_expenditures'].abs() / df['total_assets']).clip(lower=0, upper=1)

print("Control variables calculated:")
print(df[['Firm_Size', 'Leverage', 'Capital_Intensity']].describe())

# ============================================================
# 2. Green Bond & ESG Processing
# ============================================================
# Log-transform emissions_intensity (extreme skewness = 33.5, Issue #25)
# Already winsorized in cleaning step; log calms remaining skewness
if 'emissions_intensity' in df.columns:
    df['ln_emissions_intensity'] = np.log(df['emissions_intensity'].replace(0, np.nan))

# Log-transform estimated_total_carbon_footprint if present
if 'estimated_total_carbon_footprint' in df.columns:
    df['ln_carbon_footprint'] = np.log(
        df['estimated_total_carbon_footprint'].replace(0, np.nan)
    )

# ============================================================
# 3. Lagged Variables (1-year lag grouped by firm)
# ============================================================
independent_vars = [
    'Firm_Size', 'Leverage', 'Capital_Intensity',
    'return_on_assets', 'return_on_equity_total',
    'ln_emissions_intensity', 'environmental_investment',
    'esg_score'
]

for col in independent_vars:
    if col in df.columns:
        df[f'L1_{col}'] = df.groupby('ric')[col].shift(1)

print(f"\nLagged variables created for: {[c for c in independent_vars if c in df.columns]}")

# ============================================================
# 4. GIC as categorical (Issue #14)
# ============================================================
if 'gic' in df.columns:
    df['gic'] = df['gic'].astype(str).astype('category')
    print(f"GIC categories: {df['gic'].nunique()} unique industry codes")

# ============================================================
# 5. Country and Year Dummies (Fixed Effects Preparation)
# Note: 'Other' country already filtered in cleaning. Year 2025 removed.
# environmental_investment is already 1/0/NaN — no get_dummies needed for it.
# ============================================================
df = pd.get_dummies(df, columns=['country', 'Year'], drop_first=True, dtype=int)

# ============================================================
# Final Dataset Cleanup and Saving
# ============================================================
df.to_csv('../processed_data/final_engineered_panel_data.csv', index=False)
print(f"\nVariable Engineering Complete. Final shape: {df.shape}")
print("\nSummary of key engineered variables:")
summary_cols = ['Firm_Size', 'Leverage', 'Capital_Intensity', 'ln_emissions_intensity']
summary_cols = [c for c in summary_cols if c in df.columns]
print(df[summary_cols].describe())

Loaded cleaned data: (13688, 36)
Control variables calculated:
          Firm_Size      Leverage  Capital_Intensity
count  13688.000000  13450.000000       12969.000000
mean      10.726509      0.236774           0.039592
std        2.746210      0.205643           0.064806
min        2.168593      0.000000           0.000000
25%        9.805304      0.041450           0.003930
50%       11.004245      0.204886           0.017995
75%       12.283024      0.387229           0.048775
max       16.789092      1.000000           1.000000

Lagged variables created for: ['Firm_Size', 'Leverage', 'Capital_Intensity', 'return_on_assets', 'return_on_equity_total', 'ln_emissions_intensity', 'environmental_investment']
GIC categories: 6 unique industry codes

Variable Engineering Complete. Final shape: (13688, 57)

Summary of key engineered variables:
          Firm_Size      Leverage  Capital_Intensity  ln_emissions_intensity
count  13688.000000  13450.000000       12969.000000            13308.000000
mean      10.726509      0.236774           0.039592                6.437695
std        2.746210      0.205643           0.064806                1.175411
min        2.168593      0.000000           0.000000                4.269326
25%        9.805304      0.041450           0.003930                5.605799
50%       11.004245      0.204886           0.017995                6.279637
75%       12.283024      0.387229           0.048775                7.160239
max       16.789092      1.000000           1.000000                9.618776

## Panel Data Validation
Structurally validating the firm-year panel dataset.

Tasks include:
- Setting the multi-index (`['ric', 'Year']`).
- Checking if the panel is severely unbalanced.
- Generating descriptive statistics (Table 1) including engineered variables.
- Producing a correlation matrix.
- Before/after diagnostics for key variables.

In [54]:
import pandas as pd
import numpy as np

# Load the cleaned dataset
df = pd.read_csv('../processed_data/cleaned_panel_data.csv')

# ============================================================
# 1. Set Multi-Index
# ============================================================
panel = df.set_index(['ric', 'Year']).sort_index()

# ============================================================
# 2. Panel Structure Check
# ============================================================
obs_per_firm = panel.groupby(level='ric').size()
print("=" * 60)
print("PANEL STRUCTURE CHECK")
print("=" * 60)
print(f"Total Firms (RICs): {panel.index.get_level_values('ric').nunique()}")
print(f"Total Firm-Year Observations: {len(panel)}")
print(f"Average Years per Firm: {obs_per_firm.mean():.2f}")
print(f"Temporal Range: {panel.index.get_level_values('Year').min()} to {panel.index.get_level_values('Year').max()}")
print(f"Min Years for a single firm: {obs_per_firm.min()}")
print(f"Max Years for a single firm: {obs_per_firm.max()}")

# Verify no non-ASEAN countries
if 'country' in df.columns:
    print(f"\nCountries in dataset: {sorted(df['country'].unique())}")

# ============================================================
# 3. Descriptive Statistics (Table 1)
# ============================================================
primary_vars = [
    'total_assets', 'ln_total_assets', 'total_debt',
    'return_on_assets', 'return_on_equity_total',
    'emissions_intensity', 'esg_score',
    'estimated_total_carbon_footprint',
    'net_sales_or_revenues', 'market_capitalization',
    'capital_expenditures'
]

# Filter to only existing columns
primary_vars = [c for c in primary_vars if c in df.columns]

# Ensure primary variables are numeric
for col in primary_vars:
    df[col] = pd.to_numeric(df[col], errors='coerce')

desc_stats = df[primary_vars].describe().T
desc_stats['skewness'] = df[primary_vars].skew()
desc_stats['kurtosis'] = df[primary_vars].kurt()
desc_stats['missing_pct'] = (df[primary_vars].isna().sum() / len(df) * 100).round(1)

print("\n" + "=" * 60)
print("DESCRIPTIVE STATISTICS")
print("=" * 60)
display(desc_stats)

# ============================================================
# 4. Sanity Checks on Key Variables
# ============================================================
print("\n" + "=" * 60)
print("SANITY CHECKS")
print("=" * 60)

# ROA/ROE should be in decimal range (after /100)
if 'return_on_assets' in df.columns:
    roa = df['return_on_assets'].dropna()
    print(f"ROA range: [{roa.min():.4f}, {roa.max():.4f}] (should be decimal, e.g. 0.05 = 5%)")

if 'return_on_equity_total' in df.columns:
    roe = df['return_on_equity_total'].dropna()
    print(f"ROE range: [{roe.min():.4f}, {roe.max():.4f}]")

# Check environmental_investment encoding
if 'environmental_investment' in df.columns:
    print(f"\nenvironmental_investment value counts (NaN should exist, not be 0):")
    print(df['environmental_investment'].value_counts(dropna=False))

# Check for any remaining non-ASEAN
if 'country' in df.columns:
    non_asean = df[df['country'] == 'Other']
    print(f"\nNon-ASEAN ('Other') rows remaining: {len(non_asean)} (should be 0)")

# ============================================================
# 5. Correlation Matrix
# ============================================================
corr_vars = [c for c in primary_vars if c in df.columns and df[c].notna().sum() > 100]
corr_matrix = df[corr_vars].corr(method='pearson')
print("\n" + "=" * 60)
print("PEARSON CORRELATION MATRIX")
print("=" * 60)
display(corr_matrix)

# Flag high multicollinearity
print("\nHigh correlations (|r| > 0.8):")
for i in range(len(corr_matrix)):
    for j in range(i+1, len(corr_matrix)):
        r = corr_matrix.iloc[i, j]
        if abs(r) > 0.8:
            print(f"  {corr_matrix.index[i]} ↔ {corr_matrix.columns[j]}: {r:.3f}")

============================================================
PANEL STRUCTURE CHECK
============================================================
Total Firms (RICs): 1463
Total Firm-Year Observations: 13688
Average Years per Firm: 9.36
Temporal Range: 2015 to 2024
Min Years for a single firm: 3
Max Years for a single firm: 10

Countries in dataset: ['Indonesia', 'Malaysia', 'Thailand', 'Vietnam']

============================================================
DESCRIPTIVE STATISTICS
============================================================

,count,mean,std,min,25%,50%,75%,max,skewness,kurtosis,missing_pct
total_assets,13688.0,677785.969048,2.533230e+06,8.745968,18129.658705,60128.829396,215997.842090,1.956186e+07,5.911220,37.259858,0.0
ln_total_assets,13688.0,10.726509,2.746210e+00,2.168593,9.805304,11.004245,12.283024,1.678909e+01,-0.761961,1.069171,0.0
total_debt,13450.0,212064.708780,7.992360e+05,0.000000,413.460574,8861.494785,54953.781719,5.958579e+06,5.643325,33.777641,1.7
return_on_assets,13284.0,0.053444,8.088747e-02,-0.267300,0.017000,0.049300,0.088000,3.357000e-01,-0.126834,4.051143,3.0
return_on_equity_total,13235.0,0.078456,1.996059e-01,-1.030700,0.021400,0.084300,0.155900,6.854000e-01,-1.970614,11.327167,3.3
emissions_intensity,13308.0,1384.439804,2.364927e+03,71.473469,271.999136,533.594690,1287.218149,1.504463e+04,3.532743,14.294533,2.8
net_sales_or_revenues,12800.0,258567.077079,8.540528e+05,0.000000,8617.447535,35568.904184,116853.875130,6.155568e+06,5.427276,30.921872,6.5
market_capitalization,10835.0,365445.319578,1.149975e+06,34.391679,11573.164792,43242.398478,153197.060182,8.174373e+06,5.130202,28.233882,20.8
capital_expenditures,12969.0,13713.974281,4.636293e+04,0.000000,137.329676,1028.487888,5720.509773,3.492992e+05,5.585979,33.775360,5.3

============================================================
SANITY CHECKS
============================================================
ROA range: [-0.2673, 0.3357] (should be decimal, e.g. 0.05 = 5%)
ROE range: [-1.0307, 0.6854]

environmental_investment value counts (NaN should exist, not be 0):
environmental_investment
NaN    13688
Name: count, dtype: int64

Non-ASEAN ('Other') rows remaining: 0 (should be 0)

============================================================
PEARSON CORRELATION MATRIX
============================================================

,total_assets,ln_total_assets,total_debt,return_on_assets,return_on_equity_total,emissions_intensity,net_sales_or_revenues,market_capitalization,capital_expenditures
total_assets,1.000000,0.461131,0.907405,-0.049787,0.036678,0.377051,0.750042,0.781324,0.536291
ln_total_assets,0.461131,1.000000,0.456689,0.103180,0.141192,0.061787,0.445931,0.466019,0.416664
total_debt,0.907405,0.456689,1.000000,-0.052934,0.023164,0.326454,0.769975,0.756677,0.609365
return_on_assets,-0.049787,0.103180,-0.052934,1.000000,0.824620,-0.079320,0.010958,0.081876,0.019621
return_on_equity_total,0.036678,0.141192,0.023164,0.824620,1.000000,-0.021377,0.051216,0.116761,0.051058
emissions_intensity,0.377051,0.061787,0.326454,-0.079320,-0.021377,1.000000,0.207059,0.209176,0.120215
net_sales_or_revenues,0.750042,0.445931,0.769975,0.010958,0.051216,0.207059,1.000000,0.781888,0.729509
market_capitalization,0.781324,0.466019,0.756677,0.081876,0.116761,0.209176,0.781888,1.000000,0.687795
capital_expenditures,0.536291,0.416664,0.609365,0.019621,0.051058,0.120215,0.729509,0.687795,1.000000

High correlations (|r| > 0.8):
  total_assets ↔ total_debt: 0.907
  return_on_assets ↔ return_on_equity_total: 0.825