In [32]:
import pandas as pd
import numpy as np

# Merge Panel Data

In [33]:
# 1. Load the data
df1 = pd.read_csv("../data/panel_data.csv")
df2 = pd.read_csv("../data/esg_panel_data.csv")

# 2. DROP THE EXTRA HEADER ROWS
df1 = df1[df1["Year"] != "Year"]
df2 = df2[df2["Year"] != "Year"]

# 3. NOW it is safe to convert them to integers
df1["Year"] = df1["Year"].astype(int)

# (df2's columns were renamed in your cell 12, so make sure to do that first)
df2 = df2.rename(columns={"ticker": "isin"}) 
df2["Year"] = df2["Year"].astype(int)

In [34]:
df1.head()

,company,ticker,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,net_cash_flow_operating_actv,net_sales_or_revenues,operating_income,return_on_assets,return_on_equity_total,total_assets,total_capital,total_debt,total_liabilities,tri
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,139551920.0,557407302.0,120073608.0,23.12,32.37,443321800.0,325687074.0,12154497.0,117634726.0,915.21
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.90,81063081.0,26696986.0,373711509.0,159031144.0,...,159226609.0,520269497.0,104861803.0,19.17,26.44,550731097.0,393873772.0,62680107.0,170454686.0,1292.29
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,116226295.0,559746010.0,108434020.0,14.24,21.23,745486949.0,479984306.0,186715604.0,305496890.0,1662.77
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,164716711.0,722333338.0,110365095.0,12.95,19.85,780505063.0,533398478.0,164144027.0,288917413.0,1605.27
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,77719241.0,802112862.0,74237342.0,9.90,14.14,894945037.0,558134707.0,256450459.0,383110921.0,1421.17

In [35]:
df2.head()

,company,isin,country,Year,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne
0,3-2 INVESTMENT AND,VN000000C325,Vietnam,2015,2546.068815,NaN,NaN,64828.867445,NaN,NaN
1,3-2 INVESTMENT AND,VN000000C325,Vietnam,2016,2819.725335,NaN,NaN,65675.451046,NaN,NaN
2,3-2 INVESTMENT AND,VN000000C325,Vietnam,2017,4362.532697,NaN,NaN,107555.911603,NaN,NaN
3,3-2 INVESTMENT AND,VN000000C325,Vietnam,2018,3615.604879,NaN,NaN,113458.609522,NaN,NaN
4,3-2 INVESTMENT AND,VN000000C325,Vietnam,2019,1825.212869,NaN,NaN,63036.406400,NaN,NaN

In [36]:
# load market data
vn = pd.read_csv("../data/vn-market.csv")
tl = pd.read_csv("../data/tl-market.csv")
ml = pd.read_csv("../data/ml-market.csv")
sing = pd.read_csv("../data/sing-market.csv")
pp = pd.read_csv("../data/pp-market.csv")
other = pd.read_csv("../data/other-market.csv")
indo = pd.read_csv("../data/indo-market.csv")

In [37]:
market_data = pd.concat([vn, tl, ml, sing, pp, indo], ignore_index=True)
market_data.drop("currency", axis=1, inplace=True)

other = other.reindex(columns=["name", "ric", "org_permid", "isin"])
market_data = pd.concat([market_data, other], ignore_index=True)

In [38]:
tmp1 = pd.merge(df2, market_data, on="isin", how="inner")
tmp1.drop(["name", "org_permid", "company", "country"], axis=1, inplace=True)

In [39]:
df1.columns = ['company', 'ric', 'country', 'Year', 'ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities',
       'tri']

In [40]:
df1["Year"] = df1["Year"].astype(int)
tmp1["Year"] = tmp1["Year"].astype(int)

merge_data = pd.merge(df1, tmp1, on=["ric", "Year"], how="left")
merge_data

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.660,11553.020,14506949.0,21859220.0,346329349.0,119808545.0,...,12154497.0,117634726.0,915.21,VN000000C325,2546.068815,NaN,NaN,64828.867445,NaN,NaN
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.780,15340.900,81063081.0,26696986.0,373711509.0,159031144.0,...,62680107.0,170454686.0,1292.29,VN000000C325,2819.725335,NaN,NaN,65675.451046,NaN,NaN
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.540,18939.380,65713763.0,51147987.0,393966308.0,267676461.0,...,186715604.0,305496890.0,1662.77,VN000000C325,4362.532697,NaN,NaN,107555.911603,NaN,NaN
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.260,17181.810,29890001.0,38972280.0,407136318.0,249280403.0,...,164144027.0,288917413.0,1605.27,VN000000C325,3615.604879,NaN,NaN,113458.609522,NaN,NaN
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.990,14074.990,50628247.0,67504284.0,430996731.0,337421263.0,...,256450459.0,383110921.0,1421.17,VN000000C325,1825.212869,NaN,NaN,63036.406400,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58676,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.780,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.613310,NaN,50.4,22416.960700,NaN,N
58677,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.780,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.613310,NaN,50.4,22416.960700,NaN,N
58678,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.780,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.613310,NaN,50.4,22416.960700,NaN,N
58679,ZETRIX AI BHD,ZETR.KL,Malaysia,2024,0.785,0.780,135794.0,349551.0,1377820.0,239360.0,...,1290702.0,1405445.0,9620.54,MYQ0138OO006,100.613310,NaN,50.4,22416.960700,NaN,N
58680,ZETRIX AI BHD,ZETR.KL,Malaysia,2025,0.980,0.975,NaN,NaN,NaN,NaN,...,NaN,NaN,12208.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# Reset the index so it starts from 0 cleanly
merge_data = merge_data.reset_index(drop=True)

# Drop redundant duplicate rows if the market data caused any
merge_data = merge_data.drop_duplicates(subset=["ric", "Year"])

# Verify the final count 
print("Final Cleaned Panel Rows:", len(merge_data))
merge_data.head()

Final Cleaned Panel Rows: 47007

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,total_debt,total_liabilities,tri,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,14506949.0,21859220.0,346329349.0,119808545.0,...,12154497.0,117634726.0,915.21,VN000000C325,2546.068815,NaN,NaN,64828.867445,NaN,NaN
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.90,81063081.0,26696986.0,373711509.0,159031144.0,...,62680107.0,170454686.0,1292.29,VN000000C325,2819.725335,NaN,NaN,65675.451046,NaN,NaN
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,65713763.0,51147987.0,393966308.0,267676461.0,...,186715604.0,305496890.0,1662.77,VN000000C325,4362.532697,NaN,NaN,107555.911603,NaN,NaN
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,29890001.0,38972280.0,407136318.0,249280403.0,...,164144027.0,288917413.0,1605.27,VN000000C325,3615.604879,NaN,NaN,113458.609522,NaN,NaN
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,50628247.0,67504284.0,430996731.0,337421263.0,...,256450459.0,383110921.0,1421.17,VN000000C325,1825.212869,NaN,NaN,63036.406400,NaN,NaN

In [42]:
gb = pd.read_csv("../data/greenbonds.csv")

In [43]:
gb.head()

,Exceeded the limit for the Number of Deals,Package Identifier,Master Deal Type Code,All New Issues Manager Roles Code,Manager's Role Code,Dates: Issue Date,Issuer/Borrower Name Full,Issuer/Borrower PermID,Issue Type,Transaction Status,...,Issuer/Borrower TRBC Business Sector,Issuer/Borrower TRBC Economic Sector,Lead Left Bookrunner,Managers Tier 1 & Tier 2,ECM Flag,Primary Use Of Proceeds,Issuer/Borrower Nation Region,Master Deal Type,All New Issues Manager Roles,Manager's Role
0,154084480389,3480516,D,JB|JB|JB|CM|CM|CM|CM,JB|JB|JB|CM|CM|CM|CM,8/1/2017,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
1,154084486562,3480516,D,JB|JB|JB|CM|CM|CM|CM,JB|JB|JB|CM|CM|CM|CM,8/1/2017,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
2,154084490384,9983331,D,JB|JB|JB,JB|JB|JB,3/12/2015,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Morgan Stanley &...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
3,154084593248,3319100,D,JB|JB|JB,JB|JB|JB,8/9/2016,Asian Development Bank,8.589934e+09,"Agency, Supranational, Sovereign",Live,...,Banking & Investment Services,Financials,NaN,Bank of America Merrill Lynch|Credit Agricole ...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,US Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...
4,154084594902,3319989,ED,JB|JB|JB|JB|JB,JB|JB|JB|JB|JB,8/10/2016,Greenko Investment Co,5.051761e+09,High Yield Corporate,Live,...,Banking & Investment Services,Financials,Deutsche Bank,Deutsche Bank|Investec Bank Ltd|JP Morgan & Co...,False,Green Bond Purposes,Asia Pacific Excluding Central Asia,Euro & Foreign Non Cvt Debt,Joint Book Runner|Joint Book Runner|Joint Book...,Joint Book Runner|Joint Book Runner|Joint Book...

In [44]:
gb["Year"] = pd.to_datetime(gb["Dates: Issue Date"]).dt.year
# Keep only necessary columns
gb = gb[["Issuer/Borrower PermID", "Year", "Proceeds Amount This Market"]].rename(columns={"Issuer/Borrower PermID": "org_permid"})
# Standardize org_permid to string to match market_data
gb["org_permid"] = gb["org_permid"].apply(lambda x: str(int(x)) if pd.notna(x) else np.nan)
gb.head()

   org_permid  Year  Proceeds Amount This Market
0  8589934162  2017                     495.8600
1  8589934162  2017                     746.4825
2  8589934162  2015                     496.4700
3  8589934162  2016                     798.2320
4  5051761072  2016                     500.0000

In [45]:
market_data["org_permid_str"] = pd.to_numeric(market_data["org_permid"], errors='coerce')
market_data["org_permid_str"] = market_data["org_permid_str"].apply(lambda x: str(int(x)) if pd.notna(x) else np.nan)
# Map PermID to RIC
gb_mapped = pd.merge(gb, market_data[["org_permid_str", "ric"]].dropna(), left_on="org_permid", right_on="org_permid_str", how="inner")
gb_mapped.head()

   org_permid  Year  Proceeds Amount This Market org_permid_str       ric
0  4295888106  2017                        500.0     4295888106   DBSM.SI
1  4295888106  2017                        500.0     4295888106    DBSM.F
2  4295888106  2017                        500.0     4295888106  DBSDF.PK
3  4295888106  2017                        500.0     4295888106  DBSDY.PK
4  4295888106  2017                        500.0     4295888106   DEVGy.F

In [46]:
gb_agg = gb_mapped.groupby(["ric", "Year"], as_index=False).agg(
    green_bond_proceeds=("Proceeds Amount This Market", "sum")
)
gb_agg["green_bond_issue"] = 1
gb_agg.head()

         ric  Year  green_bond_proceeds  green_bond_issue
0  009830.KS  2021           152.832755                 1
1   ACDSF.PK  2020           511.413086                 1
2    ALCO.PS  2020           118.319858                 1
3   ALCPD.PS  2020            59.159929                 1
4   ALCPF.PS  2020            59.159929                 1

In [47]:
final_panel = pd.merge(merge_data, gb_agg, on=["ric", "Year"], how="left")
# Fill missing values from the merge with 0 (since no issuance = 0)
final_panel["green_bond_issue"] = final_panel["green_bond_issue"].fillna(0)
final_panel["green_bond_proceeds"] = final_panel["green_bond_proceeds"].fillna(0)
# Create the cumulative Green Bond dummy (1 for the year of issue and all years after)
final_panel = final_panel.sort_values(by=["ric", "Year"])
final_panel["green_bond_active"] = final_panel.groupby("ric")["green_bond_issue"].cumsum().clip(upper=1)
print(final_panel.shape)
final_panel.head()

(47007, 36)

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active
13824,9F INC,0,Malaysia,2016,NaN,NaN,3019.0,199371.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13825,9F INC,0,Malaysia,2017,NaN,NaN,7081.0,580724.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13826,9F INC,0,Malaysia,2018,NaN,NaN,7336.0,795040.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13827,9F INC,0,Malaysia,2019,NaN,NaN,8217.0,690732.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13828,9F INC,0,Malaysia,2020,176.0,163.86,0.0,477619.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [48]:
final_panel = final_panel.sort_index()

In [49]:
final_panel

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,isin,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,1.450695e+07,2.185922e+07,3.463293e+08,1.198085e+08,...,VN000000C325,2546.068815,NaN,NaN,6.482887e+04,NaN,NaN,0.000000,0.0,0.0
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.90,8.106308e+07,2.669699e+07,3.737115e+08,1.590311e+08,...,VN000000C325,2819.725335,NaN,NaN,6.567545e+04,NaN,NaN,0.000000,0.0,0.0
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,6.571376e+07,5.114799e+07,3.939663e+08,2.676765e+08,...,VN000000C325,4362.532697,NaN,NaN,1.075559e+05,NaN,NaN,0.000000,0.0,0.0
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,2.989000e+07,3.897228e+07,4.071363e+08,2.492804e+08,...,VN000000C325,3615.604879,NaN,NaN,1.134586e+05,NaN,NaN,0.000000,0.0,0.0
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,5.062825e+07,6.750428e+07,4.309967e+08,3.374213e+08,...,VN000000C325,1825.212869,NaN,NaN,6.303641e+04,NaN,NaN,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47002,HANWHA SOLUTIONS,009830.KS,Other,2021,52523.20,52467.56,8.126709e+08,1.651530e+09,6.159820e+09,5.789061e+09,...,KR7009830001,4885.615603,Y,64.46,4.582102e+07,NaN,N,152.832755,1.0,1.0
47003,HANWHA SOLUTIONS,009830.KS,Other,2022,37111.20,37055.56,9.029231e+08,2.616168e+09,8.642576e+09,6.810183e+09,...,KR7009830001,2601.252310,Y,61.56,2.653609e+07,NaN,N,0.000000,0.0,1.0
47004,HANWHA SOLUTIONS,009830.KS,Other,2023,46291.63,46235.99,2.390483e+09,1.958055e+09,8.708395e+09,7.689705e+09,...,KR7009830001,2587.190321,Y,68.58,2.593030e+07,NaN,N,0.000000,0.0,1.0
47005,HANWHA SOLUTIONS,009830.KS,Other,2024,26950.00,26900.00,3.397574e+09,2.184381e+09,1.088267e+10,1.170755e+10,...,KR7009830001,1634.181961,Y,73.43,1.486943e+07,NaN,NaN,0.000000,0.0,1.0
47006,HANWHA SOLUTIONS,009830.KS,Other,2025,20200.00,20150.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,1.0

In [50]:
# 1. Load the Series Data
series_df = pd.read_csv("../data/series_data.csv")

# 2. We only need the 'ticker' (which is the ric) and 'gic' columns
# (You already have the 'country' column in your final_panel)
series_df = series_df[['ticker', 'gic']]

# 3. Rename 'ticker' to 'ric' so it perfectly matches the final_panel column name
series_df = series_df.rename(columns={'ticker': 'ric'})

# 4. Merge the GIC codes back into the master panel!
final_panel = pd.merge(final_panel, series_df, on="ric", how="left")

# Print to check the output
print(final_panel.shape)

# (Optional: If you appended multiple times, the series data might have duplicates too)
# Run this just to be perfectly safe, then save:
final_panel = final_panel.drop_duplicates(subset=["ric", "Year"])

(47453, 37)

In [51]:
# final_panel.to_csv("../processed_data/final_data.csv")

# Data Processing

In [52]:
final_panel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47007 entries, 0 to 47452
Data columns (total 37 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   company                           47007 non-null  object
 1   ric                               47007 non-null  object
 2   country                           47007 non-null  object
 3   Year                              47007 non-null  int64
 4   ask_price                         32937 non-null  float64
 5   bid_price                         32126 non-null  float64
 6   capital_expenditures              37251 non-null  float64
 7   cash                              36475 non-null  float64
 8   current_assets_total              32982 non-null  float64
 9   current_liabilities_total         33001 non-null  float64
 10  earnings_bef_interest_tax         36408 non-null  float64
 11  employees                         16746 non-null  float64
 12  interest_expense_total            4067 non-null   float64
 13  long_term_debt                    37096 non-null  float64
 14  market_capitalization             36393 non-null  float64
 15  market_value                      36853 non-null  float64
 16  net_cash_flow_operating_actv      38201 non-null  float64
 17  net_sales_or_revenues             37858 non-null  float64
 18  operating_income                  37822 non-null  float64
 19  return_on_assets                  36846 non-null  float64
 20  return_on_equity_total            36286 non-null  float64
 21  total_assets                      38320 non-null  float64
 22  total_capital                     37590 non-null  float64
 23  total_debt                        37924 non-null  float64
 24  total_liabilities                 37814 non-null  float64
 25  tri                               37351 non-null  float64
 26  isin                              39598 non-null  object
 27  emissions_intensity               39142 non-null  float64
 28  environmental_investment          5524 non-null   object
 29  esg_score                         7019 non-null   float64
 30  estimated_total_carbon_footprint  39142 non-null  float64
 31  internal_carbon_pricing           1410 non-null   object
 32  internal_carbon_price_per_tonne   6864 non-null   object
 33  green_bond_proceeds               47007 non-null  float64
 34  green_bond_issue                  47007 non-null  float64
 35  green_bond_active                 47007 non-null  float64
 36  gic                               45074 non-null  float64
dtypes: float64(29), int64(1), object(7)
memory usage: 13.6+ MB

In [53]:
final_panel.columns

Index(['company', 'ric', 'country', 'Year', 'ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities',
       'tri', 'isin', 'emissions_intensity', 'environmental_investment',
       'esg_score', 'estimated_total_carbon_footprint',
       'internal_carbon_pricing', 'internal_carbon_price_per_tonne',
       'green_bond_proceeds', 'green_bond_issue', 'green_bond_active', 'gic'],
      dtype='object')

In [54]:
numeric_attributes = ['ask_price', 'bid_price',
       'capital_expenditures', 'cash', 'current_assets_total',
       'current_liabilities_total', 'earnings_bef_interest_tax', 'employees',
       'interest_expense_total', 'long_term_debt', 'market_capitalization',
       'market_value', 'net_cash_flow_operating_actv', 'net_sales_or_revenues',
       'operating_income', 'return_on_assets', 'return_on_equity_total',
       'total_assets', 'total_capital', 'total_debt', 'total_liabilities', "tri", "emissions_intensity", "green_bond_proceeds", "green_bond_issue", "green_bond_active", "gic"]

encoded_attributes = ["environmental_investment"]

In [55]:
final_panel[numeric_attributes] = final_panel[numeric_attributes].astype(float)
final_panel["internal_carbon_pricing"] = pd.to_numeric(final_panel["internal_carbon_pricing"], errors='coerce')
final_panel["internal_carbon_price_per_tonne"] = pd.to_numeric(final_panel["internal_carbon_price_per_tonne"], errors='coerce')

In [56]:
final_panel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47007 entries, 0 to 47452
Data columns (total 37 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   company                           47007 non-null  object
 1   ric                               47007 non-null  object
 2   country                           47007 non-null  object
 3   Year                              47007 non-null  int64
 4   ask_price                         32937 non-null  float64
 5   bid_price                         32126 non-null  float64
 6   capital_expenditures              37251 non-null  float64
 7   cash                              36475 non-null  float64
 8   current_assets_total              32982 non-null  float64
 9   current_liabilities_total         33001 non-null  float64
 10  earnings_bef_interest_tax         36408 non-null  float64
 11  employees                         16746 non-null  float64
 12  interest_expense_total            4067 non-null   float64
 13  long_term_debt                    37096 non-null  float64
 14  market_capitalization             36393 non-null  float64
 15  market_value                      36853 non-null  float64
 16  net_cash_flow_operating_actv      38201 non-null  float64
 17  net_sales_or_revenues             37858 non-null  float64
 18  operating_income                  37822 non-null  float64
 19  return_on_assets                  36846 non-null  float64
 20  return_on_equity_total            36286 non-null  float64
 21  total_assets                      38320 non-null  float64
 22  total_capital                     37590 non-null  float64
 23  total_debt                        37924 non-null  float64
 24  total_liabilities                 37814 non-null  float64
 25  tri                               37351 non-null  float64
 26  isin                              39598 non-null  object
 27  emissions_intensity               39142 non-null  float64
 28  environmental_investment          5524 non-null   object
 29  esg_score                         7019 non-null   float64
 30  estimated_total_carbon_footprint  39142 non-null  float64
 31  internal_carbon_pricing           179 non-null    float64
 32  internal_carbon_price_per_tonne   0 non-null      float64
 33  green_bond_proceeds               47007 non-null  float64
 34  green_bond_issue                  47007 non-null  float64
 35  green_bond_active                 47007 non-null  float64
 36  gic                               45074 non-null  float64
dtypes: float64(31), int64(1), object(5)
memory usage: 13.6+ MB

In [57]:
final_panel

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,emissions_intensity,environmental_investment,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active,gic
0,3-2 INVESTMENT,C32.HM,Vietnam,2015,11666.66,11553.02,1.450695e+07,2.185922e+07,3.463293e+08,1.198085e+08,...,2546.068815,NaN,NaN,6.482887e+04,NaN,NaN,0.000000,0.0,0.0,1.0
1,3-2 INVESTMENT,C32.HM,Vietnam,2016,15378.78,15340.90,8.106308e+07,2.669699e+07,3.737115e+08,1.590311e+08,...,2819.725335,NaN,NaN,6.567545e+04,NaN,NaN,0.000000,0.0,0.0,1.0
2,3-2 INVESTMENT,C32.HM,Vietnam,2017,19204.54,18939.38,6.571376e+07,5.114799e+07,3.939663e+08,2.676765e+08,...,4362.532697,NaN,NaN,1.075559e+05,NaN,NaN,0.000000,0.0,0.0,1.0
3,3-2 INVESTMENT,C32.HM,Vietnam,2018,17227.26,17181.81,2.989000e+07,3.897228e+07,4.071363e+08,2.492804e+08,...,3615.604879,NaN,NaN,1.134586e+05,NaN,NaN,0.000000,0.0,0.0,1.0
4,3-2 INVESTMENT,C32.HM,Vietnam,2019,14099.99,14074.99,5.062825e+07,6.750428e+07,4.309967e+08,3.374213e+08,...,1825.212869,NaN,NaN,6.303641e+04,NaN,NaN,0.000000,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47448,HANWHA SOLUTIONS,009830.KS,Other,2021,52523.20,52467.56,8.126709e+08,1.651530e+09,6.159820e+09,5.789061e+09,...,4885.615603,Y,64.46,4.582102e+07,NaN,NaN,152.832755,1.0,1.0,1.0
47449,HANWHA SOLUTIONS,009830.KS,Other,2022,37111.20,37055.56,9.029231e+08,2.616168e+09,8.642576e+09,6.810183e+09,...,2601.252310,Y,61.56,2.653609e+07,NaN,NaN,0.000000,0.0,1.0,1.0
47450,HANWHA SOLUTIONS,009830.KS,Other,2023,46291.63,46235.99,2.390483e+09,1.958055e+09,8.708395e+09,7.689705e+09,...,2587.190321,Y,68.58,2.593030e+07,NaN,NaN,0.000000,0.0,1.0,1.0
47451,HANWHA SOLUTIONS,009830.KS,Other,2024,26950.00,26900.00,3.397574e+09,2.184381e+09,1.088267e+10,1.170755e+10,...,1634.181961,Y,73.43,1.486943e+07,NaN,NaN,0.000000,0.0,1.0,1.0
47452,HANWHA SOLUTIONS,009830.KS,Other,2025,20200.00,20150.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,1.0,1.0

## Econometric Data Cleaning
Applying data cleaning techniques based on the Econometric Data Cleaning skill and the Evaluation Report fixes.

**Pipeline order (corrected):**
1. Load data & filter non-ASEAN firms / Year 2025
2. Handle missing values via forward fill (grouped by `ric`), then drop firms with <3 years of `total_assets`
3. Data type conversion (ensure numeric columns are numeric early)
4. Currency conversion to USD using `yfinance` (excludes ratios: ROA, ROE, emissions_intensity)
5. Winsorization at 1st/99th percentiles (AFTER currency conversion, in common currency)
6. Normalize ROA/ROE from percentage to decimal (divide by 100)
7. Log transform `total_assets`
8. Encode `environmental_investment` as binary (Y=1, N=0, NaN=NaN)
9. Data type verification & duplicate resolution

> **⚠️ Source Data Limitation: Singapore, Philippines, and Malaysia**
>
> The Datastream financial data for these three countries has <1% coverage for key variables like `total_assets`, `total_debt`, `net_sales_or_revenues`, etc.:
> - **Singapore**: 33/9,053 rows (0.4%) have `total_assets`
> - **Philippines**: 66/11,170 rows (0.6%) have `total_assets`
> - **Malaysia**: 66/10,105 rows (0.7%) have `total_assets`
>
> In contrast, Thailand (77.6%), Vietnam (82.7%), and Indonesia (67.1%) have robust financial data. This is an **upstream data extraction limitation** from the Datastream source, not a processing error.
>
> After cleaning (forward-fill + requiring ≥3 years of `total_assets`), Singapore and Philippines are fully dropped, and Malaysia retains only 16 observations. The ESG data for these countries is actually rich (~98% emissions coverage), but without corresponding financial data, they cannot be included in the panel.
>
> **Implication**: The effective sample covers **Thailand, Vietnam, and Indonesia** (with minimal Malaysia). This should be acknowledged in the methodology section.

In [ ]:
import pandas as pd
import yfinance as yf
from scipy.stats.mstats import winsorize
import numpy as np

# Load data

# ============================================================
# 0. Filter non-ASEAN firms and Year 2025
# (Issue #7, #8, #18: "Other" country includes Korean firms
#  in non-ASEAN exchanges; Year 2025 has almost all NaN financials)
# ============================================================
final_panel = final_panel[final_panel['country'] != 'Other'].copy()
print(f"Shape after removing non-ASEAN ('Other') firms: {final_panel.shape}")

final_panel['Year'] = pd.to_numeric(final_panel['Year'], errors='coerce')
final_panel = final_panel[final_panel['Year'] != 2025].copy()
print(f"Shape after removing Year 2025: {final_panel.shape}")

# ============================================================
# 1. Handle Missing Values
# Forward fill slowly-changing variables, grouped by 'ric'.
# NOTE: environmental_investment is NOT forward-filled (Issue #19)
#   — it is a Y/N indicator, ffill would artificially inflate 'Y'.
# ============================================================
# Financial variables: unlimited forward fill (slowly-changing)
financial_ffill_vars = [
    'total_assets', 'return_on_equity_total', 'return_on_assets',
    'internal_carbon_pricing', 'internal_carbon_price_per_tonne'
]
for col in financial_ffill_vars:
    if col in final_panel.columns:
        final_panel[col] = final_panel.groupby('ric')[col].transform(lambda x: x.ffill())

# Environmental/ESG variables: limit ffill to 1 year (Issue L from eval v3)
# These change year-over-year; unlimited ffill creates artificial stability
# that biases DID analysis on green bond timing effects
esg_ffill_vars = [
    'emissions_intensity', 'esg_score', 'estimated_total_carbon_footprint'
]
for col in esg_ffill_vars:
    if col in final_panel.columns:
        final_panel[col] = final_panel.groupby('ric')[col].transform(lambda x: x.ffill(limit=1))

# Reduce data loss (Issue #15): keep firms with at least 3 years of
# non-null total_assets, then drop individual rows still missing it.
ta_notna_count = final_panel.groupby('ric')['total_assets'].transform(
    lambda x: x.notna().sum()
)
final_panel = final_panel[ta_notna_count >= 3].copy()
final_panel = final_panel.dropna(subset=['total_assets']).copy()
print(f"Shape after ffill and filtering firms with <3 years of total_assets: {final_panel.shape}")

# ============================================================
# 2. Early Data Type Conversion (Issue #9)
# Convert numeric columns from object to float BEFORE any math.
# ============================================================
numeric_cols = [
    'ask_price', 'bid_price', 'capital_expenditures', 'cash',
    'current_assets_total', 'current_liabilities_total',
    'earnings_bef_interest_tax', 'interest_expense_total',
    'long_term_debt', 'market_capitalization', 'market_value',
    'net_cash_flow_operating_actv', 'net_sales_or_revenues',
    'operating_income', 'total_assets', 'total_capital',
    'total_debt', 'total_liabilities',
    'return_on_assets', 'return_on_equity_total',
    'emissions_intensity', 'esg_score', 'estimated_total_carbon_footprint',
    'internal_carbon_pricing', 'internal_carbon_price_per_tonne',
    'employees', 'tri'
]
for col in numeric_cols:
    if col in final_panel.columns:
        final_panel[col] = pd.to_numeric(final_panel[col], errors='coerce')

# ============================================================
# 3. Currency Conversion to USD (BEFORE winsorization)
# (Issue #16: winsorize AFTER conversion to common currency)
# (Issue #17: EXCLUDE ratios from FX conversion — ROA, ROE,
#  emissions_intensity are percentages/ratios, not currency values)
# ============================================================
currency_map = {
    'Vietnam': 'VND=X',
    'Thailand': 'THB=X',
    'Malaysia': 'MYR=X',
    'Singapore': 'SGD=X',
    'Indonesia': 'IDR=X',
    'Philippines': 'PHP=X'
}

fx_rates = {}
for country, ticker in currency_map.items():
    tk = yf.Ticker(ticker)
    hist = tk.history(period="max")
    if not hist.empty:
        hist['Year'] = hist.index.year
        yearly_avg = hist.groupby('Year')['Close'].mean()
        fx_rates[country] = yearly_avg.to_dict()

# Only MONETARY columns — explicitly exclude ratios/percentages
financial_cols_for_fx = [
    'ask_price', 'bid_price', 'capital_expenditures', 'cash',
    'current_assets_total', 'current_liabilities_total',
    'earnings_bef_interest_tax', 'interest_expense_total',
    'long_term_debt', 'market_capitalization', 'market_value',
    'net_cash_flow_operating_actv', 'net_sales_or_revenues',
    'operating_income', 'total_assets', 'total_capital',
    'total_debt', 'total_liabilities'
]
# NOTE: return_on_assets, return_on_equity_total, emissions_intensity,
#        esg_score, internal_carbon_pricing are NOT converted.

def get_fx_rate(row):
    country = row['country']
    year = row['Year']
    if country in fx_rates and year in fx_rates[country]:
        return fx_rates[country][year]
    return 1.0  # fallback (should not happen after filtering 'Other')

final_panel['fx_rate'] = final_panel.apply(get_fx_rate, axis=1)

for col in financial_cols_for_fx:
    if col in final_panel.columns:
        final_panel[col] = final_panel[col] / final_panel['fx_rate']

final_panel.drop(columns=['fx_rate'], inplace=True)
print("Currency conversion to USD complete (ratios excluded).")

# ============================================================
# 4. Winsorization (AFTER currency conversion — Issue #16)
# Now all monetary values are in USD, so percentile trimming
# is statistically meaningful across countries.
# Also winsorize emissions_intensity (Issue #25).
# ============================================================
winsorize_vars = [
    'ask_price', 'bid_price', 'total_assets', 'net_sales_or_revenues',
    'cash', 'capital_expenditures', 'long_term_debt', 'total_debt',
    'market_capitalization', 'market_value', 'operating_income',
    'earnings_bef_interest_tax', 'current_assets_total',
    'current_liabilities_total', 'total_liabilities', 'total_capital',
    'emissions_intensity', 'estimated_total_carbon_footprint'
]
# Also winsorize ratios separately
ratio_winsorize_vars = ['return_on_assets', 'return_on_equity_total']

for col in winsorize_vars + ratio_winsorize_vars:
    if col in final_panel.columns:
        mask = final_panel[col].notna()
        if mask.sum() > 0:
            final_panel.loc[mask, col] = winsorize(final_panel.loc[mask, col], limits=[0.01, 0.01])

print("Winsorization complete (post-FX conversion).")

# ============================================================
# 5. Normalize ROA and ROE from percentage to decimal
# (User feedback: these are stored as percentages, divide by 100)
# ============================================================
for col in ['return_on_assets', 'return_on_equity_total']:
    if col in final_panel.columns:
        final_panel[col] = final_panel[col] / 100.0

# ============================================================
# 6. Data Transformation & Normalization
# Log transform total_assets (standard in corporate finance)
# ============================================================
final_panel['ln_total_assets'] = np.log(final_panel['total_assets'].replace(0, np.nan))

# ============================================================
# 7. Encode environmental_investment properly (Issue #11)
# Map Y→1, N→0, keep NaN as NaN (not falsely coded as 0)
# ============================================================
final_panel = pd.get_dummies(final_panel, columns=encoded_attributes, drop_first=True)
final_panel.columns = final_panel.columns.str.strip()

final_panel = final_panel.rename(columns={
    "environmental_investment_Y": "environmental_investment"
    })

print(f"environmental_investment encoded: "
        f"1={int((final_panel['environmental_investment']==1).sum())}, "
        f"0={int((final_panel['environmental_investment']==0).sum())}, "
        f"NaN={int(final_panel['environmental_investment'].isna().sum())}")

# ============================================================
# 8. Data Type Verification
# ============================================================
final_panel['isin'] = final_panel['isin'].astype(str)
final_panel['ric'] = final_panel['ric'].astype(str)
final_panel['country'] = final_panel['country'].astype(str)
final_panel['company'] = final_panel['company'].astype(str)
final_panel['Year'] = final_panel['Year'].astype(int)

# Treat GIC as categorical, not numeric (Issue #14)
if 'gic' in final_panel.columns:
    final_panel['gic'] = final_panel['gic'].astype(str).astype('category')

# ============================================================
# 9. Duplicates Resolution
# ============================================================
final_panel = final_panel.sort_values(by=final_panel.columns.tolist()).drop_duplicates(subset=['ric', 'Year'], keep='last')

print(f"\nData Cleaning Complete. Final Shape: {final_panel.shape}")
print(f"Countries: {final_panel['country'].unique()}")
print(f"Year range: {final_panel['Year'].min()} - {final_panel['Year'].max()}")
print(f"Unique firms (RICs): {final_panel['ric'].nunique()}")

# Save the cleaned dataset for the next step
final_panel.to_csv('../processed_data/cleaned_panel_data.csv', index=False)

Shape after removing non-ASEAN ('Other') firms: (46985, 37)
Shape after removing Year 2025: (42250, 37)

Shape after ffill and filtering firms with <3 years of total_assets: (37211, 37)
Currency conversion to USD complete (ratios excluded).
Winsorization complete (post-FX conversion).
environmental_investment encoded: 1=821, 0=36390, NaN=0

Data Cleaning Complete. Final Shape: (37211, 38)
Countries: ['Singapore' 'Thailand' 'Vietnam' 'Malaysia' 'Philippines' 'Indonesia']
Year range: 2015 - 2024
Unique firms (RICs): 4026

In [59]:
final_panel

,company,ric,country,Year,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,...,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,internal_carbon_price_per_tonne,green_bond_proceeds,green_bond_issue,green_bond_active,gic,ln_total_assets,environmental_investment
24062,17LIVE GROUP LTD,LIVE.SI,Singapore,2021,NaN,NaN,NaN,14.646189,365.918028,989.207802,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,7.183082,False
24063,17LIVE GROUP LTD,LIVE.SI,Singapore,2022,NaN,NaN,0.000000,2652.516636,156050.955460,130283.029291,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,11.957938,False
24064,17LIVE GROUP LTD,LIVE.SI,Singapore,2023,3.121111,3.080151,1093.989961,101182.528245,123436.175629,68875.195042,...,NaN,27162.948376,NaN,NaN,0.0,0.0,0.0,1.0,11.969733,False
24065,17LIVE GROUP LTD,LIVE.SI,Singapore,2024,1.092733,1.070280,596.512731,81230.514042,98487.470168,46639.511688,...,NaN,18005.509579,NaN,NaN,0.0,0.0,0.0,1.0,11.799138,False
4365,2S METAL,2S.BK,Thailand,2015,0.068098,0.066929,851.314989,1804.601894,21421.116952,12176.569181,...,NaN,556564.302595,NaN,NaN,0.0,0.0,0.0,1.0,10.473907,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34361,ZIXIN GROUP,ZIXI.SI,Singapore,2020,0.015953,0.014502,1408.904635,10354.687692,30386.802691,5405.756075,...,NaN,28311.750038,NaN,NaN,0.0,0.0,0.0,1.0,11.124767,False
34362,ZIXIN GROUP,ZIXI.SI,Singapore,2021,0.026796,0.026051,699.665413,30002.248368,47091.203918,9417.943054,...,NaN,27955.187230,NaN,NaN,0.0,0.0,0.0,1.0,11.259739,False
34363,ZIXIN GROUP,ZIXI.SI,Singapore,2022,0.015232,0.014507,3170.399293,30616.729481,48203.705381,8467.453980,...,NaN,31624.673243,NaN,NaN,0.0,0.0,0.0,1.0,11.377141,False
34364,ZIXIN GROUP,ZIXI.SI,Singapore,2023,0.014150,0.012660,4908.432833,29653.904864,41217.132992,12174.641169,...,NaN,23705.796241,NaN,NaN,0.0,0.0,0.0,1.0,11.344905,False
34365,ZIXIN GROUP,ZIXI.SI,Singapore,2024,0.017214,0.016466,6923.888672,21832.964703,38514.364631,12918.953883,...,NaN,34181.458598,NaN,NaN,0.0,0.0,0.0,1.0,11.358419,False

## Variable Engineering
Calculations of intermediate financial and environmental variables for regression models.

Tasks include:
- Calculating Control Variables: Firm Size, Leverage, Profitability, Capital Intensity.
- Green Bond & ESG Processing: Log-transforming severely skewed `emissions_intensity`.
- Lagged Variables: Computing 1-year lagged values for independent variables grouped by firm.
- Creating Country and Year dummy variables for fixed effects.

**Evaluation Report fixes applied:**
- `Firm_Size` is a proper `.copy()` (Issue #26)
- `Leverage` and `Capital_Intensity` clipped to [0, 1] (Issues #24, #27)
- `gic` treated as categorical (Issue #14)
- `pd.get_dummies` no longer applied on `environmental_investment` (already binary from cleaning)

In [60]:
import pandas as pd
import numpy as np

# Load cleaned data (environmental_investment already encoded as 1/0/NaN)
# final_panel = pd.read_csv('../processed_data/cleaned_panel_data.csv')
# print(f"Loaded cleaned data: {final_panel.shape}")

# ============================================================
# 1. Calculate Control Variables
# ============================================================
# Firm_Size: proper copy, not a reference (Issue #26)
final_panel['Firm_Size'] = final_panel['ln_total_assets'].copy()

# Leverage: clip to [0, 1.5] — values > 1 can occur for distressed firms
# where debt exceeds assets, which is legitimate in ASEAN restructuring cases.
# Only extreme values (> 1.5) are treated as data errors (Issue #24, relaxed in eval v3)
final_panel['Leverage'] = (final_panel['total_debt'] / final_panel['total_assets']).clip(lower=0, upper=1.5)

# Capital_Intensity: cap at [0, 1] — CapEx/Assets > 1 is almost certainly
# a data error (Issue #27)
final_panel['Capital_Intensity'] = (final_panel['capital_expenditures'].abs() / final_panel['total_assets']).clip(lower=0, upper=1)

print("Control variables calculated:")
print(final_panel[['Firm_Size', 'Leverage', 'Capital_Intensity']].describe())

# ============================================================
# 2. Green Bond & ESG Processing
# ============================================================
# Log-transform emissions_intensity (extreme skewness = 33.5, Issue #25)
# Already winsorized in cleaning step; log calms remaining skewness
if 'emissions_intensity' in final_panel.columns:
    final_panel['ln_emissions_intensity'] = np.log(final_panel['emissions_intensity'].replace(0, np.nan))

# Log-transform estimated_total_carbon_footprint if present
if 'estimated_total_carbon_footprint' in final_panel.columns:
    final_panel['ln_carbon_footprint'] = np.log(
        final_panel['estimated_total_carbon_footprint'].replace(0, np.nan)
    )

# ============================================================
# 3. Lagged Variables (1-year lag grouped by firm)
# ============================================================
independent_vars = [
    'Firm_Size', 'Leverage', 'Capital_Intensity',
    'return_on_assets', 'return_on_equity_total',
    'ln_emissions_intensity', 'environmental_investment',
    'esg_score'
]

for col in independent_vars:
    if col in final_panel.columns:
        final_panel[f'L1_{col}'] = final_panel.groupby('ric')[col].shift(1)

print(f"\nLagged variables created for: {[c for c in independent_vars if c in final_panel.columns]}")

# ============================================================
# 4. GIC as categorical (Issue #14)
# ============================================================
if 'gic' in final_panel.columns:
    final_panel['gic'] = final_panel['gic'].astype(str).astype('category')
    print(f"GIC categories: {final_panel['gic'].nunique()} unique industry codes")

# ============================================================
# 5. Country and Year Dummies (Fixed Effects Preparation)
# Note: 'Other' country already filtered in cleaning. Year 2025 removed.
# environmental_investment is already 1/0/NaN — no get_dummies needed for it.
# ============================================================
final_panel = pd.get_dummies(final_panel, columns=['country', 'Year'], drop_first=True, dtype=int)

# ============================================================
# Final Dataset Cleanup and Saving
# ============================================================
final_panel.to_csv('../processed_data/final_engineered_panel_data.csv', index=False)
print(f"\nVariable Engineering Complete. Final shape: {final_panel.shape}")
print("\nSummary of key engineered variables:")
summary_cols = ['Firm_Size', 'Leverage', 'Capital_Intensity', 'ln_emissions_intensity']
summary_cols = [c for c in summary_cols if c in final_panel.columns]
print(final_panel[summary_cols].describe())

Control variables calculated:
          Firm_Size      Leverage  Capital_Intensity
count  37211.000000  36397.000000       35763.000000
mean      11.997583      0.233237           0.038099
std        2.158051      0.205331           0.067881
min        7.183082      0.000000           0.000000
25%       10.525907      0.051070           0.003788
50%       11.720693      0.199821           0.015810
75%       13.211649      0.368326           0.044616
max       18.556344      1.000000           1.000000

Lagged variables created for: ['Firm_Size', 'Leverage', 'Capital_Intensity', 'return_on_assets', 'return_on_equity_total', 'ln_emissions_intensity', 'environmental_investment', 'esg_score']
GIC categories: 7 unique industry codes

Variable Engineering Complete. Final shape: (37211, 63)

Summary of key engineered variables:
          Firm_Size      Leverage  Capital_Intensity  ln_emissions_intensity
count  37211.000000  36397.000000       35763.000000            35661.000000
mean      11.997583      0.233237           0.038099                6.418930
std        2.158051      0.205331           0.067881                1.147130
min        7.183082      0.000000           0.000000                4.274766
25%       10.525907      0.051070           0.003788                5.646251
50%       11.720693      0.199821           0.015810                6.241778
75%       13.211649      0.368326           0.044616                7.048985
max       18.556344      1.000000           1.000000                9.923965

## Panel Data Validation
Structurally validating the firm-year panel dataset.

Tasks include:
- Setting the multi-index (`['ric', 'Year']`).
- Checking if the panel is severely unbalanced.
- Generating descriptive statistics (Table 1) including engineered variables.
- Producing a correlation matrix.
- Before/after diagnostics for key variables.

In [61]:
final_panel

,company,ric,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,earnings_bef_interest_tax,employees,...,country_Vietnam,Year_2016,Year_2017,Year_2018,Year_2019,Year_2020,Year_2021,Year_2022,Year_2023,Year_2024
24062,17LIVE GROUP LTD,LIVE.SI,NaN,NaN,NaN,14.646189,365.918028,989.207802,NaN,964.0,...,0,0,0,0,0,0,1,0,0,0
24063,17LIVE GROUP LTD,LIVE.SI,NaN,NaN,0.000000,2652.516636,156050.955460,130283.029291,8159.190494,900.0,...,0,0,0,0,0,0,0,1,0,0
24064,17LIVE GROUP LTD,LIVE.SI,3.121111,3.080151,1093.989961,101182.528245,123436.175629,68875.195042,-105572.922918,NaN,...,0,0,0,0,0,0,0,0,1,0
24065,17LIVE GROUP LTD,LIVE.SI,1.092733,1.070280,596.512731,81230.514042,98487.470168,46639.511688,-865.953864,620.0,...,0,0,0,0,0,0,0,0,0,1
4365,2S METAL,2S.BK,0.068098,0.066929,851.314989,1804.601894,21421.116952,12176.569181,1821.378013,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34361,ZIXIN GROUP,ZIXI.SI,0.015953,0.014502,1408.904635,10354.687692,30386.802691,5405.756075,-1250.103752,NaN,...,0,0,0,0,0,1,0,0,0,0
34362,ZIXIN GROUP,ZIXI.SI,0.026796,0.026051,699.665413,30002.248368,47091.203918,9417.943054,-1737.998659,NaN,...,0,0,0,0,0,0,1,0,0,0
34363,ZIXIN GROUP,ZIXI.SI,0.015232,0.014507,3170.399293,30616.729481,48203.705381,8467.453980,1126.431046,NaN,...,0,0,0,0,0,0,0,1,0,0
34364,ZIXIN GROUP,ZIXI.SI,0.014150,0.012660,4908.432833,29653.904864,41217.132992,12174.641169,-1123.033942,NaN,...,0,0,0,0,0,0,0,0,1,0
34365,ZIXIN GROUP,ZIXI.SI,0.017214,0.016466,6923.888672,21832.964703,38514.364631,12918.953883,3338.076260,NaN,...,0,0,0,0,0,0,0,0,0,1

In [62]:
import pandas as pd
import numpy as np

# ============================================================
# 1. Set Multi-Index
# ============================================================
df = pd.read_csv("../processed_data/cleaned_panel_data.csv")
panel = df.set_index(['ric', 'Year']).sort_index()

# ============================================================
# 2. Panel Structure Check
# ============================================================
obs_per_firm = panel.groupby(level='ric').size()
print("=" * 60)
print("PANEL STRUCTURE CHECK")
print("=" * 60)
print(f"Total Firms (RICs): {panel.index.get_level_values('ric').nunique()}")
print(f"Total Firm-Year Observations: {len(panel)}")
print(f"Average Years per Firm: {obs_per_firm.mean():.2f}")
print(f"Temporal Range: {panel.index.get_level_values('Year').min()} to {panel.index.get_level_values('Year').max()}")
print(f"Min Years for a single firm: {obs_per_firm.min()}")
print(f"Max Years for a single firm: {obs_per_firm.max()}")

# Verify no non-ASEAN countries
if 'country' in df.columns:
    print(f"\nCountries in dataset: {sorted(df['country'].unique())}")

# ============================================================
# 3. Descriptive Statistics (Table 1)
# ============================================================
primary_vars = panel.select_dtypes(include=['number']).columns.tolist()

# Ensure primary variables are numeric
for col in primary_vars:
    df[col] = pd.to_numeric(df[col], errors='coerce')

desc_stats = df[primary_vars].describe().T
desc_stats['skewness'] = df[primary_vars].skew()
desc_stats['kurtosis'] = df[primary_vars].kurt()
desc_stats['missing_pct'] = (df[primary_vars].isna().sum() / len(df) * 100).round(1)

print("\n" + "=" * 60)
print("DESCRIPTIVE STATISTICS")
print("=" * 60)
display(desc_stats)

# ============================================================
# 4. Sanity Checks on Key Variables
# ============================================================
print("\n" + "=" * 60)
print("SANITY CHECKS")
print("=" * 60)

# ROA/ROE should be in decimal range (after /100)
if 'return_on_assets' in df.columns:
    roa = df['return_on_assets'].dropna()
    print(f"ROA range: [{roa.min():.4f}, {roa.max():.4f}] (should be decimal, e.g. 0.05 = 5%)")

if 'return_on_equity_total' in df.columns:
    roe = df['return_on_equity_total'].dropna()
    print(f"ROE range: [{roe.min():.4f}, {roe.max():.4f}]")

# Check environmental_investment encoding
if 'environmental_investment' in df.columns:
    print(f"\nenvironmental_investment value counts (NaN should exist, not be 0):")
    print(df['environmental_investment'].value_counts(dropna=False))

# Check for any remaining non-ASEAN
if 'country' in df.columns:
    non_asean = df[df['country'] == 'Other']
    print(f"\nNon-ASEAN ('Other') rows remaining: {len(non_asean)} (should be 0)")

# ============================================================
# 5. Correlation Matrix
# ============================================================
corr_vars = [c for c in primary_vars if c in df.columns and df[c].notna().sum() > 100]
corr_matrix = df[corr_vars].corr(method='pearson')
print("\n" + "=" * 60)
print("PEARSON CORRELATION MATRIX")
print("=" * 60)
display(corr_matrix)

# Flag high multicollinearity
print("\nHigh correlations (|r| > 0.8):")
for i in range(len(corr_matrix)):
    for j in range(i+1, len(corr_matrix)):
        r = corr_matrix.iloc[i, j]
        if abs(r) > 0.8:
            print(f"  {corr_matrix.index[i]} ↔ {corr_matrix.columns[j]}: {r:.3f}")

============================================================
PANEL STRUCTURE CHECK
============================================================
Total Firms (RICs): 4026
Total Firm-Year Observations: 37211
Average Years per Firm: 9.24
Temporal Range: 2015 to 2024
Min Years for a single firm: 3
Max Years for a single firm: 10

============================================================
DESCRIPTIVE STATISTICS
============================================================

,count,mean,std,min,25%,50%,75%,max,skewness,kurtosis,missing_pct
ask_price,28138.0,4.952161e-01,1.089517e+00,2.932691e-03,0.043499,0.144312,0.433960,7.626660e+00,4.569829,23.606153,24.4
bid_price,26124.0,4.945292e-01,1.088304e+00,2.878496e-03,0.044735,0.142159,0.432221,7.563913e+00,4.532988,23.156056,29.8
capital_expenditures,35763.0,4.654364e+04,1.785251e+05,0.000000e+00,340.937061,2113.640784,12313.490570,1.341913e+06,5.827424,35.880827,3.9
cash,31965.0,8.920163e+04,3.231391e+05,1.464619e+01,1801.115856,7145.475546,29455.907478,2.556012e+06,5.943299,38.452651,14.1
current_assets_total,31703.0,4.222193e+05,1.463410e+06,3.659180e+02,15187.288956,47243.764198,169303.008791,1.136774e+07,5.896601,37.425135,14.8
current_liabilities_total,31719.0,3.400595e+05,1.347547e+06,1.370675e+02,7164.830276,27005.403994,109471.128733,1.109957e+07,6.483217,44.931210,14.8
earnings_bef_interest_tax,31840.0,1.019595e+05,3.970979e+05,-1.055729e+05,586.814201,5650.495128,30029.226750,3.106821e+06,6.035833,39.053746,14.4
employees,16441.0,6.599597e+03,2.991969e+04,0.000000e+00,273.000000,900.000000,3123.000000,4.690000e+05,10.803748,136.543127,55.8
interest_expense_total,3472.0,2.746656e+05,9.800633e+05,0.000000e+00,1542.798075,14730.724693,73812.348679,1.235163e+07,7.330341,66.071815,90.7
long_term_debt,34094.0,4.157260e+05,1.667123e+06,0.000000e+00,191.492367,4931.556081,61758.901492,1.310428e+07,6.007154,38.907574,8.4
market_capitalization,29593.0,1.176506e+06,4.503296e+06,3.202285e+03,24563.224059,77193.228444,348398.242391,3.615380e+07,6.307551,42.581922,20.5
market_value,28167.0,8.330987e+02,2.642079e+03,2.884661e+00,23.871763,74.820074,321.445254,1.971984e+04,5.304889,31.022891,24.3
net_cash_flow_operating_actv,36633.0,3.031270e+06,8.394337e+07,-1.924003e+08,-168.076548,3981.422907,25433.880100,3.703388e+09,33.858241,1244.739975,1.6
net_sales_or_revenues,34669.0,6.802939e+05,2.455592e+06,0.000000e+00,17216.617125,61479.276628,236923.038754,1.859480e+07,5.776123,35.448075,6.8
operating_income,34632.0,8.605270e+04,3.619198e+05,-7.314807e+04,-80.921504,3521.931517,22264.731718,2.864177e+06,6.303457,42.039410,6.9
return_on_assets,36048.0,3.556434e-02,1.048264e-01,-4.620000e-01,0.007600,0.038400,0.076725,3.640000e-01,-1.282019,6.977064,3.1
return_on_equity_total,35874.0,2.514909e-02,3.208311e-01,-2.024600e+00,0.001125,0.060400,0.131700,7.978000e-01,-3.633554,20.039659,3.6
total_assets,37211.0,2.853666e+06,1.334366e+07,1.316960e+03,37268.634431,123092.731564,546696.562973,1.145297e+08,7.110387,53.219408,0.0
total_capital,32877.0,1.227153e+06,4.461774e+06,-2.057819e+03,23412.191838,79335.083026,344318.631965,3.432838e+07,5.771609,35.873898,11.6
total_debt,36397.0,7.085498e+05,3.019920e+06,0.000000e+00,2397.395132,19226.952524,132722.523422,2.433154e+07,6.530631,45.136735,2.2
total_liabilities,36300.0,1.840555e+06,9.032119e+06,1.375800e+02,11381.070923,48442.508865,259252.046422,7.604789e+07,7.035182,51.496006,2.4
tri,31475.0,3.873150e+07,6.871262e+09,0.000000e+00,46.885000,123.560000,380.470000,1.219044e+12,177.411950,31475.000000,15.4
emissions_intensity,35661.0,1.408063e+03,2.839351e+03,7.186331e+01,283.227656,513.771119,1151.689533,2.041377e+04,4.568169,23.866052,4.2
esg_score,5724.0,4.775031e+01,1.852141e+01,2.700000e-01,33.740000,48.195000,62.132500,9.195000e+01,-0.083627,-0.688710,84.6
estimated_total_carbon_footprint,35661.0,1.381066e+06,6.507138e+06,5.911280e+01,7020.196582,33505.360819,164768.458159,5.096074e+07,6.373988,41.950237,4.2
internal_carbon_pricing,155.0,5.047337e+04,3.588210e+05,2.000000e+00,20.000000,50.000000,200.000000,2.596320e+06,7.045870,48.267283,99.6
internal_carbon_price_per_tonne,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
green_bond_proceeds,37211.0,3.770086e-01,1.583517e+01,0.000000e+00,0.000000,0.000000,0.000000,1.022826e+03,47.940501,2468.095337,0.0
green_bond_issue,37211.0,8.330870e-04,2.885161e-02,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00,34.604222,1195.516468,0.0
green_bond_active,37211.0,3.224853e-03,5.669691e-02,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00,17.524830,305.136062,0.0
gic,37202.0,1.751707e+00,1.586172e+00,1.000000e+00,1.000000,1.000000,1.000000,6.000000e+00,1.965825,2.306925,0.0
ln_total_assets,37211.0,1.199758e+01,2.158051e+00,7.183082e+00,10.525907,11.720693,13.211649,1.855634e+01,0.587241,0.434465,0.0

============================================================
SANITY CHECKS
============================================================
ROA range: [-0.4620, 0.3640] (should be decimal, e.g. 0.05 = 5%)
ROE range: [-2.0246, 0.7978]

environmental_investment value counts (NaN should exist, not be 0):
environmental_investment
False    36390
True       821
Name: count, dtype: int64

============================================================
PEARSON CORRELATION MATRIX
============================================================

,ask_price,bid_price,capital_expenditures,cash,current_assets_total,current_liabilities_total,earnings_bef_interest_tax,employees,interest_expense_total,long_term_debt,...,tri,emissions_intensity,esg_score,estimated_total_carbon_footprint,internal_carbon_pricing,green_bond_proceeds,green_bond_issue,green_bond_active,gic,ln_total_assets
ask_price,1.000000,0.999155,0.304394,0.297450,0.322176,0.285563,0.376113,0.333489,0.591438,0.353205,...,0.230078,0.067506,0.155269,0.294574,-0.143991,0.033229,0.025106,0.097691,0.074913,0.338196
bid_price,0.999155,1.000000,0.314451,0.297430,0.330656,0.293346,0.377397,0.334667,0.588980,0.353615,...,0.233456,0.074557,0.165646,0.307449,-0.148958,0.034224,0.025835,0.100491,0.085315,0.345808
capital_expenditures,0.304394,0.314451,1.000000,0.703335,0.778444,0.823609,0.698562,0.561897,0.297741,0.751730,...,-0.001122,0.065202,0.127424,0.387585,-0.132228,0.049059,0.036739,0.092527,0.064583,0.507836
cash,0.297450,0.297430,0.703335,1.000000,0.894669,0.860438,0.807577,0.531824,0.544583,0.762660,...,-0.001475,0.125473,0.107035,0.459954,-0.138997,0.029403,0.018778,0.043456,0.012586,0.563805
current_assets_total,0.322176,0.330656,0.778444,0.894669,1.000000,0.952008,0.837192,0.653860,0.373835,0.849173,...,0.117573,0.094293,0.125666,0.477346,-0.143915,0.024851,0.012769,0.037023,-0.010376,0.607603
current_liabilities_total,0.285563,0.293346,0.823609,0.860438,0.952008,1.000000,0.847227,0.702826,0.532059,0.870664,...,0.098972,0.073993,0.071458,0.439726,-0.138879,0.021657,0.010679,0.037504,0.009613,0.568520
earnings_bef_interest_tax,0.376113,0.377397,0.698562,0.807577,0.837192,0.847227,1.000000,0.506264,0.735738,0.814232,...,-0.000853,0.204974,0.174406,0.612544,-0.110841,0.063719,0.052959,0.195532,0.115316,0.562378
employees,0.333489,0.334667,0.561897,0.531824,0.653860,0.702826,0.506264,1.000000,0.712537,0.515566,...,-0.001895,0.057830,-0.169217,0.352216,-0.115182,0.010565,0.004740,0.029073,-0.043247,0.354907
interest_expense_total,0.591438,0.588980,0.297741,0.544583,0.373835,0.532059,0.735738,0.712537,1.000000,0.645479,...,-0.005065,0.232977,0.318054,0.759026,0.500648,0.044075,0.043702,0.353038,-0.255923,0.465893
long_term_debt,0.353205,0.353615,0.751730,0.762660,0.849173,0.870664,0.814232,0.515566,0.645479,1.000000,...,-0.000603,0.110432,0.181670,0.498227,-0.145991,0.063496,0.051205,0.194879,0.115208,0.560180
market_capitalization,0.397231,0.398580,0.723801,0.708349,0.761493,0.791841,0.847510,0.539619,0.715417,0.792704,...,-0.001198,0.125615,0.182965,0.491781,-0.123523,0.073577,0.061079,0.209117,0.114178,0.550070
market_value,0.475285,0.476650,0.645747,0.616853,0.650760,0.633097,0.753034,0.475906,0.703183,0.664933,...,-0.001428,0.177937,0.294599,0.579769,-0.149692,0.074217,0.059367,0.205010,0.139682,0.583547
net_cash_flow_operating_actv,0.013598,0.013656,0.259635,0.259867,0.283101,0.302381,0.258196,0.811004,0.617742,0.279060,...,-0.000194,0.005070,0.014741,0.007184,-0.084965,0.000158,-0.000173,-0.000115,-0.015875,0.108640
net_sales_or_revenues,0.377121,0.377851,0.756087,0.800277,0.876783,0.905443,0.838717,0.655002,0.821785,0.803347,...,-0.001518,0.144140,0.111186,0.629767,-0.146987,0.046417,0.034374,0.135926,0.019818,0.555325
operating_income,0.376538,0.378543,0.692426,0.800164,0.830610,0.837004,0.947744,0.517417,0.733168,0.831442,...,-0.000993,0.181526,0.150808,0.608118,-0.097617,0.064047,0.052741,0.189462,0.092788,0.539082
return_on_assets,0.147506,0.143867,0.030417,0.019173,0.021383,0.005255,0.071059,-0.027841,-0.076031,-0.004806,...,0.001373,-0.003051,0.036268,0.024429,-0.234812,-0.000851,0.002516,0.000191,-0.000165,0.095605
return_on_equity_total,0.139088,0.137567,0.051637,0.036574,0.041580,0.022948,0.098313,0.014284,0.091812,0.031832,...,0.001026,0.003042,0.087308,0.056465,-0.186497,0.004143,0.006406,0.013647,0.026443,0.131175
total_assets,0.343505,0.358025,0.594854,0.784158,0.838182,0.870811,0.860875,0.489013,0.720164,0.837273,...,-0.000916,0.190746,0.147518,0.569898,-0.103959,0.071046,0.061356,0.200807,0.131429,0.526887
total_capital,0.388489,0.388957,0.754675,0.824923,0.893694,0.895359,0.893811,0.510661,0.698008,0.950915,...,-0.000772,0.143758,0.214056,0.557205,-0.142168,0.069456,0.057949,0.199779,0.131948,0.602804
total_debt,0.339175,0.358395,0.709831,0.767843,0.851825,0.895063,0.855818,0.534363,0.727683,0.956577,...,-0.000794,0.141689,0.152703,0.547219,-0.124577,0.068563,0.056970,0.193078,0.099272,0.545259
total_liabilities,0.324381,0.337222,0.543363,0.786534,0.818255,0.866036,0.826954,0.488646,0.724306,0.791191,...,-0.000980,0.216482,0.138878,0.577601,-0.101223,0.068639,0.061308,0.197714,0.128400,0.513207
tri,0.230078,0.233456,-0.001122,-0.001475,0.117573,0.098972,-0.000853,-0.001895,-0.005065,-0.000603,...,1.000000,-0.002307,0.084683,-0.001240,-0.052248,-0.000141,-0.000171,-0.000340,0.015090,0.003858
emissions_intensity,0.067506,0.074557,0.065202,0.125473,0.094293,0.073993,0.204974,0.057830,0.232977,0.110432,...,-0.002307,1.000000,0.173445,0.505700,-0.075846,0.024740,0.027465,0.060488,0.091437,0.234376
esg_score,0.155269,0.165646,0.127424,0.107035,0.125666,0.071458,0.174406,-0.169217,0.318054,0.181670,...,0.084683,0.173445,1.000000,0.228716,0.042684,0.052486,0.058025,0.129808,0.062942,0.342206
estimated_total_carbon_footprint,0.294574,0.307449,0.387585,0.459954,0.477346,0.439726,0.612544,0.352216,0.759026,0.498227,...,-0.001240,0.505700,0.228716,1.000000,-0.108576,0.071281,0.057607,0.188141,0.041157,0.421942
internal_carbon_pricing,-0.143991,-0.148958,-0.132228,-0.138997,-0.143915,-0.138879,-0.110841,-0.115182,0.500648,-0.145991,...,-0.052248,-0.075846,0.042684,-0.108576,1.000000,-0.018565,-0.019706,-0.044143,-0.075866,-0.213127
green_bond_proceeds,0.033229,0.034224,0.049059,0.029403,0.024851,0.021657,0.063719,0.010565,0.044075,0.063496,...,-0.000141,0.024740,0.052486,0.071281,-0.018565,1.000000,0.824533,0.418580,0.022485,0.049893
green_bond_issue,0.025106,0.025835,0.036739,0.018778,0.012769,0.010679,0.052959,0.004740,0.043702,0.051205,...,-0.000171,0.027465,0.058025,0.057607,-0.019706,0.824533,1.000000,0.507656,0.023315,0.048108
green_bond_active,0.097691,0.100491,0.092527,0.043456,0.037023,0.037504,0.195532,0.029073,0.353038,0.194879,...,-0.000340,0.060488,0.129808,0.188141,-0.044143,0.418580,0.507656,1.000000,0.060908,0.118146
gic,0.074913,0.085315,0.064583,0.012586,-0.010376,0.009613,0.115316,-0.043247,-0.255923,0.115208,...,0.015090,0.091437,0.062942,0.041157,-0.075866,0.022485,0.023315,0.060908,1.000000,0.216201
ln_total_assets,0.338196,0.345808,0.507836,0.563805,0.607603,0.568520,0.562378,0.354907,0.465893,0.560180,...,0.003858,0.234376,0.342206,0.421942,-0.213127,0.049893,0.048108,0.118146,0.216201,1.000000

High correlations (|r| > 0.8):
  ask_price ↔ bid_price: 0.999
  capital_expenditures ↔ current_liabilities_total: 0.824
  cash ↔ current_assets_total: 0.895
  cash ↔ current_liabilities_total: 0.860
  cash ↔ earnings_bef_interest_tax: 0.808
  cash ↔ net_sales_or_revenues: 0.800
  cash ↔ operating_income: 0.800
  cash ↔ total_capital: 0.825
  current_assets_total ↔ current_liabilities_total: 0.952
  current_assets_total ↔ earnings_bef_interest_tax: 0.837
  current_assets_total ↔ long_term_debt: 0.849
  current_assets_total ↔ net_sales_or_revenues: 0.877
  current_assets_total ↔ operating_income: 0.831
  current_assets_total ↔ total_assets: 0.838
  current_assets_total ↔ total_capital: 0.894
  current_assets_total ↔ total_debt: 0.852
  current_assets_total ↔ total_liabilities: 0.818
  current_liabilities_total ↔ earnings_bef_interest_tax: 0.847
  current_liabilities_total ↔ long_term_debt: 0.871
  current_liabilities_total ↔ net_sales_or_revenues: 0.905
  current_liabilities_total ↔ operating_income: 0.837
  current_liabilities_total ↔ total_assets: 0.871
  current_liabilities_total ↔ total_capital: 0.895
  current_liabilities_total ↔ total_debt: 0.895
  current_liabilities_total ↔ total_liabilities: 0.866
  earnings_bef_interest_tax ↔ long_term_debt: 0.814
  earnings_bef_interest_tax ↔ market_capitalization: 0.848
  earnings_bef_interest_tax ↔ net_sales_or_revenues: 0.839
  earnings_bef_interest_tax ↔ operating_income: 0.948
  earnings_bef_interest_tax ↔ total_assets: 0.861
  earnings_bef_interest_tax ↔ total_capital: 0.894
  earnings_bef_interest_tax ↔ total_debt: 0.856
  earnings_bef_interest_tax ↔ total_liabilities: 0.827
  employees ↔ net_cash_flow_operating_actv: 0.811
  interest_expense_total ↔ net_sales_or_revenues: 0.822
  long_term_debt ↔ net_sales_or_revenues: 0.803
  long_term_debt ↔ operating_income: 0.831
  long_term_debt ↔ total_assets: 0.837
  long_term_debt ↔ total_capital: 0.951
  long_term_debt ↔ total_debt: 0.957
  market_capitalization ↔ market_value: 0.853
  market_capitalization ↔ net_sales_or_revenues: 0.803
  market_capitalization ↔ operating_income: 0.859
  market_capitalization ↔ total_assets: 0.845
  market_capitalization ↔ total_capital: 0.864
  market_capitalization ↔ total_debt: 0.817
  net_sales_or_revenues ↔ operating_income: 0.845
  net_sales_or_revenues ↔ total_capital: 0.844
  net_sales_or_revenues ↔ total_debt: 0.824
  operating_income ↔ total_assets: 0.893
  operating_income ↔ total_capital: 0.908
  operating_income ↔ total_debt: 0.875
  operating_income ↔ total_liabilities: 0.851
  total_assets ↔ total_capital: 0.901
  total_assets ↔ total_debt: 0.908
  total_assets ↔ total_liabilities: 0.980
  total_capital ↔ total_debt: 0.954
  total_capital ↔ total_liabilities: 0.843
  total_debt ↔ total_liabilities: 0.870
  green_bond_proceeds ↔ green_bond_issue: 0.825